# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# Zbyněk Schwarz <zbynek.schwarz@gmail.com>, 2014
# OpenStack Infra <zanata@openstack.org>, 2015. #zanata
# Zbyněk Schwarz <zbynek.schwarz@gmail.com>, 2015. #zanata
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: cinder 9.0.0.0b4.dev103\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-09-11 18:25+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-12-21 12:13+0000\n"
"Last-Translator: Zbyněk Schwarz <zbynek.schwarz@gmail.com>\n"
"Language: cs\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Czech\n"

#, python-format
msgid ""
"%(exception)s: Exception during revert of retype for volume %(volume_name)s. "
"Failed to remove from new volume set %(new_vvs)s."
msgstr ""
"%(exception)s: Výjimka během vrácení přetypování svazku %(volume_name)s. "
"Nelze odstranit z nové sady svazků %(new_vvs)s."

#, python-format
msgid ""
"%(exception)s: Exception during revert of retype for volume %(volume_name)s. "
"Original volume set/QOS settings may not have been fully restored."
msgstr ""
"%(exception)s: Výjimka během vrácení přetypování svazku %(volume_name)s. "
"Původní nastavení sady svazků/QoS nemusí být zcela obnovena."

#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"%(fun)s: selhalo s nečekaným výstupem příkazového řádku.\n"
"Příkaz: %(cmd)s\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s\n"

#, python-format
msgid ""
"%(method)s %(url)s unexpected response status: %(response)s (expects: "
"%(expects)s)."
msgstr ""
"%(method)s %(url)s neočekávaná odpověď stavu: %(response)s (očekáváno: "
"%(expects)s)."

#, python-format
msgid "%(name)s: %(value)s"
msgstr "%(name)s: %(value)s"

#, python-format
msgid "%s"
msgstr "%s"

#, python-format
msgid "'%(value)s' is an invalid value for extra spec '%(key)s'"
msgstr "'%(value)s' je neplatná hodnota pro dodatečnou specifikaci '%(key)s'"

msgid "A valid secondary target MUST be specified in order to failover."
msgstr "Pro zavedení záložního systému MUSÍ být zadán platný druhotní cíl."

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting create_snapshot operation!"
msgstr ""
"Účet pro svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o "
"provedení operace vytvoření snímku!"

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting delete_volume operation!"
msgstr ""
"Účet pro svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o "
"provedení operace smazání svazku!"

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting unmanage operation!"
msgstr ""
"Účet pro svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o "
"provedení operace zrušení správy!"

#, python-format
msgid "Array Serial Number must be in the file %(fileName)s."
msgstr "Sériové číslo pole musí být v souboru %(fileName)s."

#, python-format
msgid "Array query failed - No response (%d)!"
msgstr "Dotaz na pole selhal - Žádná odpověď (%d)!"

msgid "Array query failed. No capabilities in response!"
msgstr "Dotaz na pole selhal. V odpovědi nebyly uvedeny schopnosti!"

msgid "Array query failed. No controllers in response!"
msgstr "Dotaz na pole selhal. V odpovědi nebyly uvedeny kontroléry!"

msgid "Array query failed. No global id in XML response!"
msgstr "Dotaz na pole selhal. V odpovědi XML nebylo globální id!"

msgid "Attaching snapshot from a remote node is not supported."
msgstr "Připojení snímku ke vzdálenému uzlu není podporováno."

#, python-format
msgid "Authorizing request: %(zfssaurl)s retry: %(retry)d ."
msgstr "Ověřování žádosti:  %(zfssaurl)s pokus: %(retry)d ."

msgid "Backend returned err for lun export."
msgstr "Při export lun vrátila podpůrná vrstva chybu!"

#, python-format
msgid "Backup id %s is not invalid. Skipping reset."
msgstr "ID zálohy %s není neplatné. Resetování je přeskočeno."

#, python-format
msgid ""
"Backup service %(configured_service)s does not support verify. Backup id "
"%(id)s is not verified. Skipping verify."
msgstr ""
"Zálohovací služba %(configured_service)s nepodporuje ověřování. Záloha s id "
"%(id)s není ověřena. Ověřování přeskočeno."

#, python-format
msgid "Backup volume metadata failed: %s."
msgstr "Záložní popisná data svazku selhala: %s"

#, python-format
msgid "Bad response from server: %(url)s. Error: %(err)s"
msgstr "Špatná odpověď od serveru: %(url)s. Chyba: %(err)s"

#, python-format
msgid ""
"CG snapshot %(cgsnap)s not found when creating consistency group %(cg)s from "
"source."
msgstr ""
"Nebyl nalezen snímek skupiny jednotnosti %(cgsnap)s při vytváření skupiny "
"%(cg)s ze zdroje."

#, python-format
msgid ""
"CLI fail: '%(cmd)s' = %(code)s\n"
"out: %(stdout)s\n"
"err: %(stderr)s"
msgstr ""
"Selhání rozhraní příkazového řádku: '%(cmd)s' = %(code)s\n"
"výstup: %(stdout)s\n"
"chyba: %(stderr)s"

msgid "Call to Nova delete snapshot failed"
msgstr "Volání Nova pro smazání snímku selhalo"

msgid "Call to Nova to create snapshot failed"
msgstr "Volání Nova pro vytvoření snímku selhalo"

#, python-format
msgid "Call to json.loads() raised an exception: %s."
msgstr "Volání json.loads() vyvolalo výjimku: %s."

#, python-format
msgid "Can not discovery in %(target_ip)s with %(target_iqn)s."
msgstr "Nelze zjišťovat v %(target_ip)s pomocí %(target_iqn)s."

msgid "Can not open the recent url, login again."
msgstr "Nelze otevřít nedávnou adresu url, probíhá znovu přihlašování."

#, python-format
msgid "Can't find volume to map %(key)s, %(msg)s"
msgstr "Nelze najít svazek k mapování %(key)s, %(msg)s"

msgid "Can't open the recent url, relogin."
msgstr "Nelze otevřít nedávnou adresu url, probíhá znovu přihlašování."

#, python-format
msgid ""
"Cannot add and verify tier policy association for storage group : "
"%(storageGroupName)s to FAST policy : %(fastPolicyName)s."
msgstr ""
"Nelze přidat a ověřit přidružení zásady vrstvení skupiny úložiště : "
"%(storageGroupName)s k zásadě FAST : %(fastPolicyName)s."

#, python-format
msgid "Cannot clone image %(image)s to volume %(volume)s. Error: %(error)s."
msgstr "Nelze klonovat obraz %(image)s do svazku %(volume)s. Chyba: %(error)s."

#, python-format
msgid "Cannot create or find an initiator group with name %(igGroupName)s."
msgstr "Nelze vytvořit nebo najít skupinu zavaděče s názvem %(igGroupName)s."

#, python-format
msgid "Cannot delete file %s."
msgstr "Nelze smazat soubor %s."

msgid "Cannot detect replica status."
msgstr "Nelze zjistit stav repliky."

msgid "Cannot determine if Tiering Policies are supported."
msgstr "Nelze zjistit zda zásady vrstvení jsou podporovány."

msgid "Cannot determine whether Tiering Policy is supported on this array."
msgstr "Nelze zjistit zdali je na tomto poli podporována zásada vrstvení."

#, python-format
msgid "Cannot find Consistency Group %s"
msgstr "Nelze najít skupinu jednotnosti %s."

#, python-format
msgid ""
"Cannot find a portGroup with name %(pgGroupName)s. The port group for a "
"masking view must be pre-defined."
msgstr ""
"Nelze najít skupinu portů s názvem %(pgGroupName)s. Skupina pro zamaskování "
"musí být předem určena."

#, python-format
msgid "Cannot find the fast policy %(fastPolicyName)s."
msgstr "Nelze najít zásadu fast %(fastPolicyName)s."

#, python-format
msgid ""
"Cannot find the new masking view just created with name %(maskingViewName)s."
msgstr "Nelze najít právě vytvořené zamaskování s názvem %(maskingViewName)s."

#, python-format
msgid "Cannot get QoS spec for volume %s."
msgstr "Nelze získat specifikaci QoS pro svazek %s."

#, python-format
msgid "Cannot get storage Group from job : %(storageGroupName)s."
msgstr "Nelze získat skupinu úložiště z úkolu : %(storageGroupName)s."

msgid "Cannot get storage system."
msgstr "Nelze získat úložný systém."

#, python-format
msgid ""
"Changing the volume name from %(tmp)s to %(orig)s failed because %(reason)s"
msgstr "Změna názvu svazku z %(tmp)s na %(orig)s selhala protože %(reason)s"

#, python-format
msgid ""
"Changing the volume name from %(tmp)s to %(orig)s failed because %(reason)s."
msgstr "Změna názvu svazku z %(tmp)s na %(orig)s selhala protože %(reason)s."

#, python-format
msgid "Clone %s not in prepared state!"
msgstr "Klon %s není v stavu připraveno!"

#, python-format
msgid ""
"Clone volume \"%s\" already exists. Please check the results of \"dog vdi "
"list\"."
msgstr ""
"Klon svazku \"%s\" již existuje. Prosím zkontrolujte výstup příkazu \"dog "
"vdi list\"."

#, python-format
msgid "Cloning of volume %s failed."
msgstr "Klonování svazku %s selhalo."

#, python-format
msgid ""
"CloudByte does not have a volume corresponding to OpenStack volume [%s]."
msgstr "CloudByte nemá svazek odpovídající svazku OpenStack [%s]."

#, python-format
msgid ""
"CloudByte operation [%(operation)s] failed for volume [%(vol)s]. Exhausted "
"all [%(max)s] attempts."
msgstr ""
"Operace CloudByte [%(operation)s] selhala u svazku [%(vol)s]. Využito všech "
"[%(max)s] pokusů."

#, python-format
msgid ""
"CloudByte snapshot information is not available for OpenStack volume [%s]."
msgstr ""
"Informace o snímku CloudByte nejsou dostupné pro svazek OpenStack [%s]."

#, python-format
msgid "CloudByte volume information not available for OpenStack volume [%s]."
msgstr ""
"Informace o svazku CloudByte nejsou dostupné pro svazek OpenStack [%s]."

#, python-format
msgid "Cmd     :%s"
msgstr "Příkaz     :%s"

#, python-format
msgid "Commit clone failed: %(name)s (%(status)d)!"
msgstr "Odevzdání klonu selhalo: %(name)s (%(status)d)!"

#, python-format
msgid "Commit failed for %s!"
msgstr "Odevzdání selhalo pro %s!"

#, python-format
msgid "Compute cluster: %s not found."
msgstr "Výpočetní cluster: %s nenalezen."

#, python-format
msgid "Configuration value %s is not set."
msgstr "Konfigurační volba %s není nastavena."

#, python-format
msgid "Conflict detected in Virtual Volume Set %(volume_set)s: %(error)s"
msgstr "V sadě virtuálního svazku %(volume_set)s zjištěn konflikt: %(error)s"

#, python-format
msgid "Connect to Flexvisor error: %s."
msgstr "Chyba při připojení k Flexvisor: %s."

#, python-format
msgid "Connect to Flexvisor failed: %s."
msgstr "Připojení k Flexvisor selhalo: %s."

msgid "Connection error while sending a heartbeat to coordination backend."
msgstr ""
"Chyba připojení při odesílání informací o aktivitě do vrstvy pro koordinaci."

#, python-format
msgid "Connection to %s failed and no secondary!"
msgstr "Připojení k %s selhalo a žádné druhotné připojení není nastaveno!"

#, python-format
msgid "Controller GET failed (%d)"
msgstr "Získání kontroléru selhalo (%d)!"

#, python-format
msgid "Copy offload workflow unsuccessful. %s"
msgstr "Kopírování postupu snížení zátěže bylo neúspěšné. %s"

#, python-format
msgid "Copy snapshot to volume for snapshot %(snap)s volume %(vol)s failed!"
msgstr ""
"Kopírování snímku do svazku pro snímek %(snap)s a svazek %(vol)s selhalo!"

#, python-format
msgid "Could not GET allocation information (%d)!"
msgstr "Nelze získat informace o přidělení (%d)!"

#, python-format
msgid "Could not connect to %(primary)s or %(secondary)s!"
msgstr "Nelze se připojit k %(primary)s nebo %(secondary)s!"

#, python-format
msgid "Could not create snapshot set. Error: '%s'"
msgstr "Nelze vytvořit sadu snímků. Chyba: '%s'"

msgid "Could not decode scheduler options."
msgstr "Nelze rozšifrovat volby plánovače."

#, python-format
msgid "Could not delete failed image volume %(id)s."
msgstr "Nelze smazat nezdařený svazek obrazu %(id)s."

#, python-format
msgid "Could not delete the image volume %(id)s."
msgstr "Nelze smazat svazek obrazu %(id)s."

#, python-format
msgid "Could not find a host for consistency group %(group_id)s."
msgstr "Nelze najít hostitele pro skupinu jednotnosti %(group_id)s."

#, python-format
msgid "Could not find any hosts (%s)"
msgstr "Nelze najít žádné hostitele (%s)"

#, python-format
msgid ""
"Could not find port group : %(portGroupName)s. Check that the EMC "
"configuration file has the correct port group name."
msgstr ""
"Nelze najít skupinu portů : %(portGroupName)s. Zkontrolujte, že soubor s "
"nastavením EMC má správný název skupiny."

#, python-format
msgid "Could not find volume with name %(name)s. Error: %(error)s"
msgstr "Nelze najít svazek s názvem %(name)s. Chyba: %(error)s"

#, python-format
msgid "Could not log in to 3PAR array (%s) with the provided credentials."
msgstr ""
"Nelze se přihlásit do pole 3PAR (%s) pomocí zadaných přihlašovacích údajů."

#, python-format
msgid "Could not stat scheduler options file %(filename)s."
msgstr "Nelze vyhodnotit soubor voleb plánovače %(filename)s."

#, python-format
msgid "Could not validate device %s"
msgstr "Nelze ověřit zařízení %s"

#, python-format
msgid ""
"Create clone_image_volume: %(volume_id)sfor image %(image_id)s, failed "
"(Exception: %(except)s)"
msgstr ""
"Vytvoření klonu svazku obrazu: %(volume_id)s pro obraz %(image_id)s selhalo "
"(Výjimka: %(except)s)"

#, python-format
msgid ""
"Create consistency group from snapshot-%(snap)s failed: SnapshotNotFound."
msgstr ""
"Vytvoření skupiny jednotnosti ze snímku %(snap)s selhalo: Snímek nebyl "
"nalezen."

#, python-format
msgid "Create consistency group from source %(source)s failed."
msgstr "Vytvoření skupiny jednotnosti ze zdroje %(source)s selhalo."

#, python-format
msgid ""
"Create consistency group from source cg-%(cg)s failed: "
"ConsistencyGroupNotFound."
msgstr ""
"Vytvoření skupiny jednotnosti ze zdrojové skupiny jednotnosti %(cg)s "
"selhalo: Skupina nebyla nalezena."

#, python-format
msgid "Create hypermetro error: %s."
msgstr "Chyba při vytváření hypermetra: %s."

#, python-format
msgid ""
"Create new lun from lun for source %(src)s => destination %(dest)s failed!"
msgstr "Vytvoření nového lun z lun pro zdroj %(src)s => cíl %(dest)s selhalo!"

#, python-format
msgid "Create snapshot notification failed: %s"
msgstr "Oznámení o vytvořeni snímku selhalo: %s"

#, python-format
msgid "Create volume failed from snapshot: %s"
msgstr "Vytvoření svazku ze snímku selhalo: %s"

#, python-format
msgid "Create volume notification failed: %s"
msgstr "Oznámení o vytvoření svazku selhalo: %s"

#, python-format
msgid "Creation of snapshot failed for volume: %s"
msgstr "Vytvoření snímku selhalo u svazku: %s"

#, python-format
msgid "Creation of volume %s failed."
msgstr "Vytvoření svazku %s selhalo."

msgid ""
"Creation request failed. Please verify the extra-specs set for your volume "
"types are entered correctly."
msgstr ""
"Žádost o vytvoření selhala. Prosím ověřte správnost dodatečných specifikací "
"nastavených pro vaše typy svazků."

msgid "DB error:"
msgstr "Chyba databáze:"

msgid "DBError encountered: "
msgstr "Zjištěna chyba databáze:"

msgid "Default Storage Profile was not found."
msgstr "Výchozí profil úložiště nebyl nalezen."

msgid ""
"Default volume type is not found. Please check default_volume_type config:"
msgstr ""
"Výchozí typ svazku nenalezen. Prosím zkontrolujte nastavení "
"default_volume_type:"

msgid "Delete consistency group failed to update usages."
msgstr "Nelze aktualizovat využití při mazání skupin jednotnosti."

#, python-format
msgid "Delete hypermetro error: %s."
msgstr "Chyba při mazání hypermetra: %s"

msgid "Delete snapshot failed, due to snapshot busy."
msgstr "Smazání snímku selhalo, protože snímek je zaneprázdněn."

#, python-format
msgid "Delete snapshot notification failed: %s"
msgstr "Oznámení o smazáni snímku selhalo: %s"

#, python-format
msgid "Delete volume notification failed: %s"
msgstr "Oznámení o smazáni svazku selhalo: %s"

#, python-format
msgid "Deleting snapshot %s failed"
msgstr "Mazání snímku %s selhalo"

#, python-format
msgid "Deleting zone failed %s"
msgstr "Mazání zóny %s selhalo"

#, python-format
msgid "Deletion of volume %s failed."
msgstr "Smazání svazku %s selhalo."

#, python-format
msgid "Destination Volume Group %s does not exist"
msgstr "Cílová skupina svazku %s neexistuje"

#, python-format
msgid "Detach attachment %(attach_id)s failed."
msgstr "Odpojení zařízení %(attach_id)s selhalo."

#, python-format
msgid "Detach migration source volume failed:  %(err)s"
msgstr "Odpojení zdrojového svazku přesunu selhalo: %(err)s"

msgid "Detach volume failed, due to remove-export failure."
msgstr "Chyba při odpojování svazku, kvůli selhání při odebrání exportu."

msgid "Detach volume failed, due to uninitialized driver."
msgstr "Odpojení svazku selhalo kvůli nezavedenému ovladači."

msgid "Detaching snapshot from a remote node is not supported."
msgstr "Odpojení snímku od vzdáleného uzle není podporováno."

#, python-format
msgid "Did not find expected column name in lsvdisk: %s."
msgstr "Nenalezen očekávaný sloupec v lsvdisku: %s."

msgid "Differential restore failed, trying full restore"
msgstr "Rozdílová obnova selhala, pokus o celkovou obnovu"

#, python-format
msgid "Disconnection failed with message: %(msg)s."
msgstr "Odpojení selhalo se zprávou: %(msg)s."

#, python-format
msgid ""
"Driver-based migration of volume %(vol)s failed. Move from %(src)s to "
"%(dst)s failed with error: %(error)s."
msgstr ""
"Přesun svazku %(vol)s za pomocí ovladače selhal. Přesun z %(src)s do %(dst)s "
"selhal s chybou: %(error)s."

#, python-format
msgid "Error Attaching volume %(vol)s."
msgstr "Chyba při připojování svazku %(vol)s."

#, python-format
msgid ""
"Error Create Group: %(groupName)s. Return code: %(rc)lu.  Error: %(error)s."
msgstr ""
"Chyba při vyváření skupiny: %(groupName)s. Návratový kód: %(rc)lu. Chyba: "
"%(error)s."

#, python-format
msgid ""
"Error Getting Snapshot: %(snapshot)s of Volume: %(lun)s in Pool: %(pool)s, "
"Project: %(project)s  Return code: %(ret.status)d, Message: %(ret.data)s."
msgstr ""
"Chyba při získávání snímku: %(snapshot)s ve svazku %(lun)s v zásobě "
"%(pool)s, projekt %(project)s, návratový kód: %(ret.status)d, zpráva: "
"%(ret.data)s."

#, python-format
msgid ""
"Error Setting Volume: %(lun)s to InitiatorGroup: %(initiatorgroup)s Pool: "
"%(pool)s Project: %(project)s  Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"Chyba při nastavování svazku: %(lun)s do skupiny zavaděče "
"%(initiatorgroup)s, zásoba %(pool)s, projekt %(project)s, návratový kód: "
"%(ret.status)d, zpráva: %(ret.data)s."

msgid "Error activating LV"
msgstr "Chyba při aktivaci logického svazku"

#, python-format
msgid "Error cleaning up failed volume creation.  Msg - %s."
msgstr "Chyba při čištění selhaného vytváření svazku. Zpráva - %s"

msgid "Error cloning volume"
msgstr "Chyba při klonování svazku"

msgid "Error closing channel."
msgstr "Chyba při uzavírání kanálu."

#, python-format
msgid ""
"Error contacting glance server '%(netloc)s' for '%(method)s', %(extra)s."
msgstr ""
"Chyba při kontaktování serveru glance '%(netloc)s' pro '%(method)s', "
"%(extra)s."

#, python-format
msgid "Error creating QOS rule %s"
msgstr "Chyba při vytváření pravidla QOS %s"

msgid "Error creating Volume"
msgstr "Chyba při vytváření svazku"

msgid "Error creating Volume Group"
msgstr "Chyba při vytváření skupiny svazku"

msgid "Error creating chap record."
msgstr "Chyba při vytváření záznamu chap."

msgid "Error creating cloned volume"
msgstr "Chyba při vytváření klonovaného svazku"

msgid "Error creating snapshot"
msgstr "Chyba při vytváření snímku"

msgid "Error creating volume"
msgstr "Chyba při vytváření svazku"

#, python-format
msgid "Error creating volume. Msg - %s."
msgstr "Chyba při vytváření svazku. Zpráva - %s."

msgid "Error deactivating LV"
msgstr "Chyba při deaktivaci logického svazku"

msgid "Error deleting snapshot"
msgstr "Chyba při mazání snímku"

#, python-format
msgid "Error detaching snapshot %(snapshot)s, due to remove export failure."
msgstr ""
"Chyba při odpojování snímku %(snapshot)s, kvůli selhání při odebrání exportu."

#, python-format
msgid "Error detaching volume %(volume)s, due to remove export failure."
msgstr ""
"Chyba při odpojování svazku %(volume)s, kvůli selhání při odebrání exportu."

#, python-format
msgid "Error detaching volume %s"
msgstr "Chyba při odpojování svazku %s"

#, python-format
msgid "Error disassociating storage group from policy: %s."
msgstr "Chyba při odloučení skupiny úložiště od zásady: %s"

msgid "Error during re-export on driver init."
msgstr "Chyba při znovu exportování během zavádění ovladače."

msgid "Error executing SSH command."
msgstr "Chyba při provádění příkazu SSH."

msgid "Error executing command via ssh."
msgstr "Chyba při provádění příkazu pomocí ssh."

#, python-format
msgid "Error executing command via ssh: %s"
msgstr "Chyba při provádění příkazu pomocí ssh: %s"

msgid "Error extending Volume"
msgstr "Chyba při rozšiřování svazku"

msgid "Error extending volume"
msgstr "Chyba při rozšiřování svazku"

#, python-format
msgid "Error extending volume %(id)s. Ex: %(ex)s"
msgstr "Chyba při rozšiřování svazku %(id)s. Výjimka: %(ex)s"

#, python-format
msgid "Error extending volume: %(vol)s. Exception: %(ex)s"
msgstr "Chyba při rozšiřování svazku: %(vol)s. Výjimka: %(ex)s"

#, python-format
msgid "Error finding target pool instance name for pool: %(targetPoolName)s."
msgstr "Chyba při hledání cílového názvu instance zásoby: %(targetPoolName)s."

#, python-format
msgid "Error getting LUN attribute. Exception: %s"
msgstr "Chyba při získávání vlastnosti LUN. Výjimka: %s"

msgid "Error getting active FC target ports."
msgstr "Chyba při získávání aktivních cílových portů FC."

msgid "Error getting active ISCSI target iqns."
msgstr "Chyba při získávání aktivních cílových iqn iSCSI."

msgid "Error getting active ISCSI target portals."
msgstr "Chyba při získávání aktivních cílových portálů iSCSI."

msgid "Error getting array, pool, SLO and workload."
msgstr "Chyba při získávání pole, zásobu, SLO a vytížení."

msgid "Error getting chap record."
msgstr "Chyba při získávání záznamu chap."

msgid "Error getting name server info."
msgstr "Při získávání informací o jmenném serveru nastala chyba."

msgid "Error getting show fcns database info."
msgstr "Při získávání informací o zobrazení databáze fcns nastala chyba."

msgid "Error getting target pool name and array."
msgstr "Chyba při získávání názvu cílového pole a zásoby."

#, python-format
msgid "Error in copying volume: %s"
msgstr "Chyba při kopírování svazku %s"

#, python-format
msgid ""
"Error in extending volume size: Volume: %(volume)s Vol_Size: %(vol_size)d "
"with Snapshot: %(snapshot)s Snap_Size: %(snap_size)d"
msgstr ""
"Chyba při rozšiřování velikost svazku: Svazek: %(volume)s, velikost svazku: "
"%(vol_size)d se snímkem: %(snapshot)s, velikost svazku: %(snap_size)d"

#, python-format
msgid "Error in workflow copy from cache. %s."
msgstr "Chyba v postupu při kopírování z mezipaměti. %s."

#, python-format
msgid "Error invalid json: %s"
msgstr "Chyba neplatný json: %s"

msgid "Error manage existing get volume size."
msgstr "Chyba při získávání velikosti spravovaného svazku."

msgid "Error manage existing volume."
msgstr "Chyba při správě existujícího svazku."

#, python-format
msgid "Error mapping volume: %s"
msgstr "Chyba při mapování svazku: %s"

#, python-format
msgid ""
"Error migrating volume: %(volumename)s. to target pool %(targetPoolName)s."
msgstr ""
"Chyba při přesunu svazku: %(volumename)s. do  cílové zásoby "
"%(targetPoolName)s."

#, python-format
msgid "Error migrating volume: %s"
msgstr "Chyba při přesunování svazku: %s"

#, python-format
msgid ""
"Error occurred in the volume driver when updating consistency group "
"%(group_id)s."
msgstr ""
"Při aktualizaci skupiny jednotnosti %(group_id)s nastala chyba v ovladači "
"svazku."

msgid ""
"Error occurred when adding hostgroup and lungroup to view. Remove lun from "
"lungroup now."
msgstr ""
"Při přidávání skupiny hostitele a lun do zobrazení nastala chyba. Prosím "
"odstraňte lun ze skupiny."

#, python-format
msgid ""
"Error occurred when building request spec list for consistency group %s."
msgstr ""
"Při sestavování seznamu žádaných specifikací pro skupinu jednotnosti %s "
"nastala chyba."

#, python-format
msgid "Error occurred when creating cgsnapshot %s."
msgstr "Při vytváření snímku skupiny jednotnosti %s nastala chyba."

#, python-format
msgid ""
"Error occurred when creating cloned volume in the process of creating "
"consistency group %(group)s from source CG %(source_cg)s."
msgstr ""
"Při vytváření klonovaného svazku během vytváření skupiny jednotnosti "
"%(group)s ze zdrojové skupiny jednotnosti %(source_cg)s nastala chyba."

#, python-format
msgid ""
"Error occurred when creating consistency group %(cg)s from cgsnapshot "
"%(cgsnap)s."
msgstr ""
"Při vytváření skupiny jednotnosti %(cg)s ze snímku %(cgsnap)s nastala chyba."

#, python-format
msgid ""
"Error occurred when creating consistency group %(group)s from cgsnapshot "
"%(cgsnap)s."
msgstr ""
"Při vytváření skupiny jednotnosti %(group)s ze snímku %(cgsnap)s nastala "
"chyba."

#, python-format
msgid ""
"Error occurred when creating consistency group %(group)s from source CG "
"%(source_cg)s."
msgstr ""
"Při vytváření skupiny jednotnosti %(group)s ze zdrojové skupiny jednotnosti "
"%(source_cg)s nastala chyba."

#, python-format
msgid "Error occurred when creating consistency group %s."
msgstr "Při vytváření skupiny jednotnosti %s nastala chyba."

#, python-format
msgid ""
"Error occurred when creating volume entry from snapshot in the process of "
"creating consistency group %(group)s from cgsnapshot %(cgsnap)s."
msgstr ""
"Při vytváření záznamu o svazku ze snímku během vytváření skupiny jednotnosti "
"%(group)s ze snímku skupiny jednotnosti %(cgsnap)s nastala chyba."

#, python-format
msgid "Error occurred when updating consistency group %(group_id)s."
msgstr "Při aktualizaci skupiny jednotnosti %(group_id)s nastala chyba."

#, python-format
msgid "Error occurred while cloning backing: %s during retype."
msgstr "Při klonování zálohy nastala chyba: %s během přetypování."

#, python-format
msgid "Error occurred while copying %(src)s to %(dst)s."
msgstr "Při kopírování %(src)s do %(dst)s nastala chyba."

#, python-format
msgid "Error occurred while copying image: %(id)s to volume: %(vol)s."
msgstr "Při kopírování obrazu nastala chyba: %(id)s do svazku %(vol)s."

#, python-format
msgid "Error occurred while copying image: %(image_id)s to %(path)s."
msgstr "Při kopírování obrazu nastala chyba: %(image_id)s do %(path)s."

msgid "Error occurred while creating temporary backing."
msgstr "Při vytváření dočasné zálohy nastala chyba."

#, python-format
msgid "Error occurred while creating volume: %(id)s from image: %(image_id)s."
msgstr "Při vytváření svazku nastala chyba: %(id)s z obrazu %(image_id)s."

#, python-format
msgid ""
"Error on execute %(command)s. Error code: %(exit_code)d Error msg: %(result)s"
msgstr ""
"Chyba při provádění %(command)s. Kód chyby: %(exit_code)d Chybová zpráva: "
"%(result)s"

#, python-format
msgid ""
"Error on execute command. Error code: %(exit_code)d Error msg: %(result)s"
msgstr ""
"Chyba při provádění příkazu. Kód chyby: %(exit_code)d Chybová zpráva: "
"%(result)s"

msgid "Error parsing array from host capabilities."
msgstr "Chyba při zpracování pole ze schopností hostitele."

msgid "Error parsing array, pool, SLO and workload."
msgstr "Chyba při zpracování pole, zásoby, SLO a vytížení."

msgid "Error parsing target pool name, array, and fast policy."
msgstr "Chyba při zpracování názvu cílového pole, zásoby a zásady fast."

#, python-format
msgid ""
"Error provisioning volume %(lun_name)s on %(volume_name)s. Details: %(ex)s"
msgstr ""
"Chyba při poskytování svazku %(lun_name)s v %(volume_name)s. Podrobnosti: "
"%(ex)s"

msgid "Error querying thin pool about data_percent"
msgstr "Chyba při dotazování mělké zásoby o procentech dat"

msgid "Error renaming logical volume"
msgstr "Chyba při přejmenování logického svazku"

#, python-format
msgid "Error resolving host %(host)s. Error - %(e)s."
msgstr "Nelze převést na ip adresu hostitele %(host)s. Chyba - %(e)s."

#, python-format
msgid "Error retrieving LUN %(vol)s number"
msgstr "Chyba při získávání čísla LUN %(vol)s"

#, python-format
msgid "Error running SSH command: \"%s\"."
msgstr "Chyba při provádění příkazu SSH: \"%s\"."

#, python-format
msgid "Error running SSH command: %s"
msgstr "Chyba při provádění příkazu SSH: %s"

msgid "Error running command."
msgstr "Chyba při provádění příkazu."

#, python-format
msgid ""
"Error scheduling %(volume_id)s from last vol-service: %(last_host)s : %(exc)s"
msgstr ""
"Chyba při plánování %(volume_id)s z poslední služby svazku: %(last_host)s : "
"%(exc)s"

msgid "Error sending a heartbeat to coordination backend."
msgstr "Chyba při odesílání informací o aktivitě do vrstvy pro koordinaci."

#, python-format
msgid "Error setting Flash Cache policy to %s - exception"
msgstr "Chyba při nastavování zásady mezipaměti Flash na %s - došlo k výjimce"

msgid "Error starting coordination backend."
msgstr "Chyba při spouštění podpůrné vrstvy pro koordinaci."

#, python-format
msgid "Error unmapping volume: %s"
msgstr "Chyba při zrušení mapování svazku: %s"

#, python-format
msgid "Error verifying LUN container %(bkt)s"
msgstr "Chyba při ověřování kontejneru LUN %(bkt)s"

#, python-format
msgid "Error verifying iSCSI service %(serv)s on host %(hst)s"
msgstr "Chyba při ověřování služby iSCSI %(serv)s, na hostiteli %(hst)s"

msgid "Error: unable to snap replay"
msgstr "Chyba: Nelze vytvořit snímek ze zpětného načtení"

#, python-format
msgid "Exception cloning volume %(name)s from source volume %(source)s."
msgstr "Výjimka při klonování svazku %(name)s ze zdrojového svazku %(source)s."

#, python-format
msgid "Exception creating LUN %(name)s in pool %(pool)s."
msgstr "Při vytváření LUN %(name)s v zásobě %(pool)s došlo k výjimce."

#, python-format
msgid "Exception creating vol %(name)s on pool %(pool)s."
msgstr "Výjimka při vytváření svazku %(name)s v zásobě %(pool)s."

#, python-format
msgid ""
"Exception creating volume %(name)s from source %(source)s on share %(share)s."
msgstr ""
"Výjimka při vytváření svazku %(name)s ze zdroje %(source)s ve sdílení "
"%(share)s."

#, python-format
msgid "Exception details: %s"
msgstr "Podrobnosti výjimky: %s"

#, python-format
msgid "Exception during mounting %s"
msgstr "Při připojování %s došlo k výjimce"

#, python-format
msgid "Exception during mounting %s."
msgstr "Při připojování %s došlo k výjimce."

#, python-format
msgid "Exception during snapCPG revert: %s"
msgstr "Výjimka během vrácení snímku společné skupiny poskytování: %s"

msgid "Exception encountered: "
msgstr "Zjištěna výjimka:"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Zachycování výjimky zdroje: %s"

msgid "Exception in string format operation"
msgstr "Výjimka při operaci s formátem řetězce"

msgid "Exception loading extension."
msgstr "Výjimka během načítání rozšíření."

#, python-format
msgid "Exception: %(ex)s"
msgstr "Výjimka: %(ex)s"

#, python-format
msgid "Exception: %s"
msgstr "Výjimka: %s"

#, python-format
msgid "Exception: %s."
msgstr "Výjimka: %s."

#, python-format
msgid "Exec of \"rm\" command on backing file for %s was unsuccessful."
msgstr "Spuštění příkazu \"rm\" na záložní soubor %s bylo neúspěšné."

#, python-format
msgid "Exists snapshot notification failed: %s"
msgstr "Oznámení o existenci snímku selhalo: %s"

#, python-format
msgid "Exists volume notification failed: %s"
msgstr "Oznámení o existenci svazku selhalo: %s"

msgid "Extend volume failed."
msgstr "Rozšíření svazku selhalo."

#, python-format
msgid "Extension of volume %s failed."
msgstr "Rozšíření snímku %s selhalo."

msgid ""
"Extra spec replication:mode must be set and must be either 'sync' or "
"'periodic'."
msgstr ""
"Dodatečná specifikace replication:mode musí být zadána a musí mít hodnotu "
"'sync' nebo 'periodic'."

msgid ""
"Extra spec replication:sync_period must be greater than 299 and less than "
"31622401 seconds."
msgstr ""
"Dodatečná specifikace  replication:sync_period musí být větší než 299 a "
"menší než 31622401 vteřin."

msgid "FAST is not supported on this array."
msgstr "FAST není podporován v tomto poli."

#, python-format
msgid "Failed collecting fcns database info for fabric %s"
msgstr "Shromažďování informací databáze fcns pro fabric %s selhalo"

#, python-format
msgid "Failed collecting name server info from fabric %s"
msgstr "Shromáždění informací o jmenném serveru z fabric %s selhalo"

#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr "Shromáždění informací nsshow pro fabric %s selhalo"

msgid "Failed collecting show fcns database for fabric"
msgstr "Shromažďování zobrazení databáze fcns pro fabric selhalo"

#, python-format
msgid "Failed destroying volume entry %s"
msgstr "Nelze zničit položku svazku %s"

#, python-format
msgid "Failed destroying volume entry: %s."
msgstr "Nelze zničit položku svazku: %s."

#, python-format
msgid ""
"Failed fetching snapshot %(snapshot_id)s bootable flag using the provided "
"glance snapshot %(snapshot_ref_id)s volume reference"
msgstr ""
"Získání příznaku zaveditelnosti snímku %(snapshot_id)s selhalo pomocí "
"zadaného odkazu na svazek snímku glance %(snapshot_ref_id)s"

#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr "Získání aktivní zóny nastavené z fabric %s selhalo"

#, python-format
msgid "Failed getting zone status from fabric %s"
msgstr "Získání stavu zóny z fabric %s selhalo"

#, python-format
msgid "Failed image conversion during cache creation: %s"
msgstr "Během vytváření mezipaměti došlo k chybě v převodu obrazu: %s"

#, python-format
msgid ""
"Failed notifying about the snapshot action %(event)s for snapshot %(snp_id)s."
msgstr "Oznámení činnosti snímku %(event)s selhalo u snímku %(snp_id)s."

#, python-format
msgid ""
"Failed notifying about the volume action %(event)s for volume %(volume_id)s"
msgstr "Oznámení činnosti svazku %(event)s selhalo u svazku %(volume_id)s"

#, python-format
msgid "Failed notifying on %(topic)s payload %(payload)s"
msgstr "Oznámení %(topic)s s obsahem %(payload)s selhalo."

#, python-format
msgid ""
"Failed recovery attempt to create iscsi backing lun for Volume ID:"
"%(vol_id)s: %(e)s"
msgstr ""
"Selhal pokus o obnovu vytvoření lun zálohující iscsi pro svazek s ID:"
"%(vol_id)s: %(e)s"

#, python-format
msgid "Failed rolling back quota for %s reservations"
msgstr "Nelze vrátit zpět kvóty pro rezervace %s"

#, python-format
msgid "Failed rolling back quota for %s reservations."
msgstr "Nelze vrátit zpět kvóty pro rezervace %s."

#, python-format
msgid ""
"Failed setting source volume %(source_volid)s back to its initial "
"%(source_status)s status"
msgstr ""
"Nelze nastavit zdrojový svazek %(source_volid)s zpět na původní stav "
"%(source_status)s "

#, python-format
msgid ""
"Failed to Roll back to re-add volume %(volumeName)s to default storage group "
"for fast policy %(fastPolicyName)s. Please contact your sysadmin to get the "
"volume returned to the default storage group."
msgstr ""
"Nelze se vrátit zpět do bodu znovu přidání svazku %(volumeName)s do výchozí "
"skupiny úložiště pro zásadu fast %(fastPolicyName)s. Prosím kontaktujte "
"svého správce systému, aby svazek vrátil zpět do výchozí skupiny úložiště."

#, python-format
msgid ""
"Failed to Roll back to re-add volume %(volumeName)s to default storage group "
"for fast policy %(fastPolicyName)s: Please contact your sys admin to get the "
"volume re-added manually."
msgstr ""
"Nelze se vrátit zpět do bodu znovu přidání svazku %(volumeName)s do výchozí "
"skupiny úložiště pro zásadu fast %(fastPolicyName)s: Prosím kontaktujte "
"svého správce systému, aby svazek přidal zpět ručně."

#, python-format
msgid ""
"Failed to add %(volumeName)s to default storage group for fast policy "
"%(fastPolicyName)s."
msgstr ""
"Nelze přidat %(volumeName)s do výchozí skupiny úložiště pro zásadu fast "
"%(fastPolicyName)s."

#, python-format
msgid "Failed to add %s to cg."
msgstr "Nelze odstranit %s ze skupiny jednotnosti."

#, python-format
msgid "Failed to add device to handler %s"
msgstr "Nelze přidat zařízení do obslužné rutiny %s"

#, python-format
msgid "Failed to add initiator iqn %s to target"
msgstr "Nelze přidat zavaděč iqn %s do cíle"

#, python-format
msgid "Failed to add initiator to group  for SCST target %s"
msgstr "Nelze přidat zavaděč do skupiny pro cíl SCST %s"

#, python-format
msgid "Failed to add lun to SCST target id:%(vol_id)s: %(e)s"
msgstr "Nelze přidat lun do cíle SCST s id: %(vol_id)s: %(e)s"

#, python-format
msgid "Failed to add multihost-access for volume \"%s\"."
msgstr "Nelze přidat přístup více hostitelů ke svazku \"%s\"."

#, python-format
msgid ""
"Failed to add storage group %(storageGroupInstanceName)s to tier policy rule "
"%(tierPolicyRuleInstanceName)s."
msgstr ""
"Nelze přidat skupinu úložiště %(storageGroupInstanceName)s do pravidla "
"zásady vrstvení %(tierPolicyRuleInstanceName)s."

#, python-format
msgid "Failed to add target(port: %s)"
msgstr "Nelze přidat cíl (port: %s)"

msgid "Failed to attach source volume for copy."
msgstr "Nelze připojit zdrojový svazek pro kopírování."

#, python-format
msgid "Failed to attach volume %(vol)s."
msgstr "Nelze připojit svazek %(vol)s."

msgid "Failed to authenticate user."
msgstr "Nelze ověřit uživatele."

#, python-format
msgid "Failed to check cluster status.(command: %s)"
msgstr "Nelze zkontrolovat stav clusteru. (příkaz: %s)"

#, python-format
msgid "Failed to clone image volume %(id)s."
msgstr "Klonování svazku obrazu %(id)s selhalo."

#, python-format
msgid "Failed to clone volume %(volume_id)s for image %(image_id)s."
msgstr "Nelze klonovat svazek %(volume_id)s pro obraz %(image_id)s."

#, python-format
msgid "Failed to clone volume.(command: %s)"
msgstr "Nelze klonovat svazek.(příkaz: %s)"

#, python-format
msgid "Failed to close disk device %s"
msgstr "Nelze uzavřít diskové zařízení %s"

#, python-format
msgid ""
"Failed to collect return properties for volume %(vol)s and connector "
"%(conn)s."
msgstr ""
"Shromáždění vlastností pro návrat svazku %(vol)s a konektoru %(conn)s "
"selhalo."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Nelze odevzdat rezervace %s"

#, python-format
msgid "Failed to copy %(src)s to %(dest)s."
msgstr "Nelze zkopírovat %(src)s do %(dest)s."

#, python-format
msgid "Failed to copy image %(image_id)s to volume: %(volume_id)s"
msgstr "Kopírování obrazu %(image_id)s do svazku %(volume_id)s selhalo"

#, python-format
msgid "Failed to copy image to volume: %(volume_id)s"
msgstr "Kopírování obrazu do svazku %(volume_id)s selhalo"

#, python-format
msgid "Failed to copy volume %(src)s to %(dest)s."
msgstr "Nelze zkopírovat svazek %(src)s do %(dest)s."

#, python-format
msgid "Failed to copy volume %(vol1)s to %(vol2)s"
msgstr "Nelze zkopírovat svazek %(vol1)s do %(vol2)s"

#, python-format
msgid "Failed to create %(conf)s for volume id:%(vol_id)s"
msgstr "Nelze vytvořit %(conf)s pro svazek s id: %(vol_id)s"

#, python-format
msgid "Failed to create CGSnapshot. Exception: %s."
msgstr "Nelze vytvořit snímek skupiny jednotnosti. Výjimka: %s."

msgid ""
"Failed to create SOAP client.Check san_ip, username, password and make sure "
"the array version is compatible"
msgstr ""
"Nelze vytvořit klienta SOAP. Zkontrolujte san_ip, uživatelské jméno, heslo a "
"ujistěte se, že verze pole je kompatibilní"

#, python-format
msgid ""
"Failed to create a first volume for storage group : %(storageGroupName)s."
msgstr ""
"Nelze vytvořit první svazek pro skupinu úložiště : %(storageGroupName)s."

#, python-format
msgid "Failed to create blkio cgroup '%(name)s'."
msgstr "Nelze vytvořit kontrolní skupinu vstupu/výstupu bloku '%(name)s'."

#, python-format
msgid "Failed to create clone of volume \"%s\"."
msgstr "Nelze vytvořit klon svazku \"%s\"."

#, python-format
msgid "Failed to create cloned volume %s."
msgstr "Nelze vytvořit klonovaný svazek %s."

#, python-format
msgid "Failed to create consistency group %(group_id)s."
msgstr "Nelze vytvořit skupinu jednotnosti %(group_id)s."

#, python-format
msgid ""
"Failed to create default storage group for FAST policy : %(fastPolicyName)s."
msgstr ""
"Nelze vytvořit výchozí skupinu úložiště pro zásadu FAST : %(fastPolicyName)s."

#, python-format
msgid "Failed to create group to SCST target %s"
msgstr "Nelze vytvořit skupinu pro cíl SCST %s"

#, python-format
msgid "Failed to create hardware id(s) on %(storageSystemName)s."
msgstr "Nelze vytvořit id hardwaru v %(storageSystemName)s."

#, python-format
msgid ""
"Failed to create iscsi target for Volume ID: %(vol_id)s. Please ensure your "
"tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""
"Nelze vytvořit cílové iscsi pro svazek s ID %(vol_id)s. Prosím ujistěte se, "
"že váš soubor s nastavením tgtd obsahuje 'include %(volumes_dir)s/*'"

#, python-format
msgid "Failed to create iscsi target for Volume ID: %(vol_id)s: %(e)s"
msgstr "Nelze vytvořit cílové iscsi pro svazek s ID %(vol_id)s: %(e)s"

#, python-format
msgid ""
"Failed to create iscsi target for volume id:%(vol_id)s. Please verify your "
"configuration in %(volumes_dir)s'"
msgstr ""
"Nelze vytvořit cílové iscsi pro svazek s id %(vol_id)s. Prosím ověřte své "
"nastavení v %(volumes_dir)s'"

#, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "Nelze vytvořit cílové iscsi pro svazek s id %(vol_id)s: %(e)s"

#, python-format
msgid "Failed to create iscsi target for volume id:%s"
msgstr "Nelze vytvořit cílové iscsi pro svazek s id: %s"

#, python-format
msgid "Failed to create iscsi target for volume id:%s."
msgstr "Nelze vytvořit cílové iscsi pro svazek s id: %s."

#, python-format
msgid "Failed to create manage_existing flow: %(object_type)s %(object_id)s."
msgstr ""
"Nelze vytvořit postup pro správu existujících: %(object_type)s %(object_id)s."

#, python-format
msgid "Failed to create snapshot of volume \"%s\"."
msgstr "Nelze vytvořit snímek svazku \"%s\"."

#, python-format
msgid "Failed to create snapshot. (command: %s)"
msgstr "Nelze vytvořit snímek. (příkaz: %s)"

#, python-format
msgid "Failed to create transfer record for %s"
msgstr "Nelze vytvořit záznam o přenosu pro %s"

#, python-format
msgid "Failed to create volume \"%s\"."
msgstr "Nelze vytvořit svazek \"%s\"."

#, python-format
msgid "Failed to create volume %s"
msgstr "Nelze vytvořit svazek %s"

#, python-format
msgid "Failed to create volume %s."
msgstr "Nelze vytvořit svazek %s."

#, python-format
msgid "Failed to create volume from snapshot \"%s\"."
msgstr "Nelze vytvořit svazek ze snímku \"%s\"."

#, python-format
msgid "Failed to create volume. %s"
msgstr "Nelze vytvořit svazek. %s"

#, python-format
msgid "Failed to create volume: %(name)s (%(status)s)"
msgstr "Nelze vytvořit svazek: %(name)s (%(status)s)"

#, python-format
msgid "Failed to created Cinder secure environment indicator file: %s"
msgstr "Nelze vytvořit soubor indikující bezpečné prostředí Cinder: %s"

#, python-format
msgid "Failed to delete initiator iqn %s from target."
msgstr "Nelze smazat zavaděč iqn %s z cíle."

#, python-format
msgid "Failed to delete snapshot %(snap)s of volume %(vol)s."
msgstr "Nelze smazat snímek %(snap)s svazku %(vol)s."

#, python-format
msgid "Failed to delete snapshot. (command: %s)"
msgstr "Nelze smazat snímek. (příkaz: %s)"

#, python-format
msgid ""
"Failed to delete the snapshot %(snap)s of CGSnapshot. Exception: "
"%(exception)s."
msgstr ""
"Nelze smazat snímek %(snap)s ze snímku skupiny jednotnosti. Výjimka: "
"%(exception)s."

#, python-format
msgid "Failed to delete the volume %(vol)s of CG. Exception: %(exception)s."
msgstr ""
"Nelze smazat svazek %(vol)s skupiny jednotnosti. Výjimka: %(exception)s."

#, python-format
msgid "Failed to delete volume \"%s\"."
msgstr "Nelze smazat svazek \"%s\"."

#, python-format
msgid "Failed to delete volume %s"
msgstr "Nelze smazat svazek %s"

#, python-format
msgid "Failed to delete volume. %s"
msgstr "Nelze smazat svazek. %s"

#, python-format
msgid "Failed to ensure export of volume \"%s\"."
msgstr "Nelze zajistit export svazku \"%s\"."

#, python-format
msgid "Failed to ensure export of volume %s"
msgstr "Nelze zajistit export svazku %s"

#, python-format
msgid "Failed to export fiber channel target due to %s"
msgstr "Nelze exportovat cíl fiber channel z důvodu %s"

#, python-format
msgid "Failed to extend volume: %(vol)s to size: %(size)s GB."
msgstr "Nelze rozšířit svazek: %(vol)s na velikost %(size)s GB."

#, python-format
msgid ""
"Failed to extend_volume %(name)s from %(current_size)sGB to %(new_size)sGB."
msgstr "Nelze rozšířit svazek %(name)s z %(current_size)sGB na %(new_size)sGB."

#, python-format
msgid "Failed to find %(s)s.  Result %(r)s"
msgstr "Nelze najít %(s)s. Výsledek %(r)s"

msgid "Failed to get IQN!"
msgstr "Nelze získat IQN!"

msgid "Failed to get LUN information!"
msgstr "Nelze získat informace o LUN!"

#, python-format
msgid "Failed to get allocation information (%d)!"
msgstr "Získání informací o přidělení (%d) selhalo!"

#, python-format
msgid "Failed to get allocation information: %(host)s (%(status)d)!"
msgstr "Nelze získat informace o přidělení: %(host)s (%(status)d)!"

#, python-format
msgid "Failed to get device number for throttling: %(error)s"
msgstr "Nelze získat číslo zařízení pro škrcení: %(error)s"

#, python-format
msgid ""
"Failed to get driver initiator data for initiator %(initiator)s and "
"namespace %(namespace)s"
msgstr ""
"Nelze získat data zavedení ovladače pro zavaděč %(initiator)s a jmenný "
"prostor %(namespace)s"

#, python-format
msgid "Failed to get fiber channel info from storage due to %(stat)s"
msgstr "Nelze získat informace o fiber channel z úložiště kvůli %(stat)s"

#, python-format
msgid "Failed to get fiber channel target from storage server due to %(stat)s"
msgstr "Nelze získat cíl fiber channel ze serverového úložiště kvůli %(stat)s"

#, python-format
msgid "Failed to get or create storage group %(storageGroupName)s."
msgstr "Nelze získat nebo vytvořit skupinu úložiště %(storageGroupName)s."

#, python-format
msgid "Failed to get response: %s."
msgstr "Nelze získat odpověď: %s."

#, python-format
msgid "Failed to get server info due to %(state)s."
msgstr "Nelze získat informace o disku z důvodu %(state)s."

msgid "Failed to get sns table"
msgstr "Nelze získat tabulku sns"

#, python-format
msgid "Failed to get target wwpns from storage due to %(stat)s"
msgstr "Nelze získat cílov= wwpns z úložiště kvůli %(stat)s"

msgid "Failed to get updated stats from Datera Cluster."
msgstr "Nelze získat aktualizované statistiky z clusteru Datera."

msgid "Failed to get updated stats from Datera cluster."
msgstr "Nelze získat aktualizované statistiky z clusteru Datera."

#, python-format
msgid "Failed to get volume status. %s"
msgstr "Nelze získat stav svazku. %s"

msgid "Failed to initialize connection"
msgstr "Nelze zavést připojení"

#, python-format
msgid "Failed to initialize connection to volume \"%s\"."
msgstr "Nelze zavést připojení ke svazku \"%s\"."

msgid "Failed to initialize connection."
msgstr "Nelze zavést připojení."

msgid "Failed to initialize driver."
msgstr "Nelze zavést ovladač."

#, python-format
msgid "Failed to issue df command for path %(path)s, error: %(error)s."
msgstr "Nelze zadat příkaz df pro cestu %(path)s, chyba: %(error)s."

#, python-format
msgid "Failed to issue mmgetstate command, error: %s."
msgstr "Nelze zadat příkaz mmgetstate, chyba: %s."

#, python-format
msgid "Failed to issue mmlsattr command for path %(path)s, error: %(error)s."
msgstr "Nelze zadat příkaz mmlsattr pro cestu %(path)s, chyba: %(error)s"

#, python-format
msgid "Failed to issue mmlsattr command on path %(path)s, error: %(error)s"
msgstr "Nelze zadat příkaz mmlsattr v cestě %(path)s, chyba: %(error)s"

#, python-format
msgid "Failed to issue mmlsconfig command, error: %s."
msgstr "Nelze zadat příkaz mmtsconfig, chyba: %s."

#, python-format
msgid "Failed to issue mmlsfs command for path %(path)s, error: %(error)s."
msgstr "Nelze zadat příkaz mmlsfs pro cestu %(path)s, chyba: %(error)s."

#, python-format
msgid "Failed to issue mmlsfs command, error: %s."
msgstr "Nelze zadat příkaz mmlsfs, chyba: %s."

#, python-format
msgid "Failed to load %s"
msgstr "Nelze načíst %s"

msgid "Failed to load osapi_volume"
msgstr "Nelze načíst svazek osapi"

#, python-format
msgid "Failed to open iet session list for %s"
msgstr "Nelze otevřít seznam sezení iet pro %s"

#, python-format
msgid "Failed to open volume from %(path)s."
msgstr "Nelze otevřít svazek z %(path)s."

#, python-format
msgid "Failed to present volume %(name)s (%(status)d)!"
msgstr "Nelze darovat svazek %(name)s (%(status)d)!"

msgid "Failed to re-export volume, setting to ERROR."
msgstr "Nelze znovu exportovat svazek, je nastavován na ERROR."

#, python-format
msgid "Failed to register image volume location %(uri)s."
msgstr "Nelze registrovat umístění svazku obrazu %(uri)s."

#, python-format
msgid ""
"Failed to remove %(volumeName)s from the default storage group for the FAST "
"Policy."
msgstr ""
"Nelze odstranit %(volumeName)s z výchozí skupiny úložiště pro zásadu FAST."

#, python-format
msgid "Failed to remove %s from cg."
msgstr "Nelze odstranit %s ze skupiny jednotnosti."

#, python-format
msgid "Failed to remove LUN %s"
msgstr "Nelze odstranit LUN %s"

#, python-format
msgid "Failed to remove iscsi target for Volume ID: %(vol_id)s: %(e)s"
msgstr "Nelze odstranit cílové iscsi pro svazek s ID: %(vol_id)s: %(e)s"

#, python-format
msgid "Failed to remove iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "Nelze odstranit cílové iscsi pro svazek s id %(vol_id)s: %(e)s"

#, python-format
msgid "Failed to remove iscsi target for volume id:%s"
msgstr "Nelze odstranit cílové iscsi pro svazek s id: %s"

#, python-format
msgid "Failed to remove iscsi target for volume id:%s."
msgstr "Nelze odstranit cílové iscsi pro svazek s id: %s."

#, python-format
msgid "Failed to rename %(new_volume)s into %(volume)s."
msgstr "Nelze přejmenovat %(new_volume)s na %(volume)s."

msgid "Failed to rename the created snapshot, reverting."
msgstr "Nelze přejmenovat vytvořený snímek, probíhá vrácení zpět."

#, python-format
msgid "Failed to request async delete of migration source vol %(vol)s: %(err)s"
msgstr ""
"Nelze zažádat o asynchronní smazání zdrojového svazku přesunu %(vol)s: "
"%(err)s"

#, python-format
msgid ""
"Failed to resize vdi. Shrinking vdi not supported. vdi: %(vdiname)s new "
"size: %(size)s"
msgstr ""
"Nelze změnit velikost vdi. Zmenšování vdi není podporováno. VDI: "
"%(vdiname)s, nová velikost: %(size)s"

#, python-format
msgid ""
"Failed to resize vdi. Too large volume size. vdi: %(vdiname)s new size: "
"%(size)s"
msgstr ""
"Nelze změnit velikost vdi. Velikost je příliš velká. VDI: %(vdiname)s, nová "
"velikost: %(size)s"

#, python-format
msgid "Failed to resize vdi. vdi not found. %s"
msgstr "Nelze změnit velikost vdi, vdi nenalezeno. %s"

#, python-format
msgid "Failed to resize vdi. vdi: %(vdiname)s new size: %(size)s"
msgstr "Nelze změnit velikost vdi. VDI: %(vdiname)s, nová velikost: %(size)s"

#, python-format
msgid "Failed to resize volume %(volume_id)s, error: %(error)s."
msgstr "Nelze změnit velikost svazku %(volume_id)s, chyba: %(error)s."

#, python-format
msgid "Failed to retrieve volume SolidFire-ID: %s in get_by_account!"
msgstr "Nelze získat svazek SolidFire s ID: %s v získání podle účtu!"

#, python-format
msgid ""
"Failed to return volume %(volumeName)s to original storage pool. Please "
"contact your system administrator to return it to the correct location."
msgstr ""
"Nelze vrátit svazek %(volumeName)s do původní zásoby úložiště. Prosím "
"kontaktujte svého správce systému, aby ho vrátil na správné místo."

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Nelze vrátit zpět rezervace %s"

#, python-format
msgid "Failed to run task %(name)s: %(cause)s"
msgstr "Nelze spustit úkol %(name)s: %(cause)s"

#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr "Nelze naplánovat %(method)s: %(ex)s"

#, python-format
msgid "Failed to send request: %s."
msgstr "Nelze odeslat požadavek: %s."

#, python-format
msgid "Failed to set 'enable' attribute for SCST target %s"
msgstr "Nelze nastavit vlastnost 'enable' pro cíl SCST %s"

#, python-format
msgid "Failed to set attribute for enable target driver %s"
msgstr "Nelze nastavit vlastnost pro povolení cílového ovladače %s"

msgid "Failed to setup the Dell EqualLogic driver."
msgstr "Nastavení ovladače Dell EqualLogic selhalo."

msgid "Failed to shutdown horcm."
msgstr "Ukončování horcm selhalo."

#, python-format
msgid "Failed to snap Consistency Group %s"
msgstr "Nelze vytvořit snímek skupiny jednotnosti %s"

msgid "Failed to start horcm."
msgstr "Spouštění horcm selhalo."

msgid "Failed to terminate connection"
msgstr "Nelze ukončit připojení"

#, python-format
msgid "Failed to terminate connection %(initiator)s %(vol)s"
msgstr "Nelze ukončit připojení %(initiator)s %(vol)s"

#, python-format
msgid "Failed to terminate connection to volume \"%s\"."
msgstr "Nelze ukončit připojení ke svazku \"%s\"."

#, python-format
msgid "Failed to umount %(share)s, reason=%(stderr)s"
msgstr "Nelze odpojit %(share)s, důvod: %(stderr)s"

#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id)s after removing iscsi "
"target"
msgstr ""
"Nelze aktualizovat %(conf)s pro svazek s id %(vol_id)s po odstranění cíle "
"iscsi"

#, python-format
msgid "Failed to update %(conf)s for volume id:%(vol_id)s"
msgstr "Nelze aktualizovat %(conf)s pro svazek s id: %(vol_id)s"

#, python-format
msgid ""
"Failed to update %(volume_id)s metadata using the provided snapshot "
"%(snapshot_id)s metadata."
msgstr ""
"Nelze aktualizovat popisná data %(volume_id)s pomocí popisných dat zadaného "
"snímku %(snapshot_id)s."

#, python-format
msgid "Failed to update quota donating volume transfer id %s"
msgstr "Nelze aktualizovat id přenosu svazku dodávajícího kvótu %s."

#, python-format
msgid "Failed to update quota for consistency group %s."
msgstr "Nelze aktualizovat kvótu skupiny jednotnosti %s."

#, python-format
msgid "Failed to update quota for deleting volume: %s"
msgstr "Nelze aktualizovat kvóty kvůli smazání svazku: %s"

#, python-format
msgid "Failed to update quota while deleting snapshots: %s"
msgstr "Nelze aktualizovat kvóty při mazání snímků: %s"

msgid "Failed to update quota while deleting volume."
msgstr "Nelze aktualizovat kvóty při mazání svazku."

msgid "Failed to update usages deleting backup"
msgstr "Nelze aktualizovat využití při mazání zálohy"

msgid "Failed to update usages deleting snapshot"
msgstr "Nelze aktualizovat využití při mazání snímku."

msgid "Failed to update usages deleting volume."
msgstr "Nelze aktualizovat využití při mazání svazku."

#, python-format
msgid "Failed to update volume status: %s"
msgstr "Nelze aktualizovat stav svazku: %s"

#, python-format
msgid ""
"Failed to verify that volume was added to storage group for FAST policy: "
"%(fastPolicyName)s."
msgstr ""
"Nelze ověřit zda svazek byl přidán do skupiny úložiště pro zásadu FAST: "
"%(fastPolicyName)s."

msgid "Failed to write in /etc/scst.conf."
msgstr "Nelze zapisovat do/etc/scst.conf."

#, python-format
msgid "Failed to write persistence file: %(path)s."
msgstr "Nelze zapsat soubor přetrvání: %(path)s."

#, python-format
msgid ""
"Failed updating %(snapshot_id)s metadata using the provided volumes "
"%(volume_id)s metadata"
msgstr ""
"Nelze aktualizovat popisná data %(snapshot_id)s pomocí popisných dat "
"zadaného svazku %(volume_id)s"

#, python-format
msgid ""
"Failed updating model of snapshot %(snapshot_id)s with creation provided "
"model %(model)s."
msgstr ""
"Nelze aktualizovat model snímku %(snapshot_id)s pomocí modelu %(model)s "
"poskytnutého při vytváření."

#, python-format
msgid ""
"Failed updating model of snapshot %(snapshot_id)s with driver provided model "
"%(model)s."
msgstr ""
"Nelze aktualizovat model snímku %(snapshot_id)s pomocí ovladače poskytnutého "
"modelem %(model)s."

#, python-format
msgid ""
"Failed updating model of volume %(volume_id)s with creation provided model "
"%(model)s"
msgstr ""
"Nelze aktualizovat model svazku %(volume_id)s pomocí modelu %(model)s "
"poskytnutého při vytváření"

#, python-format
msgid ""
"Failed updating model of volume %(volume_id)s with driver provided model "
"%(model)s"
msgstr ""
"Nelze aktualizovat model svazku %(volume_id)s pomocí ovladače poskytnutého "
"modelem %(model)s"

#, python-format
msgid "Failed updating snapshot %(snapshot_id)s with %(update)s."
msgstr "Aktualizace snímku %(snapshot_id)s pomocí %(update)s selhala."

#, python-format
msgid ""
"Failed updating snapshot metadata using the provided volumes %(volume_id)s "
"metadata"
msgstr ""
"Nelze aktualizovat popisná data snímku pomocí popisných dat zadaného svazku "
"%(volume_id)s"

#, python-format
msgid "Failed updating volume %(volume_id)s bootable flag to true"
msgstr ""
"Aktualizace příznaku zaveditelnosti svazku %(volume_id)s na true selhala"

#, python-format
msgid "Failed updating volume %(volume_id)s with %(update)s"
msgstr "Aktualizace svazku %(volume_id)s pomocí %(update)s selhala"

#, python-format
msgid "Failed updating volume %(volume_id)s with %(updates)s"
msgstr "Aktualizace svazku %(volume_id)s pomocí %(updates)s selhala"

#, python-format
msgid "Failure deleting staged tmp LUN %s."
msgstr "Smazání zařazeného dočasného LUN %s selhalo."

msgid "Fetch volume pool name failed."
msgstr "Získání názvu zásoby svazku selhalo."

#, python-format
msgid ""
"FibreChannelDriver validate_connector failed. No '%(setting)s'. Make sure "
"HBA state is Online."
msgstr ""
"Ověření konektoru ovladačem Fibre Channel selhalo. '%(setting)s' nenalezeno. "
"Ujistěte se, že stav HBA je Online."

#, python-format
msgid "Flexvisor failed to get event %(volume)s (%(status)s)."
msgstr "Flexvisor nemohl získat událost %(volume)s (%(status)s)."

#, python-format
msgid "Flexvisor failed to get pool %(id)s info."
msgstr "Flexvisor nemohl získat informace o zásobě %(id)s."

#, python-format
msgid "Flexvisor failed to get pool list due to %s."
msgstr "Flexvisor nemohl získat seznam zásob z důvodu %s."

#, python-format
msgid "Flexvisor failed to get pool list.(Error: %d)"
msgstr "Flexvisor nemohl získat seznam zásob. (Chyba: %d)"

#, python-format
msgid "Found %(count)s volumes mapped to id: %(uuid)s."
msgstr "Nalezeno %(count)s svazků mapovaných k id: %(uuid)s."

msgid "Free capacity not set: volume node info collection broken."
msgstr ""
"Volná kapacita není nastavena: Shromažďování informací o uzlech svazku je "
"nefunkční."

#, python-format
msgid "GPFS is not active.  Detailed output: %s."
msgstr "GPFS není aktivní. Podrobný výstup: %s."

msgid "Get LUN migration error."
msgstr "Chyba při získávání přesunu LUN."

msgid "Get method error."
msgstr "Chyba získávání metody."

msgid "Get replication status for volume failed."
msgstr "Získání stavu replikace svazku selhalo."

#, python-format
msgid "Host PUT failed (%s)."
msgstr "PUT hostitele selhal (%s)."

msgid "Host could not be found!"
msgstr "Hostitel nemohl být nalezen!"

#, python-format
msgid "ISCSI discovery attempt failed for:%s"
msgstr "Pokus o zjištění ISCSI selhal pro: %s"

msgid "ISE FW version is not compatible with OpenStack!"
msgstr "Verze ISE FW není kompatibilní s OpenStack!"

msgid "ISE globalid not set!"
msgstr "ISE globalid není nastaveno!"

#, python-format
msgid "Image size %(img_size)dGB is larger than volume size %(vol_size)dGB."
msgstr ""
"Velikost obrazu %(img_size)dGB je větší než velikost svazku %(vol_size)dGB."

#, python-format
msgid "Invalid API object: %s"
msgstr "Neplatný objekt API: %s"

#, python-format
msgid "Invalid JSON: %s"
msgstr "Neplatný JSON: %s"

#, python-format
msgid "Invalid ReplayList return: %s"
msgstr "Neplatné předání seznamu zpětného načtení: %s"

#, python-format
msgid "Invalid hostname %(host)s"
msgstr "Neplatný název hostitele %(host)s"

msgid ""
"Issuing a fail-over failed because replication is not properly configured."
msgstr ""
"Vyvolání zavedení záložního systému, protože replikace není správně "
"nastavena."

#, python-format
msgid "JSON encode params %(param)s error: %(status)s."
msgstr "Chyba parametrů kódování JSON %(param)s: %(status)s."

#, python-format
msgid "JSON transfer data error. %s."
msgstr "Chyba přesunu dat JSON: %s"

#, python-format
msgid "JSON transfer error: %s."
msgstr "Chyba přesunu JSON: %s."

#, python-format
msgid "LUN %(path)s geometry failed. Message - %(msg)s"
msgstr "Geometrie LUN %(path)s selhala. Zpráva - %(msg)s"

msgid "LUN extend failed!"
msgstr "Rozšíření LUN selhalo!"

msgid "LUN unexport failed!"
msgstr "Zrušení exportu LUN selhalo!"

#, python-format
msgid ""
"Location info needed for backend enabled volume migration not in correct "
"format: %s. Continuing with generic volume migration."
msgstr ""
"Informace o umístění potřebné pro přesun svazku za pomocí podpůrné vrstvy "
"nejsou ve správném formátu: %s. Bude použita obecná metoda přesunutí svazku."

#, python-format
msgid "Looks like masking view: %(maskingViewName)s has recently been deleted."
msgstr "Zdá se, že zamaskování: %(maskingViewName)s bylo nedávno smazáno."

#, python-format
msgid "Lun %s has dependent snapshots, skipping lun deletion."
msgstr "Lun %s má na sobě závislé snímky, smazání lun přeskočeno."

#, python-format
msgid "Lun create for %s failed!"
msgstr "Vytvoření LUN pro %s selhalo!"

#, python-format
msgid "Lun create snapshot for volume %(vol)s snapshot %(snap)s failed!"
msgstr "Vytvoření snímku Lun pro svazek %(vol)s a snímek %(snap)s selhalo!"

#, python-format
msgid "Lun delete for %s failed!"
msgstr "Smazání Lun pro %s selhalo!"

msgid "Lun mapping returned null!"
msgstr "Mapování Lun vrátilo prázdný obsah!"

#, python-format
msgid "MSGID%(id)04d-E: %(msg)s"
msgstr "MSGID%(id)04d-E: %(msg)s"

#, python-format
msgid ""
"Manager for service %(binary)s %(host)s is reporting problems, not sending "
"heartbeat. Service will appear \"down\"."
msgstr ""
"Správce služby %(binary)s %(host)s hlásí problémy, neodesílá informace o "
"aktivitě. Služba bude vypadat \"mimo provoz\"."

#, python-format
msgid ""
"Masking View creation or retrieval was not successful for masking view "
"%(maskingViewName)s. Attempting rollback."
msgstr ""
"Vytvoření nebo získání zamaskování nebylo úspěšné u %(maskingViewName)s. "
"Pokus o zpětné vrácení."

#, python-format
msgid ""
"Max retries reached deleting backup %(basename)s image of volume %(volume)s."
msgstr ""
"Při mazání zálohy obrazu %(basename)s svazku %(volume)s bylo dosaženo "
"maximálního množství pokusů."

#, python-format
msgid "Message: %s"
msgstr "Zpráva: %s"

msgid "Model update failed."
msgstr "Aktualizace modelu selhala."

#, python-format
msgid "Modify volume PUT failed: %(name)s (%(status)d)."
msgstr "Změna PUT svazku selhala: %(name)s (%(status)d)."

#, python-format
msgid "Mount failure for %(share)s after %(count)d attempts."
msgstr "Selhání připojení k %(share)s po %(count)d pokusech."

#, python-format
msgid "Mount failure for %(share)s."
msgstr "Selhání připojení pro %(share)s."

#, python-format
msgid "Multiple replay profiles under name %s"
msgstr "Nalezeno mnoho profilů rychlého načtení s názvem %s."

msgid "No CLI output for firmware version check"
msgstr ""
"U kontroly verzi firmware nebyl žádný výstup v rozhraní příkazového řádku"

#, python-format
msgid "No VIP configured for service %s"
msgstr "Nenastaveno žádné VIP pro službu %s"

#, python-format
msgid ""
"No action required. Volume: %(volumeName)s is already part of pool: %(pool)s."
msgstr ""
"Není vyžadována žádná činnost. Svazek: %(volumeName)s již je součástí "
"zásoby: %(pool)s."

#, python-format
msgid ""
"No action required. Volume: %(volumeName)s is already part of slo/workload "
"combination: %(targetCombination)s."
msgstr ""
"Není vyžadována žádná činnost. Svazek: %(volumeName)s již je součástí "
"kombinace slo/vytížení: %(targetCombination)s."

#, python-format
msgid ""
"No snapshots found in database, but %(path)s has backing file "
"%(backing_file)s!"
msgstr ""
"V databázi nebyly nalezeny žádné snímky, ale %(path)s má záložní soubor "
"%(backing_file)s!"

#, python-format
msgid "Not able to configure PBM for vCenter server: %s"
msgstr "Nelze nastavit PBM pro server vCenter: %s"

#, python-format
msgid "OSError: command is %(cmd)s."
msgstr "Chyba OS: příkaz je %(cmd)s."

#, python-format
msgid "OSError: command is %s."
msgstr "Chyba OS: příkaz je %s."

#, python-format
msgid ""
"One of the components of the original masking view %(maskingViewName)s "
"cannot be retrieved so please contact your system administrator to check "
"that the correct initiator(s) are part of masking."
msgstr ""
"Jedna ze součástí původního zamaskování %(maskingViewName)s nemůže být "
"získána. Prosím kontaktujte svého správce systému, aby zkontroloval, že "
"správné zavaděče jsou součástí zamaskování."

#, python-format
msgid ""
"Only SLO/workload migration within the same SRP Pool is supported in this "
"version The source pool : %(sourcePoolName)s does not match the target "
"array: %(targetPoolName)s. Skipping storage-assisted migration."
msgstr ""
"V této verzi je přesun SLO/vytížení podporován pouze v rámci stejné zásoby "
"SRP. Zdrojová zásoba : %(sourcePoolName)s se neshoduje s cílovým polem: "
"%(targetPoolName)s. Přesun za pomocí úložiště bude přeskočen."

msgid "Only available volumes can be migrated between different protocols."
msgstr "Mezi různými protokoly lze přesunovat pouze dostupné svazky."

#, python-format
msgid "POST for host create failed (%s)!"
msgstr "POST pro vytvoření hostitele selhalo (%s)!"

#, python-format
msgid "Pipe1 failed - %s "
msgstr "Roura1 selhala - %s"

#, python-format
msgid "Pipe2 failed - %s "
msgstr "Roura2 selhala - %s"

msgid ""
"Please check your xml for format or syntax errors. Please see documentation "
"for more details."
msgstr ""
"Prosím zkontrolujte váš xml soubor, zda v něm nejsou chyby ve formátu, či "
"syntaxi. Pro další informace si přečtěte dokumentaci."

#, python-format
msgid "PoolName must be in the file %(fileName)s."
msgstr "Název zásoby musí být v souboru %(fileName)s."

#, python-format
msgid "Prepare clone failed for %s."
msgstr "Příprava klonu selhala pro %s."

msgid "Primary IP must be set!"
msgstr "Hlavní IP musí být nastavena!"

msgid "Problem cleaning incomplete backup operations."
msgstr "Při čištění nedokončených záložních operací se vyskytl problém."

#, python-format
msgid "Problem cleaning temp volumes and snapshots for backup %(bkup)s."
msgstr ""
"Při čištění dočasných svazků a snímků zálohy %(bkup)s  se vyskytl problém."

#, python-format
msgid "Problem cleaning up backup %(bkup)s."
msgstr "Při čištění zálohy %(bkup)s se vyskytl problém."

msgid "Promote volume replica failed."
msgstr "Povýšení repliky svazku selhalo."

#, python-format
msgid ""
"Purity host %(host_name)s is managed by Cinder but CHAP credentials could "
"not be retrieved from the Cinder database."
msgstr ""
"Cinder spravuje hostitele Purity %(host_name)s, ale přihlašovací údaje CHAP "
"nemohly být získány z databáze Cinder."

#, python-format
msgid ""
"Purity host %(host_name)s is not managed by Cinder and can't have CHAP "
"credentials modified. Remove IQN %(iqn)s from the host to resolve this issue."
msgstr ""
"Cinder nespravuje hostitele Purity %(host_name)s a proto nelze měnit jeho "
"přihlašovací údaje CHAP. Pro vyřešení problému odstraňte IQN %(iqn)s z "
"hostitele."

#, python-format
msgid "Qemu-img is not installed. OSError: command is %(cmd)s."
msgstr "Qemu-img není nainstalováno. Chyba OS: příkaz je %(cmd)s."

#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""
"U %(s_pid)s překročena kvóta, pokus o rozšíření svazku o %(s_size)sG, (již "
"využíváno (%(d_consumed)dG z %(d_quota)dG)."

#, python-format
msgid "REST Not Available: %s"
msgstr "REST není dostupné: %s"

#, python-format
msgid "Re-throwing Exception %s"
msgstr "Znovu vyvolávání výjimky %s"

#, python-format
msgid "Read response raised an exception: %s."
msgstr "Čtení odpovědi vyvolalo výjimku: %s."

msgid "Recovered model server connection!"
msgstr "Obnoveno připojení modelového serveru!"

#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr "Obnovování ze selhaného spuštění. Pokus číslo %s"

msgid "Replication must be specified as '<is> True' or '<is> False'."
msgstr "Replikace musí být zadána jako '<is> True' nebo '<is> False'."

msgid ""
"Requested to setup thin provisioning, however current LVM version does not "
"support it."
msgstr ""
"Žádost o nastavení mělkého poskytování, ale současná verze LVM ho "
"nepodporuje."

#, python-format
msgid "Resizing %s failed. Cleaning volume."
msgstr "Změna velikosti %s selhala. Probíhá čištění svazku."

#, python-format
msgid "Restore to volume %(volume)s finished with error - %(error)s."
msgstr "Obnovení svazku %(volume)s bylo dokončeno s chybou - %(error)s."

#, python-format
msgid "Retry %(retry)s times: %(method)s Failed %(rc)s: %(reason)s"
msgstr "Pokus proveden %(retry)skrát: %(method)s selhala %(rc)s: %(reason)s"

msgid "Retype volume error."
msgstr "Chyba přetypování svazku."

#, python-format
msgid ""
"SLO: %(slo)s is not valid. Valid values are Bronze, Silver, Gold, Platinum, "
"Diamond, Optimized, NONE."
msgstr ""
"SLO: %(slo)s není platné. Platné hodnoty jsou Bronze, Silver, Gold, "
"Platinum, Diamond, Optimized, NONE."

msgid ""
"ScVolume returned success with empty payload.  Attempting to locate volume"
msgstr ""
"SCVolume předal zprávu o úspěchu s prázdným obsahem. Pokus o nalezení svazku"

#, python-format
msgid "Server Busy retry request: %s"
msgstr "Server zaneprázdněn, žádost o opakování: %s"

#, python-format
msgid "Setting QoS for %s failed"
msgstr "Nastavení QoS pro %s selhalo"

#, python-format
msgid ""
"Share %s ignored due to invalid format. Must be of form address:/export."
msgstr ""
"Sdílení %s ignorováno kvůli neplatnému formátu. Musí být ve formátu adresa:/"
"export."

#, python-format
msgid "Sheepdog is not installed. OSError: command is %s."
msgstr "Sheepdog není nainstalován. Chyba OS: příkaz je %s."

#, python-format
msgid ""
"Skipping remove_export. No iscsi_target ispresently exported for volume: %s"
msgstr ""
"Odstranění exportu přeskočeno. Žádný cíl iscsi není v současnosti exportován "
"pro svazek: %s"

#, python-format
msgid "Snapshot \"%s\" already exists."
msgstr "Snímek \"%s\" již existuje."

#, python-format
msgid ""
"Snapshot \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"Snímek \"%s\" nenalezen. Prosím zkontrolujte výstup příkazu \"dog vdi list\"."

#, python-format
msgid "Snapshot %s: create failed"
msgstr "Vytvoření snímku %s selhalo"

#, python-format
msgid "Snapshot %s: has clones"
msgstr "Snímek %s má klony"

msgid "Snapshot did not exist. It will not be deleted"
msgstr "Snímek neexistuje. Nebude smazán"

#, python-format
msgid ""
"Source CG %(source_cg)s not found when creating consistency group %(cg)s "
"from source."
msgstr ""
"Při vytváření skupiny %(cg)s ze zdroje nebyla nalezena zdrojová skupina "
"jednotnosti %(source_cg)s."

#, python-format
msgid "Source snapshot %(snapshot_id)s cannot be found."
msgstr "Zdrojový snímek %(snapshot_id)s nelze nalézt."

#, python-format
msgid "Source snapshot cannot be found for target volume %(volume_id)s."
msgstr "Zdrojový snímek pro cílový svazek %(volume_id)s nenalezen."

#, python-format
msgid "Source volume %s not ready!"
msgstr "Zdrojový svazek %s není připraven!"

#, python-format
msgid "Source volumes cannot be found for target volume %(volume_id)s."
msgstr "Zdrojové svazky pro cílový svazek %(volume_id)s nenalezeny. "

#, python-format
msgid ""
"Src Volume \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"Zdrojový svazek \"%s\" nenalezen. Prosím zkontrolujte výstup příkazu \"dog "
"vdi list\"."

#, python-format
msgid "StdErr  :%s"
msgstr "Chybový výstup  :%s"

#, python-format
msgid "StdOut  :%s"
msgstr "Standardní výstup  :%s"

#, python-format
msgid "Storage Profile %s was not found."
msgstr "Profil úložiště %s nebyl nalezen."

#, python-format
msgid "Storage profile: %s cannot be found in vCenter."
msgstr "Profil úložiště: %s nenalezen ve vCenter."

msgid "Sync volume replica failed."
msgstr "Synchronizace repliky svazku selhala."

#, python-format
msgid "TSM [%s] not found in CloudByte storage."
msgstr "TSM [%s] nenalezeno v úložišti CloudByte."

msgid "The Flexvisor service is unavailable."
msgstr "Služba Flexvisor je nedostupná."

#, python-format
msgid "The NFS Volume %(cr)s does not exist."
msgstr "Svazek NFS %(cr)s neexistuje."

msgid "The connector does not contain the required information."
msgstr "Konektor neobsahuje požadované informace."

msgid ""
"The connector does not contain the required information: initiator is missing"
msgstr "Konektor neobsahuje požadované informace: zavaděč chybí"

msgid ""
"The connector does not contain the required information: wwpns is missing"
msgstr "Konektor neobsahuje požadované informace: wwpns chybí"

msgid "The snapshot cannot be deleted because it is a clone point."
msgstr "Snímek nemůže být smazán protože je to bod klonování."

#, python-format
msgid ""
"The source array : %(sourceArraySerialNumber)s does not match the target "
"array: %(targetArraySerialNumber)s skipping storage-assisted migration."
msgstr ""
"Zdrojové pole : %(sourceArraySerialNumber)s se neshoduje cílovému poli: "
"%(targetArraySerialNumber)s, přesun za pomocí úložiště bude přeskočen."

#, python-format
msgid ""
"The source array : %(sourceArraySerialNumber)s does not match the target "
"array: %(targetArraySerialNumber)s, skipping storage-assisted migration."
msgstr ""
"Zdrojové pole : %(sourceArraySerialNumber)s se neshoduje cílovému poli: "
"%(targetArraySerialNumber)s, přesun za pomocí úložiště bude přeskočen."

#, python-format
msgid "The source volume %(volume_id)s cannot be found."
msgstr "Zdrojový svazek %(volume_id)s nelze nalézt."

#, python-format
msgid "The volume driver requires %(data)s in the connector."
msgstr "Ovladač svazku vyžaduje %(data)s v konektoru."

msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr "Ovladač svazku vyžaduje název zavaděče iSCSI v konektoru."

#, python-format
msgid "There are no valid hosts available in configured cluster(s): %s."
msgstr "V nastaveném clusteru nejsou dostupní žádní platní hostitele: %s."

#, python-format
msgid "There is no valid datastore satisfying requirements: %s."
msgstr "Žádné platné datové úložiště splňující požadavky: %s."

msgid "There must be at least one valid replication device configured."
msgstr "Musí být zadáno alespoň jedno platné replikační zařízení."

msgid "This usually means the volume was never successfully created."
msgstr "To většinou znamená, že svazek nikdy nebyl úspěšně vytvořen."

msgid "Tiering Policy is not supported on this array."
msgstr "Zásada vrstvení není podporována na tomto poli."

#, python-format
msgid "Timed out deleting %s!"
msgstr "Při mazání %s vypršel časový limit!"

#, python-format
msgid "Trying to create snapshot by non-existent LV: %s"
msgstr "Pokus o vytvoření svazku z neexistujícího logického svazku. %s"

#, python-format
msgid "URLError: %s"
msgstr "Chyba URL: %s"

#, python-format
msgid "Unable to create folder path %s"
msgstr "Nelze vytvořit cestu složky %s"

#, python-format
msgid ""
"Unable to create or get default storage group for FAST policy: "
"%(fastPolicyName)s."
msgstr ""
"Nelze vytvořit nebo získat výchozí skupinu úložiště pro zásadu FAST: "
"%(fastPolicyName)s."

#, python-format
msgid "Unable to create volume %s from replay"
msgstr "Nelze vytvořit svazek %s ze zpětného načtení"

#, python-format
msgid "Unable to create volume. Volume driver %s not initialized"
msgstr "Nelze vytvořit svazek. Ovladač svazku %s není zaveden"

msgid "Unable to delete busy volume."
msgstr "Nelze smazat zaneprázdněný svazek."

#, python-format
msgid "Unable to delete due to existing snapshot for volume: %s"
msgstr "Nelze smazat kvůli existujícímu snímku svazku. %s"

msgid ""
"Unable to delete the destination volume during volume migration, (NOTE: "
"database record needs to be deleted)."
msgstr ""
"Nelze smazat cílový svazek během přesunování, (POZNÁMKA: záznam v databázi "
"je třeba smazat)."

#, python-format
msgid "Unable to determine whether %(volumeName)s is composite or not."
msgstr "Nelze zjistit zda %(volumeName)s je složený nebo ne."

#, python-format
msgid "Unable to find VG: %s"
msgstr "Nelze najít skupinu svazku: %s"

#, python-format
msgid ""
"Unable to find default storage group for FAST policy : %(fastPolicyName)s."
msgstr ""
"Nelze najít výchozí skupinu úložiště pro zásadu FAST : %(fastPolicyName)s."

#, python-format
msgid "Unable to find service: %(service)s for given host: %(host)s."
msgstr "Nelze najít službu: %(service)s pro daného hostitele: %(host)s."

msgid "Unable to get associated pool of volume."
msgstr "Nelze získat přidruženou zásobu svazku."

#, python-format
msgid "Unable to get default storage group %(defaultSgName)s."
msgstr "Nelze získat výchozí skupinu úložiště %(defaultSgName)s."

msgid "Unable to get device mapping from network."
msgstr "Nelze získat mapování zařízení ze sítě."

#, python-format
msgid "Unable to get policy rule for fast policy: %(fastPolicyName)s."
msgstr "Nelze získat pravidlo zásady pro zásadu FAST: %(fastPolicyName)s."

#, python-format
msgid "Unable to locate Volume Group %s"
msgstr "Nelze najít skupinu svazku %s"

#, python-format
msgid "Unable to locate snapshot %s"
msgstr "Nelze nalézt snímek %s"

#, python-format
msgid "Unable to manage existing snapshot. Volume driver %s not initialized."
msgstr "Nelze spravovat existující snímek. Ovladač svazku %s není zaveden."

#, python-format
msgid "Unable to manage existing volume. Volume driver %s not initialized."
msgstr "Nelze spravovat existující svazek. Ovladač svazku %s není zaveden."

#, python-format
msgid "Unable to map %(vol)s to %(srv)s"
msgstr "Nelze mapovat %(vol)s do %(srv)s"

#, python-format
msgid "Unable to rename lun %s on array."
msgstr "Nelze přejmenovat lun %s v poli."

#, python-format
msgid "Unable to rename the logical volume for volume %s."
msgstr "Nelze přejmenovat logický svazek ve svazku %s."

#, python-format
msgid "Unable to rename the logical volume for volume: %s"
msgstr "Nelze přejmenovat logický svazek ve svazku: %s"

#, python-format
msgid "Unable to retrieve VolumeConfiguration: %s"
msgstr "Nelze získat nastavení svazku: %s"

#, python-format
msgid "Unable to retrieve pool instance of %(poolName)s on array %(array)s."
msgstr "Nelze získat instanci zásoby %(poolName)s v poli %(array)s."

#, python-format
msgid "Unable to terminate volume connection: %(err)s."
msgstr "Nelze ukončit připojení ke svazku: %(err)s."

msgid "Unexpected build error:"
msgstr "Neočekávaná chyba při sestavování:"

msgid "Unexpected error occurs in horcm."
msgstr "V horcm se vyskytly neočekávané chyby."

msgid "Unexpected error occurs in snm2."
msgstr "V snm2 se vyskytly neočekávané chyby."

#, python-format
msgid "Unexpected error when retype() revert tried to deleteVolumeSet(%s)"
msgstr ""
"Neočekávaná chyba když se vracel pokus přetypování o smazání sady svazků (%s)"

#, python-format
msgid "Unexpected error when retype() tried to deleteVolumeSet(%s)"
msgstr ""
"Neočekávaná chyba když přetypování se pokusilo o smazání sady svazků (%s)"

#, python-format
msgid "Unexpected error while invoking web service. Error - %s."
msgstr ""
"Při volání internetové služby se objevila neočekávaná chyba. Chyba - %s."

#, python-format
msgid "Unknown exception in post clone resize LUN %s."
msgstr "Neznámá výjimka při zvětšení LUN %s po klonování."

#, python-format
msgid "Unrecognized Login Response: %s"
msgstr "Nerozpoznaná odpověď přihlášení: %s"

#, python-format
msgid ""
"Update consistency group failed to add volume-%(volume_id)s: VolumeNotFound."
msgstr ""
"Aktualizace skupiny jednotnosti nemohla přidat svazek %(volume_id)s: Svazek "
"nenalezen."

#, python-format
msgid ""
"Update consistency group failed to remove volume-%(volume_id)s: "
"VolumeNotFound."
msgstr ""
"Aktualizace skupiny jednotnosti nemohla odstranit svazek %(volume_id)s: "
"Svazek nenalezen."

msgid "Update snapshot usages failed."
msgstr "Aktualizace využití snímku selhala."

msgid "Update volume model for transfer operation failed."
msgstr "Aktualizace modelu svazku pro operaci přenosu selhala."

#, python-format
msgid "Upload volume to image encountered an error (image-id: %(image_id)s)."
msgstr ""
"Při nahrávání svazku do obrazu nastala chyba (id obrazu: %(image_id)s)."

msgid "User does not have permission to change Storage Profile selection."
msgstr "Uživatel nemá oprávnění por změnu výběru profilu úložiště."

msgid "VGC-CLUSTER command blocked and cancelled."
msgstr "Příkaz clusteru VGC zablokován a zrušen."

#, python-format
msgid "Version string '%s' is not parseable"
msgstr "Řetězec verze '%s' nelze zpracovat"

#, python-format
msgid "Virtual Volume Set %s does not exist."
msgstr "Sada virtuálního svazku %s neexistuje."

#, python-format
msgid "Virtual disk device of backing: %s not found."
msgstr "Zařízení zálohy virtuálního disku. %s nenalezeno."

#, python-format
msgid "Vol copy job status %s."
msgstr "Stav úkolu kopírování svazku: %s."

#, python-format
msgid "Volume \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"Svazek \"%s\" nenalezen. Prosím zkontrolujte výstup příkazu \"dog vdi list\"."

#, python-format
msgid ""
"Volume %(name)s is not suitable for storage assisted migration using retype."
msgstr ""
"Svazek %(name)s není vhodný pro přesun využitím úložiště pomocí přetypování."

#, python-format
msgid "Volume %(name)s not found on the array."
msgstr "Svazek %(name)s nenalezen v poli."

#, python-format
msgid "Volume %(name)s not found on the array. No volume to delete."
msgstr "Svazek %(name)s nenalezen v poli. Žádný svazek ke smazání."

#, python-format
msgid ""
"Volume %(name)s not found on the array. No volume to migrate using retype."
msgstr ""
"Svazek %(name)s nenalezen v poli. Žádný svazek pro přesun pomocí přetypování."

#, python-format
msgid ""
"Volume %(volumeid)s failed to send assign command, ret: %(status)s output: "
"%(output)s"
msgstr ""
"Svazek %(volumeid)s nemohl odeslat příkaz pro přidělení, vráceno: "
"%(status)s, výstup: %(output)s"

#, python-format
msgid "Volume %s doesn't exist on array."
msgstr "Svazek %s neexistuje v poli."

#, python-format
msgid "Volume %s, not found on SF Cluster."
msgstr "Svazek %s nebyl nalezen v clusteru SF."

#, python-format
msgid "Volume %s: create failed"
msgstr "Vytvoření svazku %s selhalo"

#, python-format
msgid ""
"Volume %s: driver error when trying to retype, falling back to generic "
"mechanism."
msgstr ""
"Svazek %s: chyba ovladače při pokusu o přetypování, bude použit obecný "
"mechanismus."

#, python-format
msgid "Volume %s: manage failed."
msgstr "Správa svazku %s selhala."

#, python-format
msgid "Volume %s: rescheduling failed"
msgstr "Znovu naplánování svazku %s selhalo"

#, python-format
msgid "Volume %s: update volume state failed."
msgstr "Aktualizace stavu svazku %s selhala."

#, python-format
msgid ""
"Volume : %(volumeName)s has not been added to target storage group "
"%(storageGroup)s."
msgstr ""
"Svazek : %(volumeName)s nebyl přidán do cílové skupiny úložiště "
"%(storageGroup)s."

#, python-format
msgid ""
"Volume : %(volumeName)s has not been removed from source storage group "
"%(storageGroup)s."
msgstr ""
"Svazek : %(volumeName)s nebyl odstraněn ze zdrojové skupiny úložiště "
"%(storageGroup)s."

#, python-format
msgid ""
"Volume : %(volumeName)s. was not successfully migrated to target pool "
"%(targetPoolName)s."
msgstr ""
"Svazek : %(volumeName)s nebyl úspěšně přesunut do cílové zásoby "
"%(targetPoolName)s."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"accept_transfer operation!"
msgstr ""
"Svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o provedení "
"operace přijetí přenosu!"

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"attach_volume operation!"
msgstr ""
"Svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o provedení "
"operace připojení svazku!"

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"delete_volume operation!"
msgstr ""
"Svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o provedení "
"operace smazání svazku!"

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"detach_volume operation!"
msgstr ""
"Svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o provedení "
"operace odpojení svazku!"

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"extend_volume operation!"
msgstr ""
"Svazek s ID %s nebyl nalezen v clusteru SoldFire, při pokusu o provedení "
"operace rozšíření svazku!"

#, python-format
msgid ""
"Volume ID %s was not found on the zfssa device while attempting "
"delete_volume operation."
msgstr ""
"Svazek s ID %s nebyl nalezen na zařízení zfssa při pokusu o operaci smazání "
"svazku."

#, python-format
msgid "Volume already exists. %s"
msgstr "Svazek již existuje. %s"

msgid "Volume did not exist. It will not be deleted"
msgstr "Svazek neexistuje. Nebude smazán"

#, python-format
msgid "Volume driver %s not initialized"
msgstr "Ovladač svazku %s není zaveden"

msgid "Volume in unexpected state"
msgstr "Svazek je v neočekávaném stavu"

#, python-format
msgid "Volume in unexpected state %s, expected awaiting-transfer"
msgstr "Svazek v neočekávaném stavu %s, očekáván awaiting-transfer"

#, python-format
msgid "Volume migration failed due to exception: %(reason)s."
msgstr "Přesun svazku selhal kvůli výjimce: %(reason)s."

msgid "Volume must be detached for clone operation."
msgstr "Svazek musí být pro operaci klonování odpojen."

#, python-format
msgid "Volume size \"%sG\" is too large."
msgstr "Velikost svazku \"%sG\" je příliš velká."

#, python-format
msgid "VolumeType %s deletion failed, VolumeType in use."
msgstr "Mazání typu svazku %s selhalo, typ je používán."

#, python-format
msgid ""
"WebDAV operation failed with error code: %(code)s reason: %(reason)s Retry "
"attempt %(retry)s in progress."
msgstr ""
"Operace WebDAV selhala s chybovým kódem: %(code)s, důvod: %(reason)s. "
"Probíhá pokus %(retry)s."

#, python-format
msgid "WebDAV returned with %(code)s error during %(method)s call."
msgstr "WebDAV předal chybu %(code)s během volání %(method)s."

#, python-format
msgid ""
"Workload: %(workload)s is not valid. Valid values are DSS_REP, DSS, OLTP, "
"OLTP_REP, NONE."
msgstr ""
"Vytížení: %(workload)s není platné. Platné hodnoty jsou DSS_REP, DSS, OLTP, "
"OLTP_REP, NONE."

msgid "_find_mappings: volume is not active"
msgstr "Nalezení mapování: svazek není aktivní"

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %(vol)s does not have the specified vdisk copy "
"operation: orig=%(orig)s new=%(new)s."
msgstr ""
"Odstranění operace kopírování virtuálního disku: Svazek %(vol)s nemá zadanou "
"operaci kopírování: původní=%(orig)s, nové=%(new)s."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %(vol)s metadata does not have the specified vdisk "
"copy operation: orig=%(orig)s new=%(new)s."
msgstr ""
"Odstranění operace kopírování virtuálního disku: Popisná data svazku %(vol)s "
"nemají zadanou operaci kopírování: původní=%(orig)s, nové=%(new)s."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %s does not have any registered vdisk copy "
"operations."
msgstr ""
"Odstranění operace kopírování virtuálního disku: Svazek %s nemají žádné "
"registrované operace kopírování virtuálního disku."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume metadata %s does not have any registered vdisk "
"copy operations."
msgstr ""
"Odstranění operace kopírování virtuálního disku: Popisná data svazku %s "
"nemají žádné registrované operace kopírování virtuálního disku."

#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to host "
"%(host_name)s found."
msgstr ""
"Zrušení mapování virtuálního disku na hostiteli: Nenalezeno žádné mapování "
"svazku %(vol_name)s k hostiteli %(host_name)s."

#, python-format
msgid "_wait_for_job_complete failed after %(retries)d tries."
msgstr "Čekání na dokončení úkolu selhalo po %(retries)d pokusech."

#, python-format
msgid "_wait_for_sync failed after %(retries)d tries."
msgstr "Čekání na synchronizaci selhalo po %(retries)d pokusech."

#, python-format
msgid ""
"backup: %(vol_id)s failed to remove backup hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"záloha: %(vol_id)s nemohl odstranit pevný odkaz na zálohu z %(vpath)s do "
"%(bpath)s.\n"
"standardní výstup: %(out)s\n"
"chybový výstup: %(err)s"

#, python-format
msgid "can't create 2 volumes with the same name, %s"
msgstr "Nelze vytvořit 2 svazky se stejným názvem, %s"

msgid "cinder-rtstool is not installed correctly"
msgstr "cinder-rtstool není správně nainstalováno"

#, python-format
msgid ""
"delete: %(vol_id)s failed with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"smazání: %(vol_id)s selhalo, standardní výstup: %(out)s.\n"
"chybový výstup: %(err)s."

#, python-format
msgid "ensure_export: Volume %s not found on storage."
msgstr "Zajištění exportu: Svazek %s nebyl nalezen v úložišti."

#, python-format
msgid "error opening rbd image %s"
msgstr "chyba při otevírání obrazu rbd %s"

msgid "error refreshing volume stats"
msgstr "Při obnově statistik svazku došlo k chybě"

msgid "horcm command timeout."
msgstr "Příkazu horcm vypršel časový limit."

#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s."
msgstr ""
"Zavedení spojení: Shromáždění vlastností pro návrat svazku %(vol)s a "
"konektoru %(conn)s selhalo."

#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"Zavedení spojení: Shromáždění vlastností pro návrat svazku %(vol)s a "
"konektoru %(conn)s selhalo.\n"

msgid "iscsi_ip_address must be set!"
msgstr "iscsi_ip_address musí být nastavena!"

msgid "manage_existing: No source-name in ref!"
msgstr "Správa existujících: V odkazu není název zdroje!"

#, python-format
msgid "manage_existing_get_size: %s does not exist!"
msgstr "Správa existujících: Získání velikosti:%s neexistuje!"

msgid "manage_existing_get_size: No source-name in ref!"
msgstr "Správa existujících: Získání velikosti: V odkazu není název zdroje!"

msgid "model server went away"
msgstr "modelový server je nedostupný"

#, python-format
msgid "modify volume: %s does not exist!"
msgstr "změna svazku: %s neexistuje!"

msgid "san ip must be configured!"
msgstr "san ip musí být nastaveno!"

msgid "san_login must be configured!"
msgstr "san_login musí být nastaveno!"

msgid "san_password must be configured!"
msgstr "san_password musí být nastaveno!"

#, python-format
msgid "single_user auth mode enabled, but %(param)s not set"
msgstr ""
"Povolen režim ověření pomocí jednoho uživatele, ale %(param)s není nastaveno"

msgid "snm2 command timeout."
msgstr "Příkazu snm2 vypršel časový limit."

msgid ""
"storwize_svc_multihostmap_enabled is set to False, not allowing multi host "
"mapping."
msgstr ""
"storwize_svc_multihostmap_enabled je nastaven na False, neumožňující "
"mapování více hostitelů."

#, python-format
msgid "unmanage: Volume %s does not exist!"
msgstr "Zrušení správy: Svazek %s neexistuje!"

msgid ""
"zfssa_replication_ip not set in cinder.conf. zfssa_replication_ip is needed "
"for backend enabled volume migration. Continuing with generic volume "
"migration."
msgstr ""
"zfssa_replication_ip není nastaveno v cinder.conf. zfssa_replication_ip not "
"je potřebné pro přesun svazku za pomoci podpůrné vrstvy. Bude použita obecná "
"metoda přesunutí svazku."
