# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
# OpenStack Infra <zanata@openstack.org>, 2015. #zanata
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: cinder 9.0.0.0b4.dev103\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-09-11 18:25+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-03-25 02:49+0000\n"
"Last-Translator: SeYeon Lee <sy_lee@kr.ibm.com>\n"
"Language: ko-KR\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Korean (South Korea)\n"

#, python-format
msgid ""
"%(exception)s: Exception during revert of retype for volume %(volume_name)s. "
"Failed to remove from new volume set %(new_vvs)s."
msgstr ""
"%(exception)s: 볼륨 %(volume_name)s의 다시 입력 되돌리기 중에 예외가 발생했습"
"니다. 새 볼륨 세트 %(new_vvs)s에서 제거하는 데 실패했습니다."

#, python-format
msgid ""
"%(exception)s: Exception during revert of retype for volume %(volume_name)s. "
"Original volume set/QOS settings may not have been fully restored."
msgstr ""
"%(exception)s: 볼륨 %(volume_name)s의 다시 입력을 되돌리는 중에 예외가 발생했"
"습니다. 원래 볼륨 세트/QOS 설정이 완전히 복구되지 않았을 수 있습니다."

#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"%(fun)s: 예상치 못한 CLI 출력과 함께 실패했습니다. \n"
"명령: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"

#, python-format
msgid ""
"%(method)s %(url)s unexpected response status: %(response)s (expects: "
"%(expects)s)."
msgstr ""
"%(method)s %(url)s 예상치 못한 응답 상태: %(response)s (expects: "
"%(expects)s)."

#, python-format
msgid "%(name)s: %(value)s"
msgstr "%(name)s: %(value)s"

#, python-format
msgid "%s"
msgstr "%s"

#, python-format
msgid "'%(value)s' is an invalid value for extra spec '%(key)s'"
msgstr "'%(value)s'이(가) 추가 사양 '%(key)s'에 올바르지 않은 값임"

msgid "A valid secondary target MUST be specified in order to failover."
msgstr "장애 복구하려면 올바른 보조 대상을 지정해야 합니다."

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting create_snapshot operation!"
msgstr ""
"create_snapshot 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s의 계정"
"을 찾을 수 없습니다."

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting delete_volume operation!"
msgstr ""
"delete_volume 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s의 계정을 "
"찾을 수 없습니다."

#, python-format
msgid ""
"Account for Volume ID %s was not found on the SolidFire Cluster while "
"attempting unmanage operation!"
msgstr ""
"관리 취소 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s의 계정을 찾"
"을 수 없습니다."

#, python-format
msgid "Array Serial Number must be in the file %(fileName)s."
msgstr "배열 일련 번호가 %(fileName)s 파일에 있어야 합니다."

#, python-format
msgid "Array query failed - No response (%d)!"
msgstr "배열 쿼리 실패 - 응답이 없음(%d)!"

msgid "Array query failed. No capabilities in response!"
msgstr "배열 쿼리 실패. 응답에 기능이 없습니다."

msgid "Array query failed. No controllers in response!"
msgstr "배열 쿼리 실패. 응답에 제어기가 없습니다."

msgid "Array query failed. No global id in XML response!"
msgstr "배열 쿼리 실패. XML 응답에 글로벌 id가 없습니다."

msgid "Attaching snapshot from a remote node is not supported."
msgstr "원격 노드에서 스냅샷을 연결하는 기능은 지원되지 않습니다."

#, python-format
msgid "Authorizing request: %(zfssaurl)s retry: %(retry)d ."
msgstr "요청 승인: %(zfssaurl)s 재시도: %(retry)d ."

msgid "Backend returned err for lun export."
msgstr "백엔드에서 lun 내보내기 오류를 리턴했습니다."

#, python-format
msgid "Backup id %s is not invalid. Skipping reset."
msgstr "백업 id %s이(가) 올바르지 않습니다. 재설정을 건너뜁니다."

#, python-format
msgid ""
"Backup service %(configured_service)s does not support verify. Backup id "
"%(id)s is not verified. Skipping verify."
msgstr ""
"백업 서비스 %(configured_service)s이(가) 확인을 지원하지 않습니다. 백업 ID "
"%(id)s이(가) 확인되지 않습니다. 확인을 건너뜁니다."

#, python-format
msgid "Backup volume metadata failed: %s."
msgstr "백업 볼륨 메타데이터 실패: %s."

#, python-format
msgid "Bad response from server: %(url)s. Error: %(err)s"
msgstr "서버의 잘못된 응답: %(url)s. 오류: %(err)s"

#, python-format
msgid ""
"CG snapshot %(cgsnap)s not found when creating consistency group %(cg)s from "
"source."
msgstr ""
"소스에서 일관성 그룹 %(cg)s을(를) 작성할 때 CG 스냅샷 %(cgsnap)s을(를) 찾을 "
"수 없습니다."

#, python-format
msgid ""
"CLI fail: '%(cmd)s' = %(code)s\n"
"out: %(stdout)s\n"
"err: %(stderr)s"
msgstr ""
"CLI 실패: '%(cmd)s' = %(code)s\n"
"출력: %(stdout)s\n"
"오류: %(stderr)s"

msgid "Call to Nova delete snapshot failed"
msgstr "Nova를 호출하여 스냅샷을 삭제하는 데 실패"

msgid "Call to Nova to create snapshot failed"
msgstr "Nova를 호출하여 스냅샷을 작성하는 데 실패"

#, python-format
msgid "Call to json.loads() raised an exception: %s."
msgstr "json.loads() 호출에서 예외 발생: %s."

#, python-format
msgid "Can not discovery in %(target_ip)s with %(target_iqn)s."
msgstr "%(target_iqn)s(으)로 %(target_ip)s에서 검색할 수 없습니다."

msgid "Can not open the recent url, login again."
msgstr "최신 url을 열 수 없습니다. 다시 로그인하십시오."

#, python-format
msgid "Can't find volume to map %(key)s, %(msg)s"
msgstr "%(key)s을(를) 맵핑할 볼륨을 찾을 수 없음, %(msg)s"

msgid "Can't open the recent url, relogin."
msgstr "최신 url을 열 수 없음, 다시 로그인"

#, python-format
msgid ""
"Cannot add and verify tier policy association for storage group : "
"%(storageGroupName)s to FAST policy : %(fastPolicyName)s."
msgstr ""
"스토리지 그룹: %(storageGroupName)s의 계층 정책 연관을 확인하고 FAST 정책: "
"%(fastPolicyName)s에 추가할 수 없습니다."

#, python-format
msgid "Cannot clone image %(image)s to volume %(volume)s. Error: %(error)s."
msgstr ""
"이미지 %(image)s을(를) 볼륨 %(volume)s에 복제할 수 없습니다. 오류: %(error)s."

#, python-format
msgid "Cannot create or find an initiator group with name %(igGroupName)s."
msgstr "이름이 %(igGroupName)s인 개시자 그룹을 작성하거나 찾을 수 없습니다."

#, python-format
msgid "Cannot delete file %s."
msgstr "%s 파일을 삭제할 수 없습니다."

msgid "Cannot detect replica status."
msgstr "복제본 상태를 발견할 수 없습니다."

msgid "Cannot determine if Tiering Policies are supported."
msgstr "계층 지정 정책이 지원되는지 판별할 수 없습니다."

msgid "Cannot determine whether Tiering Policy is supported on this array."
msgstr "이 배열에서 계층 지정 정책이 지원되는지 판별할 수 없습니다."

#, python-format
msgid "Cannot find Consistency Group %s"
msgstr "일관성 그룹 %s을(를) 찾을 수 없음"

#, python-format
msgid ""
"Cannot find a portGroup with name %(pgGroupName)s. The port group for a "
"masking view must be pre-defined."
msgstr ""
"이름이 %(pgGroupName)s인 portGroup을 찾을 수 없습니다. 마스킹 보기의 포트 그"
"룹을 사전 정의해야 합니다."

#, python-format
msgid "Cannot find the fast policy %(fastPolicyName)s."
msgstr "빠른 정책 %(fastPolicyName)s을(를) 찾을 수 없습니다."

#, python-format
msgid ""
"Cannot find the new masking view just created with name %(maskingViewName)s."
msgstr ""
"방금 작성했으며 이름이 %(maskingViewName)s인 새 마스킹 보기를 찾을 수 없습니"
"다."

#, python-format
msgid "Cannot get QoS spec for volume %s."
msgstr "볼륨 %s의 QoS 사양을 가져올 수 없습니다."

#, python-format
msgid "Cannot get port group from masking view: %(maskingViewName)s. "
msgstr "마스킹 보기 %(maskingViewName)s에서 포트 그룹을 가져올 수 없습니다. "

msgid "Cannot get port group name."
msgstr "포트 그룹 이름을 가져올 수 없습니다."

#, python-format
msgid "Cannot get storage Group from job : %(storageGroupName)s."
msgstr "작업에서 스토리지 그룹을 가져올 수 없음: %(storageGroupName)s."

msgid "Cannot get storage system."
msgstr "스토리지 시스템을 가져올 수 없습니다."

#, python-format
msgid "Caught error: %(type)s %(error)s"
msgstr "오류 발견: %(type)s %(error)s"

#, python-format
msgid ""
"Changing the volume name from %(tmp)s to %(orig)s failed because %(reason)s"
msgstr ""
"%(reason)s(으)로 인해 볼륨 이름을 %(tmp)s에서 %(orig)s(으)로 변경하는 데 실패"

#, python-format
msgid ""
"Changing the volume name from %(tmp)s to %(orig)s failed because %(reason)s."
msgstr ""
"%(reason)s(으)로 인해 볼륨 이름을 %(tmp)s에서 %(orig)s(으)로 변경하는 데 실패"
"했습니다."

#, python-format
msgid "Clone %s not in prepared state!"
msgstr "복제본 %s이(가) 준비된 상태가 아닙니다."

#, python-format
msgid ""
"Clone volume \"%s\" already exists. Please check the results of \"dog vdi "
"list\"."
msgstr ""
"복제 볼륨 \"%s\"이(가) 이미 있습니다. \"dog vdi list\"의 결과를 확인하십시오."

#, python-format
msgid "Cloning of volume %s failed."
msgstr "볼륨 %s 복제에 실패했습니다."

#, python-format
msgid ""
"CloudByte does not have a volume corresponding to OpenStack volume [%s]."
msgstr "CloudByte에 OpenStack 볼륨 [%s]에 해당하는 볼륨이 없습니다."

#, python-format
msgid ""
"CloudByte operation [%(operation)s] failed for volume [%(vol)s]. Exhausted "
"all [%(max)s] attempts."
msgstr ""
"볼륨 [%(vol)s]의 CloudByte 조작 [%(operation)s]에 실패했습니다. [%(max)s] 시"
"도수가 모두 소진되었습니다."

#, python-format
msgid ""
"CloudByte snapshot information is not available for OpenStack volume [%s]."
msgstr "OpenStack 볼륨 [%s]의 CloudByte 스냅샷 정보를 사용할 수 없습니다."

#, python-format
msgid "CloudByte volume information not available for OpenStack volume [%s]."
msgstr "OpenStack 볼륨 [%s]의 CloudByte 볼륨 정보를 사용할 수 없습니다."

#, python-format
msgid "Cmd     :%s"
msgstr "Cmd     :%s"

#, python-format
msgid "Commit clone failed: %(name)s (%(status)d)!"
msgstr "복제본 커밋에 실패: %(name)s (%(status)d)!"

#, python-format
msgid "Commit failed for %s!"
msgstr "%s의 커밋에 실패했습니다."

#, python-format
msgid "Compute cluster: %s not found."
msgstr "컴퓨트 클러스터: %s을(를) 찾을 수 없음."

#, python-format
msgid "Configuration value %s is not set."
msgstr "구성 값 %s을(를) 설정하지 않았습니다."

#, python-format
msgid "Conflict detected in Virtual Volume Set %(volume_set)s: %(error)s"
msgstr "가상 볼륨 세트 %(volume_set)s에서 충돌 발견: %(error)s"

#, python-format
msgid "Connect to Flexvisor error: %s."
msgstr "Flexvisor에 연결 오류: %s."

#, python-format
msgid "Connect to Flexvisor failed: %s."
msgstr "Flexvisor에 연결 실패: %s."

msgid "Connection error while sending a heartbeat to coordination backend."
msgstr "하트비트를 조정 백엔드에 보내는 중에 연결 오류가 발생했습니다."

#, python-format
msgid "Connection to %s failed and no secondary!"
msgstr "%s에 연결에 실패했으며 보조가 없습니다."

#, python-format
msgid "Controller GET failed (%d)"
msgstr "제어기 GET 실패(%d)"

#, python-format
msgid "Copy offload workflow unsuccessful. %s"
msgstr "오프로드 워크플로 복사에 실패했습니다. %s"

#, python-format
msgid "Copy snapshot to volume for snapshot %(snap)s volume %(vol)s failed!"
msgstr "스냅샷 %(snap)s 볼륨 %(vol)s의 볼륨에 스냅샷을 복사하는 데 실패"

#, python-format
msgid "Could not GET allocation information (%d)!"
msgstr "할당 정보를 가져올 수 없습니다(%d)."

#, python-format
msgid "Could not calculate node utilization for node %s."
msgstr "노드 %s의 노드 활용도를 계산할 수 없습니다."

#, python-format
msgid "Could not connect to %(primary)s or %(secondary)s!"
msgstr "%(primary)s 또는 %(secondary)s에 연결할 수 없습니다."

#, python-format
msgid "Could not create snapshot set. Error: '%s'"
msgstr "스냅샷 세트를 작성할 수 없습니다. 오류: '%s'"

msgid "Could not decode scheduler options."
msgstr "스케줄러 옵션을 디코딩할 수 없습니다."

#, python-format
msgid "Could not delete failed image volume %(id)s."
msgstr "이미지 볼륨 %(id)s을(를) 삭제할 수 없습니다."

#, python-format
msgid "Could not delete the image volume %(id)s."
msgstr "이미지 볼륨 %(id)s을(를) 삭제할 수 없습니다."

#, python-format
msgid "Could not find a host for consistency group %(group_id)s."
msgstr "일관성 그룹 %(group_id)s의 호스트를 찾을 수 없습니다."

#, python-format
msgid "Could not find any hosts (%s)"
msgstr "호스트(%s)를 찾을 수 없음"

#, python-format
msgid ""
"Could not find port group : %(portGroupName)s. Check that the EMC "
"configuration file has the correct port group name."
msgstr ""
"포트 그룹: %(portGroupName)s을(를) 찾을 수 없습니다. EMC 구성 파일에 올바른 "
"포트 그룹 이름이 있는지 확인하십시오."

#, python-format
msgid "Could not find volume with name %(name)s. Error: %(error)s"
msgstr "이름이 %(name)s인 볼륨을 찾을 수 없습니다. 오류: %(error)s"

msgid ""
"Could not get performance base counter name. Performance-based scheduler "
"functions may not be available."
msgstr ""
"성능 기본 카운터 이름을 가져올 수 없습니다. 성능 기반 스케줄러 기능을 사용할 "
"수 없습니다."

#, python-format
msgid "Could not get utilization counters from node %s"
msgstr "노드 %s에서 활용도 카운터를 가져올 수 없음"

#, python-format
msgid "Could not log in to 3PAR array (%s) with the provided credentials."
msgstr "제공된 자격 증명으로 3PAR 배열(%s)에 로그인할 수 없습니다."

#, python-format
msgid "Could not log in to LeftHand array (%s) with the provided credentials."
msgstr "제공된 자격 증명으로 LeftHand 배열(%s)에 로그인할 수 없습니다."

#, python-format
msgid "Could not stat scheduler options file %(filename)s."
msgstr "스케줄러 옵션 파일 %(filename)s의 통계를 낼 수 없습니다."

#, python-format
msgid "Could not validate device %s"
msgstr "%s 장치를 검증할 수 없음"

#, python-format
msgid ""
"Create clone_image_volume: %(volume_id)sfor image %(image_id)s, failed "
"(Exception: %(except)s)"
msgstr ""
"이미지 %(image_id)s의 clone_image_volume: %(volume_id)s 작성 실패(예외: "
"%(except)s)"

#, python-format
msgid ""
"Create consistency group from snapshot-%(snap)s failed: SnapshotNotFound."
msgstr "스냅샷-%(snap)s에서 일관성 그룹 작성 실패."

#, python-format
msgid "Create consistency group from source %(source)s failed."
msgstr "소스 %(source)s에서 일관성 그룹을 작성하는 데 실패했습니다."

#, python-format
msgid ""
"Create consistency group from source cg-%(cg)s failed: "
"ConsistencyGroupNotFound."
msgstr "소스 cg-%(cg)s에서 일관성 그룹 작성 실패: ConsistencyGroupNotFound."

#, python-format
msgid "Create hypermetro error: %s."
msgstr "hypermetro 작성 오류: %s."

#, python-format
msgid ""
"Create new lun from lun for source %(src)s => destination %(dest)s failed!"
msgstr "소스 %(src)s => 대상 %(dest)s의 lun에서 새 lun을 작성하는 데 실패"

#, python-format
msgid "Create pair failed. Error: %s."
msgstr "쌍 작성 실패. 오류: %s."

msgid "Create replication volume error."
msgstr "복제 볼륨 작성 오류."

#, python-format
msgid "Create snapshot notification failed: %s"
msgstr "스냅샷 작성 알림 실패: %s"

#, python-format
msgid "Create volume failed from snapshot: %s"
msgstr "스냅샷에서 볼륨 작성 실패: %s"

#, python-format
msgid "Create volume notification failed: %s"
msgstr "볼륨 작성 알림 실패: %s"

#, python-format
msgid "Creation of snapshot failed for volume: %s"
msgstr "볼륨의 스냅샷 작성 실패: %s"

#, python-format
msgid "Creation of volume %s failed."
msgstr "볼륨 %s 작성에 실패했습니다."

msgid ""
"Creation request failed. Please verify the extra-specs set for your volume "
"types are entered correctly."
msgstr ""
"작성 요청에 실패했습니다. 볼륨 유형의 추가 사양 세트가 올바르게 입력되었는지 "
"확인하십시오."

msgid "DB error:"
msgstr "DB 오류:"

msgid "DBError encountered: "
msgstr "DBError 발생: "

msgid "DRBDmanage: too many assignments returned."
msgstr "DRBDmanage: 너무 많은 할당이 리턴되었습니다."

msgid "Default Storage Profile was not found."
msgstr "기본 스토리지 프로파일을 찾을 수 없습니다."

msgid ""
"Default volume type is not found. Please check default_volume_type config:"
msgstr ""
"기본 볼륨 유형을 찾을 수 없습니다. default_volume_type 구성을 확인하십시오."

msgid "Delete consistency group failed to update usages."
msgstr "일관성 그룹을 삭제하는 중 사용법을 업데이트하지 못했습니다."

#, python-format
msgid "Delete hypermetro error: %s."
msgstr "hypermetro 삭제 오류: %s."

msgid "Delete replication error."
msgstr "복제 삭제 오류."

msgid "Delete snapshot failed, due to snapshot busy."
msgstr "사용 중인 스냅샷으로 인해 스냅샷을 삭제하는 데 실패했습니다."

#, python-format
msgid "Delete snapshot notification failed: %s"
msgstr "스냅샷 삭제 알림 실패: %s"

#, python-format
msgid "Delete volume notification failed: %s"
msgstr "볼륨 삭제 알림 실패: %s"

#, python-format
msgid "Deleting snapshot %s failed"
msgstr "스냅샷 %s 삭제 실패"

#, python-format
msgid "Deleting zone failed %s"
msgstr "구역 삭제 실패 %s"

#, python-format
msgid "Deletion of volume %s failed."
msgstr "볼륨 %s 삭제에 실패했습니다."

#, python-format
msgid "Destination Volume Group %s does not exist"
msgstr "대상 볼륨 그룹 %s이(가) 없음"

#, python-format
msgid "Detach attachment %(attach_id)s failed."
msgstr "첨부 파일 %(attach_id)s의 연결을 끊는 데 실패했습니다."

#, python-format
msgid "Detach migration source volume failed:  %(err)s"
msgstr "마이그레이션 소스 볼륨의 연결을 해제하는 데 실패:  %(err)s"

msgid "Detach volume failed, due to remove-export failure."
msgstr "내보내기 제거 실패로 인해 볼륨 연결 해제에 실패했습니다."

msgid "Detach volume failed, due to uninitialized driver."
msgstr "초기화되지 않는 드라이버로 인해 볼륨 연결 해제에 실패했습니다."

msgid "Detaching snapshot from a remote node is not supported."
msgstr "원격 노드에서 스냅샷의 연결을 해제하는 기능은 지원되지 않습니다."

#, python-format
msgid "Did not find expected column name in lsvdisk: %s."
msgstr "lsvdisk에 예상 열 이름을 찾지 못함: %s."

msgid "Differential restore failed, trying full restore"
msgstr "차등 복원 실패, 전체 복원 시도"

#, python-format
msgid "Disable replication on volume failed with message: %s"
msgstr "볼륨에서 복제를 비활성화하는 데 실패하고 다음 메시지가 표시됨: %s"

#, python-format
msgid "Disconnection failed with message: %(msg)s."
msgstr "연결 해제에 실패하고 다음 메시지가 표시됨: %(msg)s."

msgid "Driver reported error during replication failover."
msgstr "복제 장애 복구 중에 드라이버에서 오류를 보고했습니다."

#, python-format
msgid ""
"Driver-based migration of volume %(vol)s failed. Move from %(src)s to "
"%(dst)s failed with error: %(error)s."
msgstr ""
"볼륨 %(vol)s의 드라이버 기반 마이그레이션에 실패했습니다. %(src)s에서 "
"%(dst)s(으)로 이동이 오류로 인해 실패: %(error)s."

#, python-format
msgid "Error Attaching volume %(vol)s."
msgstr "볼륨 %(vol)s을(를) 연결하는 중에 오류가 발생했습니다. "

#, python-format
msgid ""
"Error Create Group: %(groupName)s. Return code: %(rc)lu.  Error: %(error)s."
msgstr "그룹 작성 오류: %(groupName)s.  리턴 코드: %(rc)lu.  오류: %(error)s."

#, python-format
msgid ""
"Error Getting Snapshot: %(snapshot)s of Volume: %(lun)s in Pool: %(pool)s, "
"Project: %(project)s  Return code: %(ret.status)d, Message: %(ret.data)s."
msgstr ""
"%(pool)s 풀에 있는 %(project)s 프로젝트의 %(lun)s 볼륨에서 %(snapshot)s 스냅"
"샷을 가져오는 중 오류 발생. 리턴 코드: %(ret.status)d 메시지: %(ret.data)s."

#, python-format
msgid "Error JSONDecodeError. %s"
msgstr "JSONDecodeError 오류. %s"

#, python-format
msgid ""
"Error Setting Volume: %(lun)s to InitiatorGroup: %(initiatorgroup)s Pool: "
"%(pool)s Project: %(project)s  Return code: %(ret.status)d Message: "
"%(ret.data)s."
msgstr ""
"%(pool)s 풀 %(project)s 프로젝트에서 InitiatorGroup: %(initiatorgroup)s으로 "
"볼륨  %(lun)s을 설정하는 중 오류 발생. 리턴 코드: %(ret.status)d 메시지: "
"%(ret.data)s."

#, python-format
msgid "Error TypeError. %s"
msgstr "TypeError 오류. %s"

msgid "Error activating LV"
msgstr "LV 활성화 오류"

#, python-format
msgid "Error changing Storage Profile for volume %(original)s to %(name)s"
msgstr ""
"볼륨의 스토리지 프로파일을 %(original)s에서 %(name)s(으)로 변경 중 오류 발생"

#, python-format
msgid "Error cleaning up failed volume creation.  Msg - %s."
msgstr "실패한 볼륨 작성을 정리하는 중에 오류가 발생했습니다. 메시지 - %s."

msgid "Error cloning volume"
msgstr "볼륨 복제 오류"

msgid "Error closing channel."
msgstr "채널 닫기 오류."

#, python-format
msgid ""
"Error contacting glance server '%(netloc)s' for '%(method)s', %(extra)s."
msgstr ""
"'%(method)s', %(extra)s의 Glance 서버 '%(netloc)s'에 접속하는 중 오류가 발생"
"했습니다."

#, python-format
msgid "Error creating QOS rule %s"
msgstr "QOS 규칙 %s 작성 오류"

msgid "Error creating Volume"
msgstr "볼륨 작성 오류"

msgid "Error creating Volume Group"
msgstr "볼륨 그룹 작성 오류"

msgid "Error creating chap record."
msgstr "chap 레코드를 작성하는 중에 오류가 발생했습니다."

msgid "Error creating cloned volume"
msgstr "복제된 볼륨 작성 오류"

msgid "Error creating snapshot"
msgstr "스냅샷 작성 오류"

msgid "Error creating volume"
msgstr "볼륨 작성 오류"

#, python-format
msgid "Error creating volume. Msg - %s."
msgstr "볼륨을 작성하는 중에 오류가 발생했습니다. 메시지 - %s."

msgid "Error deactivating LV"
msgstr "LV 비활성화 오류"

msgid "Error deleting snapshot"
msgstr "스냅샷 삭제 에러"

#, python-format
msgid "Error detaching snapshot %(snapshot)s, due to remove export failure."
msgstr ""
"내보내기 제거 실패로 인해 스냅샷 %(snapshot)s의 연결을 해제하는 중 오류가 발"
"생했습니다."

#, python-format
msgid "Error detaching volume %(volume)s, due to remove export failure."
msgstr ""
"내보내기 제거 실패로 인해 볼륨 %(volume)s의 연결을 해제하는 중 오류가 발생했"
"습니다."

#, python-format
msgid "Error detaching volume %s"
msgstr "볼륨 %s 연결 해제 오류"

#, python-format
msgid "Error disassociating storage group from policy: %s."
msgstr "정책에서 스토리지 그룹의 연관을 해제하는 중 오류 발생: %s."

msgid "Error during re-export on driver init."
msgstr "드라이버 초기화 시 다시 내보내는 중에 오류가 발생했습니다."

msgid ""
"Error encountered on Cinder backend during thaw operation, service will "
"remain frozen."
msgstr ""
"thaw 조작 중에 Cinder 백엔드에서 오류 발생, 서비스가 동결된 상태로 남습니다."

msgid "Error executing SSH command."
msgstr "SSH 명령 실행 오류."

msgid "Error executing command via ssh."
msgstr "ssh를 통해 명령 실행 중에 오류 발생."

#, python-format
msgid "Error executing command via ssh: %s"
msgstr "ssh를 통해 명령 실행 중에 오류 발생: %s"

#, python-format
msgid "Error expanding volume %s."
msgstr "볼륨 %s 확장 오류."

msgid "Error extending Volume"
msgstr "볼륨 확장 오류"

msgid "Error extending volume"
msgstr "볼륨 확장 오류"

#, python-format
msgid "Error extending volume %(id)s. Ex: %(ex)s"
msgstr "볼륨 %(id)s 확장 오류. 예: %(ex)s"

#, python-format
msgid "Error extending volume: %(vol)s. Exception: %(ex)s"
msgstr "볼륨 확장 오류: %(vol)s. 예외: %(ex)s"

#, python-format
msgid "Error finding replicated pg snapshot on %(secondary)s."
msgstr "%(secondary)s에서 복제된 pg 스냅샷을 찾는 중 오류가 발생했습니다."

#, python-format
msgid "Error finding target pool instance name for pool: %(targetPoolName)s."
msgstr "풀의 대상 풀 인스턴스 이름을 찾는 중 오류 발생: %(targetPoolName)s."

#, python-format
msgid "Error getting FaultDomainList for %s"
msgstr "%s의 FaultDomainList 가져오기 오류"

#, python-format
msgid "Error getting LUN attribute. Exception: %s"
msgstr "LUN 속성 가져오기 오류. 실행: %s"

msgid "Error getting active FC target ports."
msgstr "활성 FC 대상 포트를 가져오는 중 오류가 발생했습니다."

msgid "Error getting active ISCSI target iqns."
msgstr "활성 ISCSI 대상 iqns를 가져오는 중 오류가 발생했습니다."

msgid "Error getting active ISCSI target portals."
msgstr "활성 ISCSI 대상 포털을 가져오는 중 오류가 발생했습니다."

msgid "Error getting array, pool, SLO and workload."
msgstr "배열, 풀, SLO 및 워크로드를 가져오는 중 오류가 발생했습니다."

msgid "Error getting chap record."
msgstr "chap 레코드를 가져오는 중에 오류가 발생했습니다."

msgid "Error getting name server info."
msgstr "이름 서버 정보 가져오기 오류."

msgid "Error getting show fcns database info."
msgstr "표시 fcns 데이터베이스 정보 가져오기 오류."

msgid "Error getting target pool name and array."
msgstr "대상 풀 이름과 배열을 가져오는 중 오류가 발생했습니다."

#, python-format
msgid "Error has occurred: %s"
msgstr "오류 발생: %s"

#, python-format
msgid "Error in copying volume: %s"
msgstr "볼륨 복사 오류: %s"

#, python-format
msgid ""
"Error in extending volume size: Volume: %(volume)s Vol_Size: %(vol_size)d "
"with Snapshot: %(snapshot)s Snap_Size: %(snap_size)d"
msgstr ""
"볼륨 크기 확장 오류: 볼륨: %(volume)s Vol_Size: %(vol_size)d 포함된 스냅샷: "
"%(snapshot)s Snap_Size: %(snap_size)d"

#, python-format
msgid "Error in workflow copy from cache. %s."
msgstr "캐시에서 워크플로우를 복사하는 데 실패했습니다. %s."

#, python-format
msgid "Error invalid json: %s"
msgstr "올바르지 않은 JSON 오류: %s"

msgid "Error manage existing get volume size."
msgstr "기존 볼륨 크기 가져오기를 관리하는 중 오류가 발생했습니다."

msgid "Error manage existing volume."
msgstr "기존 볼륨 관리 오류."

#, python-format
msgid "Error managing replay %s"
msgstr "재생 관리 오류 %s"

msgid "Error mapping VDisk-to-host"
msgstr " VDisk-호스트 맵핑 오류"

#, python-format
msgid "Error mapping volume: %s"
msgstr "볼륨 맵핑 오류: %s"

#, python-format
msgid ""
"Error migrating volume: %(volumename)s. to target pool %(targetPoolName)s."
msgstr ""
"볼륨 %(volumename)s을(를) 대상 풀 %(targetPoolName)s(으)로 마이그레이션하는 "
"중에 오류가 발생했습니다."

#, python-format
msgid "Error migrating volume: %s"
msgstr "볼륨 마이그레이션 오류: %s"

#, python-format
msgid ""
"Error occurred in the volume driver when updating consistency group "
"%(group_id)s."
msgstr ""
"일관성 그룹 %(group_id)s을(를) 업데이트할 때 볼륨 드라이버에서 오류가 발생했"
"습니다."

msgid ""
"Error occurred when adding hostgroup and lungroup to view. Remove lun from "
"lungroup now."
msgstr ""
"볼 hostgroup 및 lungroup을 추가할 때 오류가 발생했습니다. 이제 lungroup에서 "
"lun을 제거합니다."

#, python-format
msgid ""
"Error occurred when building request spec list for consistency group %s."
msgstr "일관성 그룹 %s의 요청 사양 목록을 빌드할 때 오류가 발생했습니다."

#, python-format
msgid "Error occurred when creating cgsnapshot %s."
msgstr "cg 스냅샷 %s을(를) 작성하는 중에 오류가 발생했습니다."

#, python-format
msgid ""
"Error occurred when creating cloned volume in the process of creating "
"consistency group %(group)s from source CG %(source_cg)s."
msgstr ""
"소스 CG %(source_cg)s에서 일관성 그룹 %(group)s을(를) 작성하는 프로세스 중에 "
"복제된 볼륨을 작성할 때 오류가 발생했습니다."

#, python-format
msgid ""
"Error occurred when creating consistency group %(cg)s from cgsnapshot "
"%(cgsnap)s."
msgstr ""
"cgsnapshot %(cgsnap)s에서 일관성 그룹  %(cg)s을(를) 작성하는 중에 오류가 발생"
"했습니다. "

#, python-format
msgid ""
"Error occurred when creating consistency group %(group)s from cgsnapshot "
"%(cgsnap)s."
msgstr ""
"cgsnapshot %(cgsnap)s에서 일관성 그룹 %(group)s을(를) 작성하는 중에 오류가 발"
"생했습니다. "

#, python-format
msgid ""
"Error occurred when creating consistency group %(group)s from source CG "
"%(source_cg)s."
msgstr ""
"소스 CG %(source_cg)s에서 일관성 그룹 %(group)s을(를) 작성할 때 오류가 발생했"
"습니다."

#, python-format
msgid "Error occurred when creating consistency group %s."
msgstr "일관성 그룹 %s을(를) 작성하는 중에 오류가 발생했습니다. "

#, python-format
msgid ""
"Error occurred when creating volume entry from snapshot in the process of "
"creating consistency group %(group)s from cgsnapshot %(cgsnap)s."
msgstr ""
"cgsnapshot %(cgsnap)s에서 일관성 그룹 %(group)s을(를) 작성하는 프로세스 중에 "
"스냅샷에서 볼륨 항목을 작성할 때 오류가 발생했습니다."

#, python-format
msgid "Error occurred when updating consistency group %(group_id)s."
msgstr "일관성 그룹 %(group_id)s을(를) 업데이트하는 중에 오류가 발생했습니다. "

#, python-format
msgid "Error occurred while cloning backing: %s during retype."
msgstr "다시 입력 중에 지원 %s을(를) 복제하는 중에 오류가 발생했습니다."

#, python-format
msgid "Error occurred while copying %(src)s to %(dst)s."
msgstr "%(src)s을(를) %(dst)s(으)로 복사하는 중에 오류가 발생했습니다."

#, python-format
msgid "Error occurred while copying image: %(id)s to volume: %(vol)s."
msgstr ""
"이미지 %(id)s을(를) 볼륨 %(vol)s(으)로 복사하는 중에 오류가 발생했습니다."

#, python-format
msgid "Error occurred while copying image: %(image_id)s to %(path)s."
msgstr ""
"이미지: %(image_id)s을(를) %(path)s에 복사하는 중에 오류가 발생했습니다."

msgid "Error occurred while creating temporary backing."
msgstr "임시 지원을 작성하는 중에 오류가 발생했습니다."

#, python-format
msgid "Error occurred while creating volume: %(id)s from image: %(image_id)s."
msgstr ""
"이미지 %(image_id)s에서 볼륨 %(id)s을(를) 작성하는 중에 오류가 발생했습니다."

#, python-format
msgid ""
"Error on execute %(command)s. Error code: %(exit_code)d Error msg: %(result)s"
msgstr ""
"%(command)s 실행 오류. 오류 코드: %(exit_code)d 오류 메시지: %(result)s"

#, python-format
msgid ""
"Error on execute command. Error code: %(exit_code)d Error msg: %(result)s"
msgstr "실행 명령 오류. 오류 코드: %(exit_code)d 오류 메시지: %(result)s"

msgid "Error parsing array from host capabilities."
msgstr "호스트 기능에서 배열을 구문 분석하는 중 오류가 발생했습니다."

msgid "Error parsing array, pool, SLO and workload."
msgstr "배열, 풀, SLO 및 워크로드를 구문 분석하는 중 오류가 발생했습니다."

msgid "Error parsing target pool name, array, and fast policy."
msgstr ""
"대상 풀 이름, 배열 및 빠른 정책을 구문 분석하는 중 오류가 발생했습니다."

#, python-format
msgid ""
"Error provisioning volume %(lun_name)s on %(volume_name)s. Details: %(ex)s"
msgstr ""
"%(volume_name)s에서 볼륨 %(lun_name)s을(를) 프로비저닝하는 중에 오류가 발생했"
"습니다. 세부 사항: %(ex)s"

msgid "Error querying thin pool about data_percent"
msgstr "data_percent에 대한 thin 풀 쿼리 오류"

msgid "Error renaming logical volume"
msgstr "논리 볼륨의 이름 변경 오류"

#, python-format
msgid "Error renaming volume %(original)s to %(name)s"
msgstr "볼륨의 이름을 %(original)s에서 %(name)s(으)로 변경하는 중 오류 발생"

#, python-format
msgid "Error resolving host %(host)s. Error - %(e)s."
msgstr "호스트 %(host)s을(를) 분석하는 중에 오류가 발생했습니다. 오류 - %(e)s."

#, python-format
msgid "Error retrieving LUN %(vol)s number"
msgstr "LUN %(vol)s 번호 검색 오류"

#, python-format
msgid "Error running SSH command: \"%s\"."
msgstr "SSH 명령 실행 중 오류: \"%s\""

#, python-format
msgid "Error running SSH command: %s"
msgstr "SSH 명령 실행 중 오류: %s"

msgid "Error running command."
msgstr "명령 실행 오류."

#, python-format
msgid ""
"Error scheduling %(volume_id)s from last vol-service: %(last_host)s : %(exc)s"
msgstr ""
"볼륨-서비스 %(last_host)s : %(exc)s에서 %(volume_id)s을(를) 스케줄링하는 중 "
"오류 발생"

msgid "Error sending a heartbeat to coordination backend."
msgstr "하트비트를 조정 백엔드에 보내는 중에 오류가 발생했습니다."

#, python-format
msgid "Error setting Flash Cache policy to %s - exception"
msgstr "플래시 캐시 정책을 %s(으)로 설정하는 중 오류 발생 - 예외"

msgid "Error starting coordination backend."
msgstr "조정 백엔드를 시작하는 중에 오류가 발생했습니다."

#, python-format
msgid "Error trying to change %(opt)s from %(old)s to %(new)s"
msgstr "%(opt)s을(를) %(old)s에서 %(new)s(으)로 변경하려는 중 오류 발생"

#, python-format
msgid "Error unmanaging replay %s"
msgstr "재생 %s 관리 취소 오류"

#, python-format
msgid "Error unmapping volume: %s"
msgstr "볼륨 맵핑 해제 오류: %s"

#, python-format
msgid "Error verifying LUN container %(bkt)s"
msgstr "LUN 컨테이너 %(bkt)s 확인 오류"

#, python-format
msgid "Error verifying iSCSI service %(serv)s on host %(hst)s"
msgstr "호스트 %(hst)s에서 iSCSI 서비스 %(serv)s을(를) 확인하는 중 오류 발생"

msgid "Error: unable to snap replay"
msgstr "오류: 재생을 스냅할 수 없음"

#, python-format
msgid "Exception cloning volume %(name)s from source volume %(source)s."
msgstr ""
"소스 볼륨 %(source)s에서 볼륨 %(name)s을(를) 복제하는 중 예외가 발생했습니다."

#, python-format
msgid "Exception creating LUN %(name)s in pool %(pool)s."
msgstr "풀 %(pool)s에서 LUN %(name)s을(를) 작성하는 중 예외가 발생했습니다."

#, python-format
msgid "Exception creating vol %(name)s on pool %(pool)s."
msgstr "풀 %(pool)s에서 볼륨 %(name)s을(를) 작성하는 중 예외가 발생했습니다."

#, python-format
msgid ""
"Exception creating volume %(name)s from source %(source)s on share %(share)s."
msgstr ""
"공유 %(share)s하는 소스 %(source)s에서 볼륨 %(name)s을(를) 작성하는 중 예외"
"가 발생했습니다."

#, python-format
msgid "Exception details: %s"
msgstr "예외 세부 사항: %s"

#, python-format
msgid "Exception during mounting %s"
msgstr "%s 마운트 중 예외"

#, python-format
msgid "Exception during mounting %s."
msgstr "%s 마운트 중 예외 발생."

msgid "Exception during mounting."
msgstr "마운트 중에 예외 발생"

#, python-format
msgid "Exception during snapCPG revert: %s"
msgstr "snapCPG 되돌리기 중에 예외 발생: %s"

msgid "Exception encountered: "
msgstr "예외 발생:"

#, python-format
msgid "Exception handling resource: %s"
msgstr "자원 처리 예외: %s"

msgid "Exception in string format operation"
msgstr "문자열 형식화 오퍼레이션의 예외"

msgid "Exception loading extension."
msgstr "확장을 로드하는 중에 예외가 발생했습니다."

#, python-format
msgid "Exception: %(ex)s"
msgstr "예외: %(ex)s"

#, python-format
msgid "Exception: %s"
msgstr "예외: %s"

#, python-format
msgid "Exception: %s."
msgstr "예외: %s."

#, python-format
msgid "Exec of \"rm\" command on backing file for %s was unsuccessful."
msgstr "%s 의 지원 파일에서 \"rm\" 명령을 실행하는 데 실패했습니다."

#, python-format
msgid "Exists snapshot notification failed: %s"
msgstr "스냅샷 존재 알림 실패: %s"

#, python-format
msgid "Exists volume notification failed: %s"
msgstr "볼륨 존재 알림 실패: %s"

msgid "Extend volume failed."
msgstr "볼륨 확장에 실패했습니다."

#, python-format
msgid "Extension of volume %s failed."
msgstr "볼륨 %s 확장에 실패했습니다."

msgid ""
"Extra spec replication:mode must be set and must be either 'sync' or "
"'periodic'."
msgstr ""
"추가 사양 replication:mode를 설정해야 하며 'sync' 또는 'periodic'이어야 합니"
"다."

msgid ""
"Extra spec replication:sync_period must be greater than 299 and less than "
"31622401 seconds."
msgstr ""
"추가 사양 replication:sync_period는 299 이상 31622401초 미만이어야 합니다."

#, python-format
msgid "Extra specs must be specified as capabilities:%s='<is> True'."
msgstr "추가 사양은 capabilities:%s='<is> True'로 지정해야 합니다"

msgid ""
"Extra specs must be specified as replication_type='<in> sync' or '<in> "
"async'."
msgstr ""
"추가 사양은 replication_type='<in> sync' 또는 '<in> async'로 지정해야 합니다."

msgid "FAST is not supported on this array."
msgstr "이 배열에서는 FAST가 지원되지 않습니다."

#, python-format
msgid "Failed collecting fcns database info for fabric %s"
msgstr "패브릭 %s의 fcns 데이터베이스 정보 수집 실패"

#, python-format
msgid "Failed collecting name server info from fabric %s"
msgstr "패브릭 %s에서 이름 서버 정보를 수집하는 데 실패"

#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr "패브릭 %s의 nsshow 정보를 수집하는 데 실패"

msgid "Failed collecting show fcns database for fabric"
msgstr "패브릭의 표시 fcns 데이터베이스 수집 실패"

#, python-format
msgid "Failed destroying volume entry %s"
msgstr "볼륨 항목 %s 영구 삭제 실패"

#, python-format
msgid "Failed destroying volume entry: %s."
msgstr "볼륨 항목 영구 삭제 실패: %s"

#, python-format
msgid ""
"Failed fetching snapshot %(snapshot_id)s bootable flag using the provided "
"glance snapshot %(snapshot_ref_id)s volume reference"
msgstr ""
"제공된 glance 스냅샷 %(snapshot_ref_id)s 볼륨 참조를 사용하여 스냅샷 "
"%(snapshot_id)s 부트 가능 플래그를 가져오는 데 실패"

#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr "패브릭 %s에서 활성 구역 세트를 가져오는 데 실패"

#, python-format
msgid "Failed getting zone status from fabric %s"
msgstr "패브릭 %s의 구역 상태 가져오기 실패"

#, python-format
msgid "Failed image conversion during cache creation: %s"
msgstr "캐시 작성 중에 이미지 전환 실패: %s"

#, python-format
msgid ""
"Failed notifying about the snapshot action %(event)s for snapshot %(snp_id)s."
msgstr ""
"스냅샷 %(snp_id)s의 스냅샷 작업 %(event)s에 대해 알리는 데 실패했습니다."

#, python-format
msgid ""
"Failed notifying about the volume action %(event)s for volume %(volume_id)s"
msgstr "볼륨 %(volume_id)s의 볼륨 작업 %(event)s에 대해 알리는 데 실패"

#, python-format
msgid "Failed notifying on %(topic)s payload %(payload)s"
msgstr "%(topic)s 페이로드 %(payload)s에 대한 알림 실패"

#, python-format
msgid ""
"Failed recovery attempt to create iscsi backing lun for Volume ID:"
"%(vol_id)s: %(e)s"
msgstr ""
"볼륨 ID:%(vol_id)s의 iscsi 지원 lun을 작성하기 위한 복구 시도에 실패: %(e)s"

#, python-format
msgid "Failed rolling back quota for %s reservations"
msgstr "%s 예약 할당량을 롤백하는 데 실패"

#, python-format
msgid "Failed rolling back quota for %s reservations."
msgstr "%s 예약 할당량을 롤백하는 데 실패."

#, python-format
msgid ""
"Failed setting source volume %(source_volid)s back to its initial "
"%(source_status)s status"
msgstr ""
"소스 볼륨 %(source_volid)s을(를) 초기 %(source_status)s 상태로 다시 설정하는 "
"데 실패"

#, python-format
msgid ""
"Failed to Roll back to re-add volume %(volumeName)s to default storage group "
"for fast policy %(fastPolicyName)s. Please contact your sysadmin to get the "
"volume returned to the default storage group."
msgstr ""
"빠른 정책 %(fastPolicyName)s의 기본 스토리지 그룹에 볼륨 %(volumeName)s을"
"(를) 다시 추가하기 위한 롤백에 실패했습니다. 기본 스토리지 그룹에 리턴된 볼륨"
"을 가져오려면 sysadmin에 문의하십시오."

#, python-format
msgid ""
"Failed to Roll back to re-add volume %(volumeName)s to default storage group "
"for fast policy %(fastPolicyName)s: Please contact your sys admin to get the "
"volume re-added manually."
msgstr ""
"빠른 정책 %(fastPolicyName)s의 기본 스토리지 그룹에 볼륨 %(volumeName)s을"
"(를) 다시 추가하기 위한 롤백에 실패했습니다. 수동으로 다시 추가한 볼륨을 가져"
"오려면 sysadmin에 문의하십시오."

#, python-format
msgid ""
"Failed to add %(volumeName)s to default storage group for fast policy "
"%(fastPolicyName)s."
msgstr ""
"빠른 정책 %(fastPolicyName)s에 대한 기본 스토리지 그룹에 %(volumeName)s 을"
"(를) 추가하지 못했습니다."

#, python-format
msgid "Failed to add %s to cg."
msgstr "%s을(를) cg에 추가하는 데 실패했습니다."

#, python-format
msgid "Failed to add device to handler %s"
msgstr "핸들러 %s에 장치를 추가하는 데 실패"

#, python-format
msgid "Failed to add initiator iqn %s to target"
msgstr "개시자 iqn %s을(를) 대상에 추가하지 못함"

#, python-format
msgid "Failed to add initiator to group  for SCST target %s"
msgstr "SCST 대상 %s의 그룹에 개시자를 추가하는 데 실패"

#, python-format
msgid "Failed to add lun to SCST target id:%(vol_id)s: %(e)s"
msgstr "SCST 대상 id:%(vol_id)s에 lun 추가 실패: %(e)s"

#, python-format
msgid "Failed to add multihost-access for volume \"%s\"."
msgstr "볼륨 \"%s\"의 다중 호스트 액세스를 추가하는 데 실패했습니다."

#, python-format
msgid ""
"Failed to add storage group %(storageGroupInstanceName)s to tier policy rule "
"%(tierPolicyRuleInstanceName)s."
msgstr ""
"스토리지 그룹 %(storageGroupInstanceName)s을(를) 계층 정책 규칙 "
"%(tierPolicyRuleInstanceName)s에 추가하지 못했습니다."

#, python-format
msgid "Failed to add target(port: %s)"
msgstr "대상(포트: %s)을 추가하는 데 실패"

msgid "Failed to apply replication:activereplay setting"
msgstr "replication:activereplay 설정을 적용하는 데 실패"

msgid "Failed to attach source volume for copy."
msgstr "복사할 소스 볼륨을 연결하는 데 실패했습니다."

#, python-format
msgid "Failed to attach volume %(vol)s."
msgstr "볼륨 %(vol)s에 연결하는 데 실패했습니다."

msgid "Failed to authenticate user."
msgstr "사용자를 인증하지 못했습니다."

#, python-format
msgid "Failed to check cluster status.(command: %s)"
msgstr "클러스터 상태를 확인하는 데 실패했습니다(명령: %s)."

#, python-format
msgid "Failed to clone image volume %(id)s."
msgstr "이미지 볼륨 %(id)s을(를) 복제하는 데 실패."

#, python-format
msgid "Failed to clone volume %(volume_id)s for image %(image_id)s."
msgstr ""
"이미지 %(image_id)s의 볼륨 %(volume_id)s을(를) 복제하는 데 실패했습니다."

#, python-format
msgid "Failed to clone volume.(command: %s)"
msgstr "볼륨을 복제하는 데 실패했습니다(명령: %s)."

#, python-format
msgid "Failed to close disk device %s"
msgstr "디스크 장치 %s 닫기 실패"

#, python-format
msgid ""
"Failed to collect return properties for volume %(vol)s and connector "
"%(conn)s."
msgstr ""
"%(vol)s 볼륨 및 %(conn)s 커넥터에 대한 리턴 특성을 수집하지 못했습니다."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "%s 예약을 커밋하는 데 실패"

#, python-format
msgid "Failed to copy %(src)s to %(dest)s."
msgstr "%(src)s을(를) %(dest)s에 복사하는 데 실패했습니다."

#, python-format
msgid "Failed to copy image %(image_id)s to volume: %(volume_id)s"
msgstr "이미지 %(image_id)s을(를) 볼륨: %(volume_id)s에 복사하는 데 실패"

#, python-format
msgid "Failed to copy image to volume: %(volume_id)s"
msgstr "볼륨: %(volume_id)s에 이미지를 복사하는 데 실패"

#, python-format
msgid "Failed to copy volume %(src)s to %(dest)s."
msgstr "볼륨 %(src)s을(를) %(dest)s에 복사하는 데 실패했습니다."

#, python-format
msgid "Failed to copy volume %(vol1)s to %(vol2)s"
msgstr "볼륨 %(vol1)s을(를) %(vol2)s에 복사하는 데 실패"

#, python-format
msgid "Failed to create %(conf)s for volume id:%(vol_id)s"
msgstr "볼륨 id:%(vol_id)s의 %(conf)s을(를) 작성하는 데 실패"

#, python-format
msgid "Failed to create CG from CGsnapshot. Exception: %s"
msgstr "CGSnapshot에서 CG 작성 실패. 예외: %s."

#, python-format
msgid "Failed to create CGSnapshot. Exception: %s."
msgstr "CGSnapshot 작성 실패. 예외: %s."

msgid ""
"Failed to create SOAP client.Check san_ip, username, password and make sure "
"the array version is compatible"
msgstr ""
"SOAP 클라이언트 작성에 실패했습니다. san_ip, 사용자 이름, 비밀번호를 확인하"
"고 배열 버전이 호환되는지 확인하십시오."

#, python-format
msgid ""
"Failed to create a first volume for storage group : %(storageGroupName)s."
msgstr ""
"스토리지 그룹: %(storageGroupName)s의 첫 번째 볼륨을 작성하는 데 실패했습니"
"다."

#, python-format
msgid "Failed to create blkio cgroup '%(name)s'."
msgstr "blkio cgroup '%(name)s'을(를) 작성하는 데 실패했습니다."

#, python-format
msgid "Failed to create clone of volume \"%s\"."
msgstr "볼륨 \"%s\"의 복제본을 작성하는 데 실패했습니다."

#, python-format
msgid "Failed to create cloned volume %s."
msgstr "복제된 볼륨 %s을(를) 작성하지 못했습니다."

#, python-format
msgid "Failed to create consistency group %(group_id)s."
msgstr "일관성 그룹 %(group_id)s을(를) 작성하는 데 실패했습니다."

#, python-format
msgid ""
"Failed to create default storage group for FAST policy : %(fastPolicyName)s."
msgstr ""
"FAST 정책: %(fastPolicyName)s에 대한 기본 스토리지 그룹을 작성하지 못했습니"
"다."

#, python-format
msgid "Failed to create group to SCST target %s"
msgstr "SCST 대상 %s에 그룹을 작성하는 데 실패"

#, python-format
msgid "Failed to create hardware id(s) on %(storageSystemName)s."
msgstr "%(storageSystemName)s에서 하드웨어 ID를 작성하지 못했습니다. "

#, python-format
msgid ""
"Failed to create iscsi target for Volume ID: %(vol_id)s. Please ensure your "
"tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""
"볼륨  ID: %(vol_id)s의 iscsi 대상을 작성하지 못했습니다. tgtd 구성 파일에 "
"'include %(volumes_dir)s/*'가 포함되었는지 확인하십시오."

#, python-format
msgid "Failed to create iscsi target for Volume ID: %(vol_id)s: %(e)s"
msgstr "볼륨 ID:%(vol_id)s:에 대한 iscsi 대상을 작성하지 못함: %(e)s"

#, python-format
msgid ""
"Failed to create iscsi target for volume id:%(vol_id)s. Please verify your "
"configuration in %(volumes_dir)s'"
msgstr ""
"볼륨 id:%(vol_id)s에 대한 iscsi 대상을 작성하지 못했습니다. "
"%(volumes_dir)s'에서 구성을 확인하십시오."

#, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "볼륨 id:%(vol_id)s: %(e)s에 대한 iscsi 대상을 작성하지 못했습니다. "

#, python-format
msgid "Failed to create iscsi target for volume id:%s"
msgstr "볼륨 id:%s에 대한 iscsi 대상을 작성하지 못했습니다. "

#, python-format
msgid "Failed to create iscsi target for volume id:%s."
msgstr "볼륨 id:%s에 대한 iscsi 대상을 작성하지 못했습니다. "

#, python-format
msgid "Failed to create manage_existing flow: %(object_type)s %(object_id)s."
msgstr ""
"manage_existing 흐르을 작성하는 데 실패: %(object_type)s %(object_id)s."

#, python-format
msgid "Failed to create snapshot of volume \"%s\"."
msgstr "볼륨 \"%s\"에 대한 스냅샷을 작성하지 못했습니다. "

#, python-format
msgid "Failed to create snapshot. (command: %s)"
msgstr "스냅샷을 작성하는 데 실패했습니다(명령: %s)."

#, python-format
msgid "Failed to create transfer record for %s"
msgstr "%s의 전송 레코드를 작성하는 데 실패"

#, python-format
msgid "Failed to create volume \"%s\"."
msgstr "볼륨 \"%s\"을(를) 작성하지 못함 "

#, python-format
msgid "Failed to create volume %s"
msgstr "%s 볼륨을 작성하지 못함 "

#, python-format
msgid "Failed to create volume %s."
msgstr "볼륨 %s을(를) 작성하지 못했습니다. "

#, python-format
msgid "Failed to create volume from snapshot \"%s\"."
msgstr "스냅샷 \"%s\"에서 볼륨을 작성하는 데 실패했습니다."

#, python-format
msgid "Failed to create volume. %s"
msgstr "볼륨을 작성하지 못했습니다. %s"

#, python-format
msgid "Failed to create volume: %(name)s (%(status)s)"
msgstr "볼륨을 작성하는 데 실패: %(name)s (%(status)s)"

#, python-format
msgid "Failed to created Cinder secure environment indicator file: %s"
msgstr "Cinder 보안 환경 표시기 파일을 작성하는 데 실패: %s"

#, python-format
msgid "Failed to delete initiator iqn %s from target."
msgstr "대상에서 개시자 iqn %s을(를) 삭제하지 못했습니다."

#, python-format
msgid "Failed to delete snapshot %(snap)s of volume %(vol)s."
msgstr "볼륨 %(vol)s의 스냅샷 %(snap)s을(를) 삭제하는 데 실패했습니다."

#, python-format
msgid "Failed to delete snapshot. (command: %s)"
msgstr "스냅샷을 삭제하는 데 실패했습니다(명령: %s)."

#, python-format
msgid ""
"Failed to delete the snapshot %(snap)s of CGSnapshot. Exception: "
"%(exception)s."
msgstr ""
"CGSnapshot의 스냅샷 %(snap)s을(를) 삭제하는 데 실패했습니다. 예외: "
"%(exception)s."

#, python-format
msgid ""
"Failed to delete the snapshot %(snap)s of cgsnapshot: %(cgsnapshot_id)s. "
"Exception: %(exception)s."
msgstr ""
"cgsnapshot: %(cgsnapshot_id)s의 스냅샷 %(snap)s을(를) 삭제하는 데 실패했습니"
"다. 예외: %(exception)s."

#, python-format
msgid "Failed to delete the volume %(vol)s of CG. Exception: %(exception)s."
msgstr "CG의 볼륨 %(vol)s을(를) 삭제하는 데 실패했습니다. 예외: %(exception)s."

#, python-format
msgid "Failed to delete volume \"%s\"."
msgstr "볼륨 \"%s\"을(를) 삭제하는 데 실패했습니다. "

#, python-format
msgid "Failed to delete volume %s"
msgstr "볼륨 %s을(를) 삭제하는 데 실패했습니다."

#, python-format
msgid "Failed to delete volume. %s"
msgstr "볼륨을 삭제하는 데 실패했습니다. %s"

#, python-format
msgid "Failed to ensure export of volume \"%s\"."
msgstr "볼륨 \"%s\" 내보내기를 확인하는 데 실패했습니다."

#, python-format
msgid "Failed to ensure export of volume %s"
msgstr "볼륨 %s 내보내기를 확인하는 데 실패했습니다."

#, python-format
msgid "Failed to export fiber channel target due to %s"
msgstr "%s(으)로 인해 파이버 채널 대상을 내보내는 데 실패"

#, python-format
msgid "Failed to extend volume: %(vol)s to size: %(size)s GB."
msgstr "볼륨 %(vol)s을(를) %(size)sGB 크기로 확장하는 데 실패했습니다."

#, python-format
msgid ""
"Failed to extend_volume %(name)s from %(current_size)sGB to %(new_size)sGB."
msgstr ""
"%(current_size)sGB에서 %(new_size)sGB(으)로 extend_volume %(name)s을(를) 수행"
"하는 데 실패했습니다."

#, python-format
msgid "Failed to failover volume %(volume_id)s to %(target)s: %(error)s."
msgstr ""
"볼륨 %(volume_id)s을(를) %(target)s(으)로 장애 복구하는 데 실패: %(error)s."

#, python-format
msgid "Failed to find %(s)s.  Result %(r)s"
msgstr "%(s)s을(를) 찾지 못했습니다. 결과 %(r)s"

msgid "Failed to get IQN!"
msgstr "IQN을 가져오는 데 실패"

msgid "Failed to get LUN information!"
msgstr "LUN 정보를 가져오는 데 실패했습니다."

#, python-format
msgid "Failed to get allocation information (%d)!"
msgstr "할당 정보를 가져오는 데 실패했습니다(%d)."

#, python-format
msgid "Failed to get allocation information: %(host)s (%(status)d)!"
msgstr "할당 정보: %(host)s (%(status)d)을(를) 가져오는 데 실패했습니다."

#, python-format
msgid "Failed to get device number for throttling: %(error)s"
msgstr "조절을 위해 장치 번호를 가져오는 데 실패: %(error)s"

#, python-format
msgid ""
"Failed to get driver initiator data for initiator %(initiator)s and "
"namespace %(namespace)s"
msgstr ""
"개시자 %(initiator)s 및 네임스페이스 %(namespace)s의 드라이버 개시자 데이터"
"를 가져오는 데 실패"

#, python-format
msgid "Failed to get fiber channel info from storage due to %(stat)s"
msgstr "%(stat)s(으)로 인해 스토리지에서 파이버 채널 정보를 가져오는 데 실패"

#, python-format
msgid "Failed to get fiber channel target from storage server due to %(stat)s"
msgstr ""
"%(stat)s(으)로 인해 스토리지 서버에서 파이버 채널 대상을 가져오는 데 실패"

#, python-format
msgid "Failed to get or create storage group %(storageGroupName)s."
msgstr ""
"스토리지 그룹 %(storageGroupName)s을(를) 가져오거나 작성하지 못했습니다."

#, python-format
msgid "Failed to get response: %s."
msgstr "응답 가져오기 실패: %s."

#, python-format
msgid "Failed to get server info due to %(state)s."
msgstr "%(state)s(으)로 인해 서버 정보를 가져오는 데 실패했습니다."

msgid "Failed to get sns table"
msgstr "sns 테이블 가져오기 실패"

#, python-format
msgid "Failed to get target wwpns from storage due to %(stat)s"
msgstr "%(stat)s(으)로 인해 스토리지에서 대상 wwpns를 가져오는 데 실패"

msgid "Failed to get updated stats from Datera Cluster."
msgstr "Datera 클러스터에서 업데이트된 통계를 가져오는 데 실패했습니다."

msgid "Failed to get updated stats from Datera cluster."
msgstr "Datera 클러스터에서 업데이트된 통계를 가져오는 데 실패했습니다."

#, python-format
msgid "Failed to get volume status. %s"
msgstr "볼륨 상태를 가져오는 데 실패했습니다. %s"

msgid "Failed to initialize connection"
msgstr "연결 초기화 실패"

#, python-format
msgid "Failed to initialize connection to volume \"%s\"."
msgstr "볼륨 \"%s\"에 대한 연결을 초기화하는 데 실패했습니다."

msgid "Failed to initialize connection."
msgstr "연결을 초기화하는 데 실패했습니다."

msgid "Failed to initialize driver."
msgstr "드라이버를 초기화하는 데 실패했습니다."

#, python-format
msgid "Failed to issue df command for path %(path)s, error: %(error)s."
msgstr "경로 %(path)s에서 df 명령 실행 실패, 오류: %(error)s."

#, python-format
msgid "Failed to issue mmgetstate command, error: %s."
msgstr "mmgetstate 명령 실행 실패, 오류: %s."

#, python-format
msgid "Failed to issue mmlsattr command for path %(path)s, error: %(error)s."
msgstr "경로 %(path)s에서 mmlsattr 명령 실행 실패, 오류: %(error)s."

#, python-format
msgid "Failed to issue mmlsattr command on path %(path)s, error: %(error)s"
msgstr "경로 %(path)s에서 mmlsattr 명령 실행 실패, 오류: %(error)s."

#, python-format
msgid "Failed to issue mmlsconfig command, error: %s."
msgstr "mmlsconfig 명령 실행 실패, 오류: %s."

#, python-format
msgid "Failed to issue mmlsfs command for path %(path)s, error: %(error)s."
msgstr "경로 %(path)s에서 mmlsfs 명령 실행 실패, 오류: %(error)s."

#, python-format
msgid "Failed to issue mmlsfs command, error: %s."
msgstr "mmlsfs 명령 실행 실패, 오류: %s."

#, python-format
msgid "Failed to load %s"
msgstr "%s을(를) 로드하는 데 실패"

msgid "Failed to load osapi_volume"
msgstr "osapi_volume을 로드하는 데 실패"

#, python-format
msgid "Failed to open iet session list for %s"
msgstr "%s의 iet 세션 목록을 여는 데 실패"

#, python-format
msgid "Failed to open volume from %(path)s."
msgstr "%(path)s에서 볼륨을 여는 데 실패했습니다."

msgid "Failed to perform replication failover"
msgstr "복제 장애 복구 수행 실패"

#, python-format
msgid "Failed to present volume %(name)s (%(status)d)!"
msgstr "볼륨 %(name)s (%(status)d)을(를) 표시하는 데 실패했습니다."

msgid "Failed to re-export volume, setting to ERROR."
msgstr "볼륨을 다시 내보내는 데 실패했습니다. ERROR로 설정합니다."

#, python-format
msgid "Failed to register image volume location %(uri)s."
msgstr "이미지 볼륨 위치 %(uri)s을(를) 등록하는 데 실패했습니다."

#, python-format
msgid ""
"Failed to remove %(volumeName)s from the default storage group for the FAST "
"Policy."
msgstr ""
"FAST 정책에 대한 기본 스토리지 그룹에서 %(volumeName)s 볼륨을 제거하지 못했습"
"니다."

#, python-format
msgid "Failed to remove %s from cg."
msgstr "cg에서 %s을(를) 제거하는 데 실패했습니다."

#, python-format
msgid "Failed to remove LUN %s"
msgstr "LUN %s 제거 실패"

#, python-format
msgid "Failed to remove iscsi target for Volume ID: %(vol_id)s: %(e)s"
msgstr "볼륨 ID:%(vol_id)s:에 대한 iscsi 대상을 제거하지 못함: %(e)s"

#, python-format
msgid "Failed to remove iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "볼륨 id:%(vol_id)s: %(e)s에 대한 iscsi 대상을 제거하지 못했습니다. "

#, python-format
msgid "Failed to remove iscsi target for volume id:%s"
msgstr "볼륨 id:%s에 대한 iscsi 대상을 제거하지 못했습니다. "

#, python-format
msgid "Failed to remove iscsi target for volume id:%s."
msgstr "볼륨 id:%s에 대한 iscsi 대상을 제거하지 못했습니다. "

#, python-format
msgid "Failed to rename %(new_volume)s into %(volume)s."
msgstr "%(new_volume)s의 이름을 %(volume)s(으)로 바꾸지 못했습니다."

msgid "Failed to rename the created snapshot, reverting."
msgstr "작성된 스냅샷의 이름을 바꾸는 데 실패, 되돌리는 중입니다."

#, python-format
msgid "Failed to rename volume %(existing)s to %(new)s. Volume manage failed."
msgstr ""
"볼륨 %(existing)s의 이름을 %(new)s(으)로 변경하지 못했습니다. 볼륨 관리에 실"
"패했습니다."

#, python-format
msgid ""
"Failed to rename volume %(existing)s to %(new)s. Volume unmanage failed."
msgstr ""
"볼륨 %(existing)s의 이름을 %(new)s(으)로 변경하는 데 실패했습니다. 볼륨 관리 "
"취소에 실패했습니다."

#, python-format
msgid "Failed to request async delete of migration source vol %(vol)s: %(err)s"
msgstr ""
"마이그레이션 소스 볼륨 %(vol)s의 비동기 삭제를 요청하는 데 실패: %(err)s"

#, python-format
msgid ""
"Failed to resize vdi. Shrinking vdi not supported. vdi: %(vdiname)s new "
"size: %(size)s"
msgstr ""
"vdi의 크기를 조정하는 데 실패했습니다. vdi 축소는 지원되지 않습니다. vdi: "
"%(vdiname)s 새 크기: %(size)s"

#, python-format
msgid ""
"Failed to resize vdi. Too large volume size. vdi: %(vdiname)s new size: "
"%(size)s"
msgstr ""
"vdi의 크기를 조정하는 데 실패했습니다. 볼륨 크기가 너무 큽니다. vdi: "
"%(vdiname)s 새 크기: %(size)s"

#, python-format
msgid "Failed to resize vdi. vdi not found. %s"
msgstr "vdi의 크기를 조정하는 데 실패했습니다. vdi를 찾을 수 없습니다. %s"

#, python-format
msgid "Failed to resize vdi. vdi: %(vdiname)s new size: %(size)s"
msgstr ""
"vdi의 크기를 조정하는 데 실패했습니다. vdi: %(vdiname)s 새 크기: %(size)s"

#, python-format
msgid "Failed to resize volume %(volume_id)s, error: %(error)s."
msgstr "볼륨 %(volume_id)s 크기 조정 실패, 오류: %(error)s."

#, python-format
msgid "Failed to retrieve volume SolidFire-ID: %s in get_by_account!"
msgstr "%s get_by_account!에서 SolidFire-ID 볼륨을 검색하지 못했습니다. "

#, python-format
msgid ""
"Failed to return volume %(volumeName)s to original storage pool. Please "
"contact your system administrator to return it to the correct location."
msgstr ""
"볼륨 %(volumeName)s을(를) 원래 스토리지 풀로 리턴하는 데 실패했습니다. 시스"
"템 관리자에게 문의하여 올바른 위치로 리턴하십시오."

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "%s 예약을 철회하는 데 실패"

#, python-format
msgid "Failed to run task %(name)s: %(cause)s"
msgstr "작업 %(name)s 실행 실패: %(cause)s"

#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr "schedule_%(method)s 실패: %(ex)s"

#, python-format
msgid "Failed to send request: %s."
msgstr "요청 보내기 실패: %s."

#, python-format
msgid "Failed to set 'enable' attribute for SCST target %s"
msgstr "SCST 대상 %s의 'enable' 속성을 설정하는 데 실패"

#, python-format
msgid "Failed to set attribute for enable target driver %s"
msgstr "대상 드라이버 %s을(를) 활성화하는 속성을 설정하는 데 실패"

#, python-format
msgid "Failed to set properties for volume %(existing)s. Volume manage failed."
msgstr ""
"볼륨 %(existing)s의 특성을 설정하지 못했습니다. 볼륨 관리에 실패했습니다."

#, python-format
msgid ""
"Failed to set properties for volume %(existing)s. Volume unmanage failed."
msgstr ""
"볼륨 %(existing)s의 특성을 설정하지 못했습니다. 볼륨 관리 취소에 실패했습니"
"다."

msgid "Failed to setup the Dell EqualLogic driver."
msgstr "Dell EqualLogic 드라이버를 설정하는 데 실패했습니다."

msgid "Failed to shutdown horcm."
msgstr "horcm을 시스템 종료하는 데 실패했습니다."

#, python-format
msgid "Failed to snap Consistency Group %s"
msgstr "일관성 그룹 %s을(를) 맞추는 데 실패"

msgid "Failed to start horcm."
msgstr "horcm을 시작하지 못했습니다."

msgid "Failed to terminate connection"
msgstr "연결 종료 실패"

#, python-format
msgid "Failed to terminate connection %(initiator)s %(vol)s"
msgstr "연결 %(initiator)s %(vol)s을(를) 종료하는 데 실패"

#, python-format
msgid "Failed to terminate connection to volume \"%s\"."
msgstr "볼륨 \"%s\"에 대한 연결을 종료하는 데 실패했습니다."

#, python-format
msgid "Failed to umount %(share)s, reason=%(stderr)s"
msgstr "%(share)s을(를) umount하는 데 실패, 이유=%(stderr)s"

#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id)s after removing iscsi "
"target"
msgstr ""
"iscsi 대상을 제거한 후 볼륨 id %(vol_id)s의 %(conf)s을(를) 업데이트하는 데 실"
"패"

#, python-format
msgid "Failed to update %(conf)s for volume id:%(vol_id)s"
msgstr "볼륨 id:%(vol_id)s의 %(conf)s을(를) 업데이트하는 데 실패"

#, python-format
msgid ""
"Failed to update %(volume_id)s metadata using the provided snapshot "
"%(snapshot_id)s metadata."
msgstr ""
"제공된 스냅샷 %(snapshot_id)s 메타데이터를 사용하여 %(volume_id)s 메타데이터"
"를 업데이트하는 데 실패했습니다."

#, python-format
msgid "Failed to update quota donating volume transfer id %s"
msgstr "볼륨 전송 id %s를 제공하는 할당량을 업데이트하는 데 실패"

#, python-format
msgid "Failed to update quota for consistency group %s."
msgstr "일관성 그룹 %s의 할당량을 업데이트하는 데 실패했습니다."

#, python-format
msgid "Failed to update quota for deleting volume: %s"
msgstr "볼륨 삭제를 위해 할당량을 업데이트하는 데 실패: %s"

#, python-format
msgid "Failed to update quota while deleting snapshots: %s"
msgstr "스냅샷을 삭제하는 중에 할당량 업데이트 실패: %s"

msgid "Failed to update quota while deleting volume."
msgstr "볼륨을 삭제하는 동안 할당량을 업데이트하는 데 실패했습니다."

msgid "Failed to update replay profiles"
msgstr "재생 프로파일을 업데이트하는 데 실패"

msgid "Failed to update storage profile"
msgstr "스토리지 프로파일을 업데이트하는 데 실패"

msgid "Failed to update usages deleting backup"
msgstr "백업을 삭제하는 중 사용법을 업데이트하지 못함"

msgid "Failed to update usages deleting snapshot"
msgstr "스냅샷을 삭제하는 중 사용법을 업데이트하지 못함"

msgid "Failed to update usages deleting volume."
msgstr "볼륨을 삭제하는 중 사용법을 업데이트하지 못했습니다."

#, python-format
msgid "Failed to update volume status: %s"
msgstr "볼륨 상태를 업데이트하는 데 실패: %s"

#, python-format
msgid ""
"Failed to verify that volume was added to storage group for FAST policy: "
"%(fastPolicyName)s."
msgstr ""
"FAST 정책의 스토리지 그룹에 볼륨이 추가되었는지 확인하는 데 실패: "
"%(fastPolicyName)s."

msgid "Failed to write in /etc/scst.conf."
msgstr "/etc/scst.conf에 쓰지 못했습니다."

#, python-format
msgid "Failed to write persistence file: %(path)s."
msgstr "영구 파일을 쓰는 데 실패: %(path)s."

#, python-format
msgid ""
"Failed updating %(snapshot_id)s metadata using the provided volumes "
"%(volume_id)s metadata"
msgstr ""
"제공된 %(volume_id)s 메타데이터를 사용하여 %(snapshot_id)s 메타데이터를 업데"
"이트하는 데 실패"

#, python-format
msgid ""
"Failed updating model of snapshot %(snapshot_id)s with creation provided "
"model %(model)s."
msgstr ""
"스냅샷 %(snapshot_id)s의 모델을 작성 제공 모델 %(model)s(으)로 업데이트하는 "
"데 실패했습니다."

#, python-format
msgid ""
"Failed updating model of snapshot %(snapshot_id)s with driver provided model "
"%(model)s."
msgstr ""
"스냅샷 %(snapshot_id)s의 모델을 드라이버 제공 모델 %(model)s(으)로 업데이트하"
"는 데 실패했습니다."

#, python-format
msgid ""
"Failed updating model of volume %(volume_id)s with creation provided model "
"%(model)s"
msgstr ""
"볼륨 %(volume_id)s의 모델을 작성 제공 모델 %(model)s(으)로 업데이트하는 데 실"
"패"

#, python-format
msgid ""
"Failed updating model of volume %(volume_id)s with driver provided model "
"%(model)s"
msgstr ""
"볼륨 %(volume_id)s의 모델을 드라이버 제공 모델 %(model)s(으)로 업데이트하는 "
"데 실패"

#, python-format
msgid "Failed updating snapshot %(snapshot_id)s with %(update)s."
msgstr "스냅샷 %(snapshot_id)s을(를) %(update)s(으)로 업데이트하는 데 실패."

#, python-format
msgid ""
"Failed updating snapshot metadata using the provided volumes %(volume_id)s "
"metadata"
msgstr ""
"제공된 %(volume_id)s 메타데이터를 사용하여 스냅샷 메타데이터를 업데이트하는 "
"데 실패"

#, python-format
msgid "Failed updating volume %(volume_id)s bootable flag to true"
msgstr "볼륨 %(volume_id)s 부트 가능 플래그를 true로 업데이트하는 데 실패"

#, python-format
msgid "Failed updating volume %(volume_id)s with %(update)s"
msgstr "볼륨 %(volume_id)s을(를) %(update)s(으)로 업데이트하는 데 실패"

#, python-format
msgid "Failed updating volume %(volume_id)s with %(updates)s"
msgstr "볼륨 %(volume_id)s을(를) %(updates)s(으)로 업데이트하는 데 실패"

#, python-format
msgid "Failure deleting staged tmp LUN %s."
msgstr "스테이징된 임시 LUN %s 삭제 실패."

#, python-format
msgid "Failure restarting snap vol. Error: %s."
msgstr "스냅 볼륨을 다시 시작하는 데 실패. 오류: %s."

msgid "Fetch volume pool name failed."
msgstr "볼륨 풀 이름을 가져오는 데 실패했습니다."

#, python-format
msgid ""
"FibreChannelDriver validate_connector failed. No '%(setting)s'. Make sure "
"HBA state is Online."
msgstr ""
"FibreChannelDriver validate_connector가 실패했습니다. '%(setting)s'가 없습니"
"다. HBA 상태가 온라인인지 확인하십시오."

#, python-format
msgid "Flexvisor failed to get event %(volume)s (%(status)s)."
msgstr ""
"Flexviso에서 이벤트 %(volume)s (%(status)s)을(를) 가져오는 데 실패했습니다."

#, python-format
msgid "Flexvisor failed to get pool %(id)s info."
msgstr "Flexvisor에서 풀 %(id)s 정보를 가져오는 데 실패했습니다."

#, python-format
msgid "Flexvisor failed to get pool list due to %s."
msgstr "%s(으)로 인해 Flexvisor에서 풀 목록을 가져오는 데 실패했습니다."

#, python-format
msgid "Flexvisor failed to get pool list.(Error: %d)"
msgstr "Flexvisor에서 풀 목록을 가져오는 데 실패했습니다(오류: %d)"

#, python-format
msgid "Found %(count)s volumes mapped to id: %(uuid)s."
msgstr "id: %(uuid)s에 맵핑된 %(count)s개의 볼륨을 찾을 수 없습니다. "

msgid "Free capacity not set: volume node info collection broken."
msgstr "여유 공간을 설정하지 않음: 볼륨 노드 정보 콜렉션이 중단되었습니다. "

#, python-format
msgid "GPFS is not active.  Detailed output: %s."
msgstr "GPFS가 활성이 아닙니다. 자세한 결과: %s."

msgid "Get LUN migration error."
msgstr "LUN 마이그레이션 가져오기 오류."

msgid "Get method error."
msgstr "메소드 가져오기 오류."

msgid "Get replication status for volume failed."
msgstr "볼륨의 복제본 상태를 가져오는 데 실패했습니다."

#, python-format
msgid "Host PUT failed (%s)."
msgstr "호스트 PUT 실패(%s)."

msgid "Host could not be found!"
msgstr "호스트를 찾을 수 없습니다."

#, python-format
msgid "ISCSI discovery attempt failed for:%s"
msgstr "%s에 대한 ISCSI 검색 시도 실패"

msgid "ISE FW version is not compatible with OpenStack!"
msgstr "ISE FW 버전이 OpenStack과 호환되지 않습니다."

msgid "ISE globalid not set!"
msgstr "ISE globalid가 설정되지 않습니다."

#, python-format
msgid "Image size %(img_size)dGB is larger than volume size %(vol_size)dGB."
msgstr "이미지 크기 %(img_size)dGB가 볼륨 크기 %(vol_size)dGB보다 큽니다."

#, python-format
msgid "Invalid API object: %s"
msgstr "올바르지 않은 API 오브젝트: %s"

#, python-format
msgid "Invalid JSON: %s"
msgstr "올바르지 않은 JSON: %s"

#, python-format
msgid "Invalid ReplayList return: %s"
msgstr "올바르지 않은 ReplayList 리턴: %s"

#, python-format
msgid "Invalid hostname %(host)s"
msgstr "올바르지 않은 호스트 이름 %(host)s"

msgid "Invalid replication target specified for failover"
msgstr "장애 복구를 위해 올바르지 않은 복제 대상이 지정됨"

msgid ""
"Issuing a fail-over failed because replication is not properly configured."
msgstr "복제가 적절하게 구성되지 않았으므로 장애 복구 실행에 실패했습니다."

#, python-format
msgid "JSON encode params %(param)s error: %(status)s."
msgstr "JSON 인코드 매개 변수 %(param)s 오류: %(status)s."

#, python-format
msgid "JSON transfer data error. %s."
msgstr "JSON 전송 데이터 오류. %s."

#, python-format
msgid "JSON transfer error: %s."
msgstr "JSON 전송 오류: %s."

#, python-format
msgid "LUN %(path)s geometry failed. Message - %(msg)s"
msgstr "LUN %(path)s 지오메트리에 실패했습니다. 메시지 - %(msg)s"

msgid "LUN extend failed!"
msgstr "LUN 확장 실패"

msgid "LUN unexport failed!"
msgstr "LUN 내보내기 취소 실패"

#, python-format
msgid ""
"Location info needed for backend enabled volume migration not in correct "
"format: %s. Continuing with generic volume migration."
msgstr ""
"백엔드 사용 볼륨 마이그레이션에 필요한 위치 정보가 올바른 형식: %s이(가) 아닙"
"니다. 일반 볼륨 마이그레이션을 계속합니다."

msgid ""
"Logging into the Datera cluster failed. Please check your username and "
"password set in the cinder.conf and start the cinder-volume service again."
msgstr ""
"Datera 클러스터에 로그인하는 데 실패했습니다. cinder.conf에 설정된 사용자 이"
"름과 비밀번호를 확인하고 cinder-volume 서비스를 다시 시작하십시오."

#, python-format
msgid ""
"Login error. URL: %(url)s\n"
"Reason: %(reason)s."
msgstr ""
"로그인 오류. URL: %(url)s\n"
"이유: %(reason)s."

#, python-format
msgid "Looks like masking view: %(maskingViewName)s has recently been deleted."
msgstr "마스킹 보기: %(maskingViewName)s이(가) 최근에 삭제된 것으로 보입니다."

#, python-format
msgid "Lun %s has dependent snapshots, skipping lun deletion."
msgstr "Lun %s에 종속 스냅샷이 있으므로 lun 삭제를 건너뜁니다."

#, python-format
msgid "Lun create for %s failed!"
msgstr "%s의 Lun 작성 실패"

#, python-format
msgid "Lun create snapshot for volume %(vol)s snapshot %(snap)s failed!"
msgstr "볼륨 %(vol)s 스냅샷 %(snap)s의 Lun 작성 스냅샷 실패"

#, python-format
msgid "Lun delete for %s failed!"
msgstr "%s의 Lun 삭제 실패"

msgid "Lun mapping returned null!"
msgstr "Lun 맵핑에서 널(null)을 리턴했습니다!"

#, python-format
msgid "MSGID%(id)04d-E: %(msg)s"
msgstr "MSGID%(id)04d-E: %(msg)s"

msgid "Manage exist volume failed."
msgstr "기존 볼륨 관리에 실패했습니다."

#, python-format
msgid ""
"Manager for service %(binary)s %(host)s is reporting problems, not sending "
"heartbeat. Service will appear \"down\"."
msgstr ""
"서비스 %(binary)s %(host)s의 관리자가 하트비트를 보내지 않고 문제점을 보고합"
"니다. 서비스가 \"작동 중지\"로 표시됩니다."

#, python-format
msgid ""
"Masking View creation or retrieval was not successful for masking view "
"%(maskingViewName)s. Attempting rollback."
msgstr ""
"마스킹 보기 %(maskingViewName)s의 마스킹 보기 작성 또는 검색에 성공하지 못했"
"습니다. 롤백을 시도합니다."

#, python-format
msgid ""
"Max retries reached deleting backup %(basename)s image of volume %(volume)s."
msgstr ""
"볼륨 %(volume)s의 백업 %(basename)s 이미지를 삭제하도록 허용된 최대 재시도 수"
"에 도달했습니다."

#, python-format
msgid "Message: %s"
msgstr "메시지: %s"

msgid "Model update failed."
msgstr "모델 업데이트에 실패했습니다."

#, python-format
msgid "Modify volume PUT failed: %(name)s (%(status)d)."
msgstr "수정 볼륨 PUT 실패: %(name)s (%(status)d)."

#, python-format
msgid "Mount failure for %(share)s after %(count)d attempts."
msgstr "%(count)d번의 시도 후에 %(share)s의 마운트 실패."

#, python-format
msgid "Mount failure for %(share)s."
msgstr "%(share)s의 마운트 실패."

#, python-format
msgid "Multiple replay profiles under name %s"
msgstr "%s(이)라는 이름의 여러 재생 프로파일"

msgid "No CLI output for firmware version check"
msgstr "펌웨어 버전 확인을 위한 CLI 출력이 없음"

#, python-format
msgid "No VIP configured for service %s"
msgstr "서비스 %s의 VIP가 구성되지 않음"

#, python-format
msgid ""
"No action required. Volume: %(volumeName)s is already part of pool: %(pool)s."
msgstr ""
"작업이 필요하지 않습니다. 볼륨: %(volumeName)s이(가) 이미 풀: %(pool)s의 일부"
"가 아닙니다."

#, python-format
msgid ""
"No action required. Volume: %(volumeName)s is already part of slo/workload "
"combination: %(targetCombination)s."
msgstr ""
"작업이 필요하지 않습니다. 볼륨: %(volumeName)s이(가) 이미 slo/워크로드 조합: "
"%(targetCombination)s의 일부입니다."

#, python-format
msgid ""
"No snapshots found in database, but %(path)s has backing file "
"%(backing_file)s!"
msgstr ""
"데이터베이스에서 스냅샷을 찾을 수 없지만t %(path)s에 지원 파일 "
"%(backing_file)s이(가) 있습니다."

#, python-format
msgid "Not able to configure PBM for vCenter server: %s"
msgstr "vCenter 서버의 PBM을 구성할 수 없음: %s"

#, python-format
msgid "OSError: command is %(cmd)s."
msgstr "OSError: 명령이 %(cmd)s입니다."

#, python-format
msgid "OSError: command is %s."
msgstr "OSError: 명령이 %s입니다."

#, python-format
msgid ""
"One of the components of the original masking view %(maskingViewName)s "
"cannot be retrieved so please contact your system administrator to check "
"that the correct initiator(s) are part of masking."
msgstr ""
"원래 마스킹 보기 %(maskingViewName)s의 구성 요소 중 하나를 검색할 수 없으므"
"로, 올바른 개시자가 마스킹의 일부인지 확인하도록 시스템 관리자에게 요청하십시"
"오."

#, python-format
msgid ""
"Only SLO/workload migration within the same SRP Pool is supported in this "
"version The source pool : %(sourcePoolName)s does not match the target "
"array: %(targetPoolName)s. Skipping storage-assisted migration."
msgstr ""
"이 버전에서는 동일한 SRP 풀의 SLO/워크로드 마이그레이션만 지원됩니다. 소스 "
"풀: %(sourcePoolName)s이(가) 대상 배열: %(targetPoolName)s과(와) 일치하지 않"
"습니다. 스토리지 지원 마이그레이션을 건너뜁니다."

msgid "Only available volumes can be migrated between different protocols."
msgstr "서로 다른 프로토콜 간에 사용 가능한 볼륨만 마이그레이션할 수 있습니다."

#, python-format
msgid "POST for host create failed (%s)!"
msgstr "호스트의 POST 작성에 실패했습니다(%s)."

#, python-format
msgid "Pipe1 failed - %s "
msgstr "Pipe1 실패 - %s "

#, python-format
msgid "Pipe2 failed - %s "
msgstr "Pipe2 실패 - %s "

msgid ""
"Please check your xml for format or syntax errors. Please see documentation "
"for more details."
msgstr ""
"xml에서 형식 또는 구문 오류를 확인하십시오. 자세한 내용은 문서를 참조하십시"
"오."

#, python-format
msgid "PoolName must be in the file %(fileName)s."
msgstr "PoolName은 파일 %(fileName)s에 있어야 합니다. "

#, python-format
msgid "Prepare clone failed for %s."
msgstr "%s의 복제본 준비에 실패했습니다."

msgid "Primary IP must be set!"
msgstr "기본 IP를 설정해야 합니다!"

msgid "Problem cleaning incomplete backup operations."
msgstr "불완전한 백업 조작 정리 문제."

#, python-format
msgid "Problem cleaning temp volumes and snapshots for backup %(bkup)s."
msgstr "백업 %(bkup)s의 임시 볼륨 및 스냅샷 정리 문제."

#, python-format
msgid "Problem cleaning up backup %(bkup)s."
msgstr "백업 %(bkup)s 정리 문제."

msgid "Promote volume replica failed."
msgstr "볼륨 복제본 홍보에 실패했습니다."

#, python-format
msgid ""
"Purity host %(host_name)s is managed by Cinder but CHAP credentials could "
"not be retrieved from the Cinder database."
msgstr ""
"Cinder에서 Purity 호스트 %(host_name)s을(를) 관리하지만 Cinder 데이터베이스에"
"서 CHAP 자격 증명을 검색할 수 없습니다."

#, python-format
msgid ""
"Purity host %(host_name)s is not managed by Cinder and can't have CHAP "
"credentials modified. Remove IQN %(iqn)s from the host to resolve this issue."
msgstr ""
"Cinder에서 Purity 호스트 %(host_name)s을(를) 관리하지 않으므로 CHAP 자격 증명"
"을 수정할 수 없습니다. 이 문제를 해결하려면 호스트에서 IQN %(iqn)s을(를) 제거"
"하십시오."

#, python-format
msgid "Qemu-img is not installed. OSError: command is %(cmd)s."
msgstr "Qemu-img가 설치되지 않았습니다. OSError: 명령이 %(cmd)s입니다."

#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""
"%(s_pid)s에 대한 할당량을 초과하여 %(s_size)sG만큼 볼륨을 확장하려고 시도, "
"(%(d_quota)dG 중 %(d_consumed)dG는 이미 사용됨)"

#, python-format
msgid "REST Not Available: %s"
msgstr "REST를 사용할 수 없음: %s"

#, python-format
msgid "Re-throwing Exception %s"
msgstr "%s 예외가 다시 발생"

#, python-format
msgid "Read response raised an exception: %s."
msgstr "읽기 응답에서 예외 발생: %s."

msgid "Recovered model server connection!"
msgstr "모델 서버 연결을 복구했습니다!"

#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr "실패한 실행에서 복구 중입니다. 번호 %s 시도"

msgid "Replication must be specified as '<is> True' or '<is> False'."
msgstr "복제는 '<is> True'나 '<is> False'로 지정되어야 합니다."

msgid ""
"Requested to setup thin provisioning, however current LVM version does not "
"support it."
msgstr ""
"씬 프로비저닝을 설정하도록 요청했지만 현재 LVM 버전에서 지원하지 않습니다."

#, python-format
msgid "Resizing %s failed. Cleaning volume."
msgstr "%s 크기 조정에 실패했습니다. 볼륨을 정리합니다."

#, python-format
msgid "Restore to volume %(volume)s finished with error - %(error)s."
msgstr ""
"볼륨 %(volume)s(으)로 복원이 완료되었지만 %(error)s 오류가 발생했습니다."

#, python-format
msgid "Retry %(retry)s times: %(method)s Failed %(rc)s: %(reason)s"
msgstr "%(retry)s번 재시도: %(method)s 실패 %(rc)s: %(reason)s"

#, python-format
msgid "Retype unable to find volume %s."
msgstr "재입력해도 볼륨 %s을(를) 찾을 수 없습니다."

msgid "Retype volume error."
msgstr "볼륨 다시 입력 오류."

msgid "Retype volume error. Create replication failed."
msgstr ""
"볼륨을 다시 입력하는 중에 오류가 발생했습니다. 복제 작성에 실패했습니다."

msgid "Retype volume error. Delete replication failed."
msgstr ""
"볼륨을 다시 입력하는 중에 오류가 발생했습니다. 복제 삭제에 실패했습니다."

#, python-format
msgid ""
"SLO: %(slo)s is not valid. Valid values are Bronze, Silver, Gold, Platinum, "
"Diamond, Optimized, NONE."
msgstr ""
"SLO: %(slo)s이(가) 올바르지 않습니다. 올바른 값은 Bronze, Silver, Gold, "
"Platinum, Diamond, Optimized, NONE입니다."

msgid ""
"ScVolume returned success with empty payload.  Attempting to locate volume"
msgstr ""
"ScVolume에서 빈 페이로드와 함께 성공을 리턴했습니다. 볼륨을 찾으려고 시도합니"
"다."

#, python-format
msgid "Server Busy retry request: %s"
msgstr "서버 사용 중 재시도 요청: %s"

msgid "Service not found for updating replication_status."
msgstr "replication_status를 업데이트하는 서비스를 찾을 수 없습니다."

#, python-format
msgid "Setting QoS for %s failed"
msgstr "%s의 QoS 설정 실패"

#, python-format
msgid ""
"Share %s ignored due to invalid format. Must be of form address:/export."
msgstr ""
"올바르지 않은 형식으로 인해 공유 %s이(가) 무시됩니다. format.  address:/"
"export 형식이어야 합니다."

#, python-format
msgid "Sheepdog is not installed. OSError: command is %s."
msgstr "Sheepdog가 설치되지 않았습니다. OSError: 명령이 %s입니다."

#, python-format
msgid ""
"Skipping remove_export. No iscsi_target ispresently exported for volume: %s"
msgstr ""
"remove_export를 건너뜁니다. 현재 %s 볼륨에 대한 iscsi_target을 내보내지 않았"
"습니다. "

#, python-format
msgid "Snapshot \"%s\" already exists."
msgstr "스냅샷 \"%s\"이(가) 이미 있습니다."

#, python-format
msgid ""
"Snapshot \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"스냅샷 \"%s\"을(를) 찾을 수 없습니다. \"dog vdi list\"의 결과를 확인하십시오."

#, python-format
msgid "Snapshot %(snapshotname)s not found on the array. No volume to delete."
msgstr ""
"배열에서 스냅샷 %(snapshotname)s을(를) 찾을 수 없습니다. 삭제할 볼륨이 없습니"
"다. "

#, python-format
msgid "Snapshot %s: create failed"
msgstr "스냅샷 %s: 작성 실패"

#, python-format
msgid "Snapshot %s: has clones"
msgstr "스냅샷 %s에 복제본이 있음"

msgid "Snapshot did not exist. It will not be deleted"
msgstr "스냅샷이 없으므로 삭제되지 않음"

#, python-format
msgid ""
"Source CG %(source_cg)s not found when creating consistency group %(cg)s "
"from source."
msgstr ""
"소스에서 일관성 그룹 %(cg)s을(를) 작성할 때 소스 CG  CG %(source_cg)s을(를) "
"찾을 수 없습니다."

#, python-format
msgid "Source snapshot %(snapshot_id)s cannot be found."
msgstr "소스 스냅샷 %(snapshot_id)s을(를) 찾을 수 없습니다."

#, python-format
msgid "Source snapshot cannot be found for target volume %(volume_id)s."
msgstr "대상 볼륨 %(volume_id)s의 소스 스냅샷을 찾을 수 없습니다."

#, python-format
msgid "Source volume %s not ready!"
msgstr "소스 볼륨 %s이(가) 준비되지 않았습니다."

#, python-format
msgid "Source volumes cannot be found for target volume %(volume_id)s."
msgstr "대상 볼륨 %(volume_id)s의 소스 볼륨을 찾을 수 없습니다."

#, python-format
msgid ""
"Src Volume \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"소스 볼륨 \"%s\"을(를) 찾을 수 없습니다. \"dog vdi list\"의 결과를 확인하십시"
"오."

#, python-format
msgid "Start synchronization failed. Error: %s."
msgstr "동기화 시작 실패. 오류: %s."

#, python-format
msgid "StdErr  :%s"
msgstr "StdErr :%s"

#, python-format
msgid "StdOut  :%s"
msgstr "StdOut: %s"

#, python-format
msgid "Storage Profile %s was not found."
msgstr "스토리지 프로파일 %s을(를) 찾을 수 없습니다. "

#, python-format
msgid "Storage profile: %s cannot be found in vCenter."
msgstr "스토리지 프로파일: vCenter에서 %s을(를) 찾을 수 없습니다."

msgid "Sync volume replica failed."
msgstr "볼륨 복제본 동기화에 실패했습니다."

#, python-format
msgid "TSM [%s] not found in CloudByte storage."
msgstr "CloudByte 스토리지에서 TSM [%s]을(를) 찾을 수 없습니다."

msgid "The Flexvisor service is unavailable."
msgstr "Flexvisor 서비스를 사용할 수 없습니다."

#, python-format
msgid "The NFS Volume %(cr)s does not exist."
msgstr "NFS 볼륨 %(cr)s이(가) 없습니다."

msgid "The connector does not contain the required information."
msgstr "커넥터에 필수 정보가 없습니다."

msgid ""
"The connector does not contain the required information: initiator is missing"
msgstr "커넥터에 필수 정보가 없음: 개시자가 누락되어 있음"

msgid ""
"The connector does not contain the required information: wwpns is missing"
msgstr "커넥터에 필수 정보가 없음: wwpns가 누락되어 있음"

#, python-format
msgid ""
"The primary array must have an API version of %(min_ver)s or higher, but is "
"only on %(current_ver)s, therefore replication is not supported."
msgstr ""
"기본 배열에 %(min_ver)s 이상의 API 버전이 있어야 하지만, %(current_ver)s만 있"
"으므로 복제가 지원되지 않습니다."

#, python-format
msgid ""
"The replication mode of %(type)s has not successfully established "
"partnership with the replica Storwize target %(stor)s."
msgstr ""
"%(type)s의 복제 모드가 복제본 Storwize 대상 %(stor)s과(와) 성공적으로 파트너"
"십을 맺을 수 없습니다."

msgid "The snapshot cannot be deleted because it is a clone point."
msgstr "스냅샷이 복제 지점이므로 삭제할 수 없습니다."

#, python-format
msgid ""
"The source array : %(sourceArraySerialNumber)s does not match the target "
"array: %(targetArraySerialNumber)s skipping storage-assisted migration."
msgstr ""
"소스 배열: %(sourceArraySerialNumber)s이(가) 대상 배열: "
"%(targetArraySerialNumber)s과(와) 일치하지 않아 스토리지 지원 마이그레이션을 "
"건너뜁니다."

#, python-format
msgid ""
"The source array : %(sourceArraySerialNumber)s does not match the target "
"array: %(targetArraySerialNumber)s, skipping storage-assisted migration."
msgstr ""
"소스 배열: %(sourceArraySerialNumber)s이(가) 대상 배열: "
"%(targetArraySerialNumber)s과(와) 일치하지 않아 스토리지 지원 마이그레이션을 "
"건너뜁니다."

#, python-format
msgid "The source volume %(volume_id)s cannot be found."
msgstr "소스 볼륨 %(volume_id)s을(를) 찾을 수 없습니다."

#, python-format
msgid "The volume driver requires %(data)s in the connector."
msgstr "볼륨 드라이버는 커넥터에 %(data)s이(가) 필요합니다."

msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr "볼륨 드라이버는 커넥터에 iSCSI 개시자 이름이 필요합니다. "

#, python-format
msgid "There are no valid hosts available in configured cluster(s): %s."
msgstr "구성된 클러스터에서 사용할 수 있는 올바른 호스트가 없음: %s."

#, python-format
msgid "There is no valid datastore satisfying requirements: %s."
msgstr "요구 사항을 만족하는 올바른 데이터 저장소가 없음: %s."

msgid "There must be at least one valid replication device configured."
msgstr "하나 이상의 올바른 복제 장치가 구성되어야 합니다."

#, python-format
msgid ""
"There was a problem with the failover (%(error)s) and it was unsuccessful. "
"Volume '%(volume)s will not be available on the failed over target."
msgstr ""
"장애 복구에 문제점이 있어(%(error)s) 실패했습니다. 장애 복구된 대상에서 볼륨 "
"'%(volume)s을(를) 사용할 수 없습니다."

#, python-format
msgid "There was an error deleting volume %(id)s: %(error)s."
msgstr "볼륨 %(id)s 삭제 오류: %(error)s."

msgid "This usually means the volume was never successfully created."
msgstr "일반적으로 볼륨이 성공적으로 작성된 적이 없음을 나타냅니다."

msgid "Tiering Policy is not supported on this array."
msgstr "이 배열에서 계층 지정 정책이 지원되지 않습니다."

#, python-format
msgid "Timed out deleting %s!"
msgstr "%s을(를) 삭제하는 중에 제한시간이 종료되었습니다."

#, python-format
msgid "Trying to create snapshot by non-existent LV: %s"
msgstr "존재하지 않는 LV에서 스냅샷을 작성하려고 시도: %s"

#, python-format
msgid "URLError: %s"
msgstr "URLError: %s"

#, python-format
msgid "Unable to access the Storwize back-end for volume %s."
msgstr "볼륨 %s의 Storwize 백엔드에 액세스할 수 없습니다."

#, python-format
msgid "Unable to create folder path %s"
msgstr "폴더 경로 %s을(를) 작성할 수 없음"

#, python-format
msgid ""
"Unable to create or get default storage group for FAST policy: "
"%(fastPolicyName)s."
msgstr ""
"FAST 정책 %(fastPolicyName)s에 대한 기본 스토리지 그룹을 작성하거나 확인하지 "
"못했습니다."

#, python-format
msgid "Unable to create volume %s from replay"
msgstr "재생에서 볼륨 %s을(를) 작성할 수 없습니다."

#, python-format
msgid "Unable to create volume on SC: %s"
msgstr "SC에서 볼륨을 작성할 수 없음: %s"

#, python-format
msgid "Unable to create volume. Volume driver %s not initialized"
msgstr "볼륨을 작성할 수 없습니다. 볼륨 드라이버 %s이(가) 초기화되지 않음"

msgid "Unable to delete busy volume."
msgstr "사용 중인 볼륨을 삭제할 수 없습니다."

#, python-format
msgid "Unable to delete due to existing snapshot for volume: %s"
msgstr "볼륨의 기존 스냅샷으로 인해 삭제할 수 없음: %s"

#, python-format
msgid "Unable to delete profile %s."
msgstr "%s 프로파일을 삭제할 수 없습니다."

#, python-format
msgid "Unable to delete replication for %(vol)s to %(dest)s."
msgstr "%(dest)s(으)로 복제된 %(vol)s을(를) 삭제할 수 없습니다."

msgid ""
"Unable to delete the destination volume during volume migration, (NOTE: "
"database record needs to be deleted)."
msgstr ""
"볼륨 마이그레이션 중에 대상 볼륨을 삭제할 수 없습니다(참고: 데이터베이스 레코"
"드를 삭제해야 함)."

#, python-format
msgid "Unable to determine whether %(volumeName)s is composite or not."
msgstr "%(volumeName)s의 복합 여부를 판별할 수 없습니다."

msgid "Unable to disconnect host from volume, could not determine Purity host"
msgstr ""
"볼륨에서 호스트의 연결을 해제할 수 없으므로, Purity 호스트를 판별할 수 없음"

msgid ""
"Unable to failover to the secondary. Please make sure that the secondary "
"back-end is ready."
msgstr ""
"보조로 장애 복구할 수 없습니다. 보조 백엔드가 준비되었는지 확인하십시오."

#, python-format
msgid "Unable to find VG: %s"
msgstr "VG에서 찾을 수 없습니다: %s"

#, python-format
msgid ""
"Unable to find default storage group for FAST policy : %(fastPolicyName)s."
msgstr ""
"FAST 정책 %(fastPolicyName)s에 대한 기본 스토리지 그룹을 찾을 수 없습니다."

#, python-format
msgid "Unable to find disk folder %(name)s on %(ssn)s"
msgstr "%(ssn)s에서 디스크 폴더 %(name)s을(를) 찾을 수 없음"

#, python-format
msgid "Unable to find mapping profiles: %s"
msgstr "맵핑 프로파일을 찾을 수 없음: %s"

#, python-format
msgid "Unable to find or create QoS Node named %s"
msgstr "%s(이)라는 QoS 노드를 찾거나 작성할 수 없음"

#, python-format
msgid "Unable to find service: %(service)s for given host: %(host)s."
msgstr "제공된 호스트: %(host)s의 서비스: %(service)s을(를) 찾을 수 없습니다."

msgid "Unable to get associated pool of volume."
msgstr "볼륨의 연관된 풀을 가져올 수 없습니다."

#, python-format
msgid "Unable to get default storage group %(defaultSgName)s."
msgstr "기본 스토리지 그룹 %(defaultSgName)s을(를) 가져올 수 없습니다."

msgid "Unable to get device mapping from network."
msgstr "네트워크에서 장치 맵핑을 가져올 수 없습니다."

#, python-format
msgid "Unable to get policy rule for fast policy: %(fastPolicyName)s."
msgstr "빠른 정책: %(fastPolicyName)s의 정책 규칙을 가져올 수 없습니다."

#, python-format
msgid "Unable to locate Volume Group %s"
msgstr "볼륨그룹 %s를 찾을 수 없음"

#, python-format
msgid "Unable to locate snapshot %s"
msgstr "스냅샷 %s을(를) 찾을 수 없음"

#, python-format
msgid "Unable to manage existing snapshot. Volume driver %s not initialized."
msgstr ""
"기존 스냅샷을 관리할 수 없습니다. 볼륨 드라이버 %s이(가) 초기화되지 않았습니"
"다."

#, python-format
msgid "Unable to manage existing volume. Volume driver %s not initialized."
msgstr ""
"기존 볼륨을 관리할 수 없습니다. 볼륨 드라이버 %s이(가) 초기화되지 않았습니다."

#, python-format
msgid "Unable to map %(vol)s to %(srv)s"
msgstr "%(vol)s을(를) %(srv)s에 맵핑할 수 없음"

#, python-format
msgid "Unable to rename lun %s on array."
msgstr "배열에서 lun %s의 이름을 바꿀 수 없습니다."

#, python-format
msgid "Unable to rename the logical volume for volume %s."
msgstr "볼륨 %s의 논리 볼륨 이름을 변경할 수 없습니다."

#, python-format
msgid "Unable to rename the logical volume for volume: %s"
msgstr "볼륨의 논리 볼륨 이름을 변경할 수 없음: %s"

#, python-format
msgid "Unable to replicate %(volname)s to %(destsc)s"
msgstr "%(volname)s을(를) %(destsc)s에 복제할 수 없음"

#, python-format
msgid "Unable to retrieve VolumeConfiguration: %s"
msgstr "VolumeConfiguration을 찾을 수 없음: %s"

#, python-format
msgid "Unable to retrieve pool instance of %(poolName)s on array %(array)s."
msgstr "배열 %(array)s에서 %(poolName)s의 풀 인스턴스를 검색할 수 없습니다."

#, python-format
msgid "Unable to terminate volume connection: %(err)s."
msgstr "볼륨 연결을 종료할 수 없음: %(err)s"

msgid "Unexpected build error:"
msgstr "예상치 못한 빌드 오류:"

msgid "Unexpected error occurs in horcm."
msgstr "horcm에서 예상치 못한 오류가 발생합니다."

msgid "Unexpected error occurs in snm2."
msgstr "snm2에서 예상치 못한 오류가 발생합니다."

#, python-format
msgid "Unexpected error when retype() revert tried to deleteVolumeSet(%s)"
msgstr ""
"retype() 되돌리기에서 VolumeSet(%s)을(를) 삭제하는 중에 예상치 못한 오류 발생"

#, python-format
msgid "Unexpected error when retype() tried to deleteVolumeSet(%s)"
msgstr "retype()에서 VolumeSet(%s)을(를) 삭제하는 중에 예상치 못한 오류 발생"

#, python-format
msgid "Unexpected error while invoking web service. Error - %s."
msgstr "웹 서비스를 호출하는 중에 예상치 못한 오류가 발생했습니다. 오류 - %s."

#, python-format
msgid "Unexpected exception during cache cleanup of snapshot %s"
msgstr "스냅샷 %s의 캐시 정리 중에 예상치 못한 예외 발생"

#, python-format
msgid "Unknown exception in post clone resize LUN %s."
msgstr "사후 복제 크기 조정 LUN %s에서 알 수 없는 예외가 발생했습니다."

#, python-format
msgid "Unrecognized Login Response: %s"
msgstr "인식되지 않은 로그인 응답: %s"

#, python-format
msgid ""
"Update consistency group failed to add volume-%(volume_id)s: VolumeNotFound."
msgstr ""
"일관성 그룹을 업데이트하는 중 볼륨-%(volume_id)s 추가 실패: VolumeNotFound."

#, python-format
msgid ""
"Update consistency group failed to remove volume-%(volume_id)s: "
"VolumeNotFound."
msgstr ""
"일관성 그룹을 업데이트하는 중 볼륨-%(volume_id)s 제거 실패: VolumeNotFound."

msgid "Update snapshot usages failed."
msgstr "스냅샷 사용법을 업데이트하는 데 실패했습니다."

msgid "Update volume model for transfer operation failed."
msgstr "전송 조작을 위한 볼륨 모델 업데이트에 실패했습니다."

#, python-format
msgid "Upload volume to image encountered an error (image-id: %(image_id)s)."
msgstr "이미지에 볼륨을 업로드하는 중 오류 발생(image-id: %(image_id)s)."

msgid "User does not have permission to change Storage Profile selection."
msgstr "사용자에게 스토리지 프로파일 선택을 변경할 권한이 없습니다."

msgid "VGC-CLUSTER command blocked and cancelled."
msgstr "VGC-CLUSTER 명령이 차단되어 취소되었습니다."

#, python-format
msgid "Version string '%s' is not parseable"
msgstr "버전 문자열 '%s'을(를) 구문 분석할 수 없음"

#, python-format
msgid "Virtual Volume Set %s does not exist."
msgstr "가상 볼륨 세트 %s이(가) 없습니다."

#, python-format
msgid "Virtual disk device of backing: %s not found."
msgstr "지원 가상 디스크 장치: %s을(를) 찾을 수 없습니다."

#, python-format
msgid "Vol copy job status %s."
msgstr "볼륨 복사 작업 상태 %s."

#, python-format
msgid "Volume \"%s\" not found. Please check the results of \"dog vdi list\"."
msgstr ""
"볼륨 \"%s\"을(를) 찾을 수 없습니다. \"dog vdi list\"의 결과를 확인하십시오."

#, python-format
msgid ""
"Volume %(name)s is not suitable for storage assisted migration using retype."
msgstr ""
"볼륨 %(name)s이(가) 재입력을 사용하는 스토리지 지원 마이그레이션에 적합하지 "
"않습니다."

#, python-format
msgid "Volume %(name)s not found on the array."
msgstr "배열에서 볼륨 %(name)s을(를) 찾을 수 없습니다."

#, python-format
msgid "Volume %(name)s not found on the array. No volume to delete."
msgstr "배열에서 %(name)s 볼륨을 찾을 수 없습니다. 삭제할 볼륨이 없습니다. "

#, python-format
msgid ""
"Volume %(name)s not found on the array. No volume to migrate using retype."
msgstr ""
"배열에서 %(name)s 볼륨을 찾을 수 없습니다. 다시 입력을 사용하여 마이그레이션"
"할 볼륨이 없습니다. "

#, python-format
msgid "Volume %(vol)s in the consistency group could not be deleted."
msgstr "일관성 그룹의 볼륨 %(vol)s을(를) 삭제할 수 없습니다."

#, python-format
msgid ""
"Volume %(volumeid)s failed to send assign command, ret: %(status)s output: "
"%(output)s"
msgstr ""
"볼륨 %(volumeid)s에서 지정 명령을 보내는 데 실패, ret: %(status)s 출력: "
"%(output)s"

#, python-format
msgid "Volume %s doesn't exist on array."
msgstr "배열에 %s 볼륨이 없습니다."

#, python-format
msgid "Volume %s, not found on SF Cluster."
msgstr "SF 클러스터에서 %s 볼륨을 찾을 수 없습니다. "

#, python-format
msgid "Volume %s: create failed"
msgstr "볼륨 %s: 작성 실패"

#, python-format
msgid ""
"Volume %s: driver error when trying to retype, falling back to generic "
"mechanism."
msgstr ""
"다시 입력하려고 할 때 볼륨 %s: 드라이버 오류 발생, 일반 메커니즘으로 장애 복"
"구."

#, python-format
msgid "Volume %s: manage failed."
msgstr "볼륨 %s: 관리 실패."

#, python-format
msgid "Volume %s: rescheduling failed"
msgstr "볼륨 %s: 재스케줄링 실패"

#, python-format
msgid "Volume %s: update volume state failed."
msgstr "볼륨 %s: 볼륨 상태 업데이트 실패."

#, python-format
msgid ""
"Volume : %(volumeName)s has not been added to target storage group "
"%(storageGroup)s."
msgstr ""
"대상 스토리지 그룹 %(storageGroup)s에 볼륨: %(volumeName)s이(가) 추가되지 않"
"았습니다."

#, python-format
msgid ""
"Volume : %(volumeName)s has not been removed from source storage group "
"%(storageGroup)s."
msgstr ""
"소스 스토리지 그룹 %(storageGroup)s에서 볼륨: %(volumeName)s이(가) 제거되지 "
"않았습니다."

#, python-format
msgid ""
"Volume : %(volumeName)s. was not successfully migrated to target pool "
"%(targetPoolName)s."
msgstr ""
"볼륨: %(volumeName)s이(가) 대상 풀 %(targetPoolName)s에 성공적으로 마이그레이"
"션되지 않았습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"accept_transfer operation!"
msgstr ""
"accept_transfer 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s을(를) "
"찾을 수 없습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"attach_volume operation!"
msgstr ""
"attach_volume 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s을(를) 찾"
"을 수 없습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"delete_volume operation!"
msgstr ""
"delete_volume 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s을(를) 찾"
"을 수 없습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"detach_volume operation!"
msgstr ""
"detach_volume 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s을(를) 찾"
"을 수 없습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the SolidFire Cluster while attempting "
"extend_volume operation!"
msgstr ""
"extend_volume 조작을 시도하는 중에 SolidFire Cluster에서 볼륨 ID %s을(를) 찾"
"을 수 없습니다."

#, python-format
msgid ""
"Volume ID %s was not found on the zfssa device while attempting "
"delete_volume operation."
msgstr ""
"delete_volume 조작을 시도하는 동안 zfssa 장치에서 볼륨 ID %s을(를) 찾을 수 없"
"습니다."

#, python-format
msgid "Volume already exists. %s"
msgstr "볼륨이 이미 있습니다. %s"

#, python-format
msgid ""
"Volume creation failed, deleting created snapshot %(volume_name)s@%(name)s"
msgstr "볼륨 작성에 실패하여, 작성된 스냅샷 %(volume_name)s@%(name)s 삭제"

#, python-format
msgid "Volume creation failed, deleting created snapshot %s"
msgstr "볼륨 작성에 실패하여, 작성된 스냅샷 %s 삭제"

msgid "Volume did not exist. It will not be deleted"
msgstr "볼륨이 없어 삭제되지 않음"

#, python-format
msgid "Volume driver %s not initialized"
msgstr "볼륨 드라이버 %s이(가) 초기화되지 않음"

msgid "Volume in unexpected state"
msgstr "예상치 못한 상태의 볼륨"

#, python-format
msgid "Volume in unexpected state %s, expected awaiting-transfer"
msgstr "예상치 못한 상태 %s의 볼륨, 예상된 상태는 전송 대기임"

#, python-format
msgid "Volume migration failed due to exception: %(reason)s."
msgstr "예외로 인해 볼륨 마이그레이션에 실패: %(reason)s."

msgid "Volume must be detached for clone operation."
msgstr "복제 조작을 수행하려면 볼륨의 연결을 해제해야 합니다."

#, python-format
msgid "Volume size \"%sG\" is too large."
msgstr "볼륨 크기 \"%sG\"이(가) 너무 큽니다."

#, python-format
msgid "VolumeType %s deletion failed, VolumeType in use."
msgstr "VolumeType %s 삭제 실패, VolumeType이 사용 중입니다."

#, python-format
msgid ""
"WebDAV operation failed with error code: %(code)s reason: %(reason)s Retry "
"attempt %(retry)s in progress."
msgstr ""
"WebDAV 조작에 실패, 오류 코드: %(code)s 이유: %(reason)s 재시도 시도 "
"%(retry)s이(가) 진행 중입니다."

#, python-format
msgid "WebDAV returned with %(code)s error during %(method)s call."
msgstr "%(method)s 호출 중에 WebDAV에서 %(code)s을(를) 리턴했습니다."

#, python-format
msgid ""
"Workload: %(workload)s is not valid. Valid values are DSS_REP, DSS, OLTP, "
"OLTP_REP, NONE."
msgstr ""
"워크로드: %(workload)s이(가) 올바르지 않습니다. 올바른 값은 DSS_REP, DSS, "
"OLTP, OLTP_REP, NONE입니다."

msgid "_check_version_fail: Parsing error."
msgstr "_check_version_fail: 구문 분석 오류."

msgid "_find_mappings: volume is not active"
msgstr "_find_mappings: 볼륨이 활성이 아님"

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %(vol)s does not have the specified vdisk copy "
"operation: orig=%(orig)s new=%(new)s."
msgstr ""
"_rm_vdisk_copy_op: 볼륨 %(vol)s에 지정된 vdisk 복사 조작이 없음: orig="
"%(orig)s new=%(new)s."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %(vol)s metadata does not have the specified vdisk "
"copy operation: orig=%(orig)s new=%(new)s."
msgstr ""
"_rm_vdisk_copy_op: 볼륨 %(vol)s 메타데이터에 지정된 vdisk 복사 조작이 없음: "
"orig=%(orig)s new=%(new)s."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume %s does not have any registered vdisk copy "
"operations."
msgstr "_rm_vdisk_copy_op: 볼륨 %s에 등록된 vdisk 복사 조작이 없습니다."

#, python-format
msgid ""
"_rm_vdisk_copy_op: Volume metadata %s does not have any registered vdisk "
"copy operations."
msgstr ""
"_rm_vdisk_copy_op: 볼륨 메타데이터 %s에 등록된 vdisk 복사 조작이 없습니다."

#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to host "
"%(host_name)s found."
msgstr ""
"_unmap_vdisk_from_host: 볼륨 %(vol_name)s과(와) 호스트 %(host_name)s의 맵핑"
"을 찾을 수 없습니다."

#, python-format
msgid "_wait_for_job_complete failed after %(retries)d tries."
msgstr "_wait_for_job_complete가 %(retries)d번의 재시도 후에 실패했습니다."

#, python-format
msgid "_wait_for_job_complete, failed after %(retries)d tries."
msgstr "_wait_for_job_complete가 %(retries)d번의 재시도 후에 실패했습니다."

#, python-format
msgid "_wait_for_sync failed after %(retries)d tries."
msgstr "_wait_for_sync가 %(retries)d번의 재시도 후에 실패했습니다."

#, python-format
msgid ""
"backup: %(vol_id)s failed to remove backup hardlink from %(vpath)s to "
"%(bpath)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."
msgstr ""
"백업: %(vol_id)s이(가) %(vpath)s에서 %(bpath)s으로 백업 하드 링크를 제거하지 "
"못했습니다.\n"
"stdout: %(out)s\n"
" stderr: %(err)s."

#, python-format
msgid "can't create 2 volumes with the same name, %s"
msgstr "동일한 이름  %s의 두 볼륨을 작성할 수 없음"

msgid "cinder-rtstool is not installed correctly"
msgstr "cinder-rtstool이 올바르게 설치되지 않음"

#, python-format
msgid ""
"delete: %(vol_id)s failed with stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"삭제: %(vol_id)s이(가) stdout에 실패함. stdout: %(out)s\n"
" stderr: %(err)s"

#, python-format
msgid "ensure_export: Volume %s not found on storage."
msgstr "ensure_export: 스토리지에 볼륨 %s을(를) 찾을 수 없습니다."

#, python-format
msgid "error opening rbd image %s"
msgstr "rbd 이미지 %s 열기 오류"

msgid "error refreshing volume stats"
msgstr "볼륨 상태를 새로 고치는 중 오류 발생"

msgid "horcm command timeout."
msgstr "horcm 명령의 제한시간이 초과되었습니다."

msgid "import pywbem failed!! pywbem is necessary for this volume driver."
msgstr ""
"pywbem 가져오기에 실패했습니다. 이 볼륨 드라이버에 pywbem이 필요합니다."

#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s."
msgstr ""
"initialize_connection: %(vol)s 볼륨 및 %(conn)s 커넥터에 대한 리턴 특성을 수"
"집하지 못했습니다."

#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"initialize_connection: %(vol)s 볼륨 및 %(conn)s 커넥터에 대한 리턴 특성을 수"
"집하지 못함.\n"

msgid "iscsi_ip_address must be set!"
msgstr "iscsi_ip_address를 설정해야 합니다."

msgid "manage_existing: No source-name in ref!"
msgstr "manage_existing: ref에 source-name이 없습니다."

#, python-format
msgid "manage_existing_get_size: %s does not exist!"
msgstr "manage_existing_get_size: %s이(가) 없습니다."

msgid "manage_existing_get_size: No source-name in ref!"
msgstr "manage_existing_get_size: ref에 source-name이 없습니다."

msgid "model server went away"
msgstr "모델 서버가 사라졌음"

#, python-format
msgid "modify volume: %s does not exist!"
msgstr "수정 볼륨: %s(이)가 없습니다."

msgid "san ip must be configured!"
msgstr "san ip를 구성해야 합니다."

msgid "san_login must be configured!"
msgstr "san_login을 구성해야 합니다."

msgid "san_password must be configured!"
msgstr "san_password를 구성해야 합니다."

#, python-format
msgid "single_user auth mode enabled, but %(param)s not set"
msgstr "single_user 인증 모드를 사용하지만 %(param)s이(가) 설정되지 않음"

msgid "snm2 command timeout."
msgstr "snm2 명령의 제한시간이 초과되었습니다."

msgid ""
"storwize_svc_multihostmap_enabled is set to False, not allowing multi host "
"mapping."
msgstr ""
"storwize_svc_multihostmap_enabled가 False로 설정되어 있어 다중 호스트 맵핑이 "
"허용되지 않습니다."

#, python-format
msgid "unmanage: Volume %s does not exist!"
msgstr "관리 취소: %s 볼륨이 없습니다."

msgid "zfssa_initiator cannot be empty when creating a zfssa_initiator_group."
msgstr ""
"zfssa_initiator_group을(를) 작성할 때 zfssa_initiator가 비어 있지 않아야 합니"
"다."

msgid ""
"zfssa_replication_ip not set in cinder.conf. zfssa_replication_ip is needed "
"for backend enabled volume migration. Continuing with generic volume "
"migration."
msgstr ""
"cinder.conf. zfssa_replication_ip에 설정되지 않은 zfssa_replication_ip가 백엔"
"드 사용 볼륨 마이그레이션에 필요합니다. 일반 볼륨 마이그레이션을 계속합니다."
